using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Threading;
using Linqraft.Core.Collections;
using Linqraft.Core.Configuration;
using Linqraft.Core.Utilities;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Linqraft.SourceGenerator;

/// <summary>
/// Analyzes projection syntax and builds template models for later source generation.
/// </summary>
internal static partial class ProjectionTemplateBuilder
{
    // Helper routines below resolve DTO shapes, capture transport, and lookup metadata shared across the analysis flow.
    /// <summary>
    /// Creates root dto template.
    /// </summary>
    private static GeneratedDtoTemplateModel CreateRootDtoTemplate(
        TypeSyntax resultTypeSyntax,
        SemanticModel semanticModel,
        InvocationExpressionSyntax invocation,
        INamedTypeSymbol? sourceType,
        string ownerHintName,
        CancellationToken cancellationToken,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        var resultType =
            semanticModel.GetTypeInfo(resultTypeSyntax, cancellationToken).Type as INamedTypeSymbol;
        if (resultType is IErrorTypeSymbol)
        {
            resultType = null;
        }

        var namespaceName =
            resultType is not null && !resultType.ContainingNamespace.IsGlobalNamespace
                ? SymbolNameHelper.GetNamespace(resultType.ContainingNamespace)
                : ResolveCallerNamespace(invocation, semanticModel, cancellationToken);
        var dtoName = resultType?.Name ?? GetUnqualifiedTypeName(resultTypeSyntax);
        var containingTypes = GetContainingTypes(resultType, cancellationToken);
        var containingTypeKey =
            containingTypes.Length == 0
                ? string.Empty
                : string.Join(".", containingTypes.Select(type => type.Name));
        var templateId = $"root:{namespaceName}|{containingTypeKey}|{dtoName}";
        var existingProperties =
            resultType
                ?.GetMembers()
                .OfType<IPropertySymbol>()
                .GroupBy(property => property.Name, StringComparer.Ordinal)
                .Select(group => group.First())
                .OrderBy(property => property.Name, StringComparer.Ordinal)
                .ToArray()
            ?? Array.Empty<IPropertySymbol>();

        return new GeneratedDtoTemplateModel
        {
            TemplateId = templateId,
            PlaceholderToken = CreateDtoPlaceholderToken(
                templateId,
                generatorOptions,
                cancellationToken
            ),
            Kind = GeneratedDtoTemplateKind.RootExplicit,
            PreferredNamespace = namespaceName,
            UseGlobalNamespaceFallback = string.IsNullOrWhiteSpace(namespaceName),
            Name = dtoName,
            ShapeHash = string.Empty,
            AccessibilityKeyword = resultType is null
                ? "public"
                : SymbolNameHelper.GetAccessibilityKeyword(resultType.DeclaredAccessibility),
            DeclaredIsRecord = resultType is null ? null : resultType.IsRecord,
            IsRoot = true,
            IsAutoGeneratedNested = false,
            Documentation = DocumentationExtractor.GetTypeDocumentation(
                sourceType,
                LinqraftCommentOutput.All,
                cancellationToken
            ),
            OwnerHintName = ownerHintName,
            Origins = new[] { CreateOrigin(invocation) },
            ShapeSignature = templateId,
            ContainingTypes = containingTypes,
            Properties = existingProperties
                .Select(property =>
                {
                    var typeTemplate = property.Type is null or IErrorTypeSymbol
                        ? "object"
                        : property.Type.ToFullyQualifiedTypeName();
                    return new GeneratedPropertyTemplateModel
                    {
                        Name = property.Name,
                        TypeTemplate = typeTemplate,
                        FallbackTypeTemplate = typeTemplate,
                        Documentation = null,
                        IsSuppressed = true,
                    };
                })
                .ToArray(),
        };
    }

    /// <summary>
    /// Analyzes captures.
    /// </summary>
    private static CaptureAnalysisResult AnalyzeCaptures(
        InvocationExpressionSyntax invocation,
        SemanticModel semanticModel,
        CancellationToken cancellationToken,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        // Captures move caller-scope values into an explicit transport object so the generated
        // interceptor can rehydrate them as locals before emitting the selector body.
        var captureArgument = GetCaptureArgument(
            invocation,
            semanticModel,
            generatorOptions,
            cancellationToken
        );
        if (captureArgument?.Expression is null)
        {
            return CaptureAnalysisResult.None;
        }

        if (captureArgument.Expression is AnonymousObjectCreationExpressionSyntax anonymousCapture)
        {
            return new CaptureAnalysisResult
            {
                TransportKind = CaptureTransportKind.AnonymousObject,
                TransportTypeName = null,
                Entries = anonymousCapture
                    .Initializers.Select(
                        (initializer, index) =>
                            CreateCaptureEntry(
                                GetAnonymousMemberName(initializer),
                                initializer.Expression,
                                index,
                                semanticModel,
                                cancellationToken
                            )
                    )
                    .ToArray(),
            };
        }

        if (captureArgument.Expression is LambdaExpressionSyntax captureLambda)
        {
            var body = GetLambdaBodyExpression(captureLambda);
            if (body is null)
            {
                return CaptureAnalysisResult.None;
            }

            var entries = body is TupleExpressionSyntax tuple
                ? tuple
                    .Arguments.Select(
                        (argument, index) =>
                            CreateCaptureEntry(
                                GetCaptureMemberName(argument.Expression),
                                argument.Expression,
                                index,
                                semanticModel,
                                cancellationToken,
                                $"Item{index + 1}"
                            )
                    )
                    .ToArray()
                :
                [
                    CreateCaptureEntry(
                        GetCaptureMemberName(body),
                        body,
                        0,
                        semanticModel,
                        cancellationToken
                    ),
                ];
            var bodyType =
                semanticModel.GetTypeInfo(body, cancellationToken).Type
                ?? semanticModel.GetTypeInfo(body, cancellationToken).ConvertedType;

            return new CaptureAnalysisResult
            {
                TransportKind = CaptureTransportKind.Delegate,
                TransportTypeName = bodyType?.ToFullyQualifiedTypeName() ?? "object",
                Entries = entries,
            };
        }

        return CaptureAnalysisResult.None;
    }

    /// <summary>
    /// Creates origin.
    /// </summary>
    private static GeneratedSourceOriginModel CreateOrigin(SyntaxNode node)
    {
        var lineSpan = node.GetLocation().GetLineSpan();
        var path = string.IsNullOrWhiteSpace(lineSpan.Path)
            ? node.SyntaxTree.FilePath
            : lineSpan.Path;
        return new GeneratedSourceOriginModel
        {
            FileName = string.IsNullOrWhiteSpace(path) ? "unknown" : Path.GetFileName(path),
            LineNumber = lineSpan.StartLinePosition.Line + 1,
        };
    }

    /// <summary>
    /// Creates dto placeholder token.
    /// </summary>
    private static string CreateDtoPlaceholderToken(
        string templateId,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        return $"{generatorOptions.DtoPlaceholderPrefix}_{HashingHelper.ComputeHash(templateId, 16, cancellationToken)}__";
    }

    /// <summary>
    /// Attempts to handle find projection invocation.
    /// </summary>
    private static bool TryFindProjectionInvocation(
        ExpressionSyntax expression,
        LinqraftGeneratorOptionsCore generatorOptions,
        out InvocationExpressionSyntax invocation
    )
    {
        switch (expression)
        {
            case ConditionalExpressionSyntax conditionalExpression:
                if (
                    TryFindProjectionInvocation(
                        conditionalExpression.WhenTrue,
                        generatorOptions,
                        out invocation
                    )
                )
                {
                    return true;
                }

                return TryFindProjectionInvocation(
                    conditionalExpression.WhenFalse,
                    generatorOptions,
                    out invocation
                );
            case BinaryExpressionSyntax binaryExpression
                when binaryExpression.IsKind(SyntaxKind.CoalesceExpression):
                if (
                    TryFindProjectionInvocation(
                        binaryExpression.Left,
                        generatorOptions,
                        out invocation
                    )
                )
                {
                    return true;
                }

                return TryFindProjectionInvocation(
                    binaryExpression.Right,
                    generatorOptions,
                    out invocation
                );
            case InvocationExpressionSyntax directInvocation
                when IsProjectionInvocation(directInvocation, generatorOptions):
                invocation = directInvocation;
                return true;
            case InvocationExpressionSyntax nestedInvocation
                when nestedInvocation.Expression is MemberAccessExpressionSyntax memberAccess:
                return TryFindProjectionInvocation(
                    memberAccess.Expression,
                    generatorOptions,
                    out invocation
                );
            case MemberAccessExpressionSyntax memberAccess:
                return TryFindProjectionInvocation(
                    memberAccess.Expression,
                    generatorOptions,
                    out invocation
                );
            case ConditionalAccessExpressionSyntax conditionalAccess
                when conditionalAccess.WhenNotNull
                    is InvocationExpressionSyntax whenNotNullInvocation
                    && IsProjectionInvocation(whenNotNullInvocation, generatorOptions):
                invocation = whenNotNullInvocation;
                return true;
            case ConditionalAccessExpressionSyntax conditionalAccess:
                if (
                    conditionalAccess.WhenNotNull is ExpressionSyntax whenNotNull
                    && TryFindProjectionInvocation(whenNotNull, generatorOptions, out invocation)
                )
                {
                    return true;
                }

                invocation = null!;
                return false;
            default:
                invocation = null!;
                return false;
        }
    }

    /// <summary>
    /// Determines whether the invocation is a projection invocation.
    /// </summary>
    private static bool IsProjectionInvocation(
        InvocationExpressionSyntax invocation,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        var name = GetInvocationName(invocation.Expression);
        return name == "Select"
            || name == "SelectMany"
            || name == generatorOptions.SelectExprMethodName
            || name == generatorOptions.SelectManyExprMethodName
            || name == generatorOptions.GroupByExprMethodName;
    }

    /// <summary>
    /// Resolves projection pattern.
    /// </summary>
    private static ProjectionPattern? ResolveProjectionPattern(
        ExpressionSyntax selectorBody,
        int typeArgumentCount
    )
    {
        if (selectorBody is AnonymousObjectCreationExpressionSyntax)
        {
            return typeArgumentCount == 0
                ? ProjectionPattern.Anonymous
                : ProjectionPattern.ExplicitDto;
        }

        if (selectorBody is ObjectCreationExpressionSyntax)
        {
            return ProjectionPattern.PredefinedDto;
        }

        return null;
    }

    /// <summary>
    /// Determines whether the invocation has an explicit result type.
    /// </summary>
    private static bool HasExplicitResultType(
        InvocationExpressionSyntax invocation,
        int typeArgumentCount,
        SemanticModel semanticModel,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        if (
            !IsUseLinqraftInvocationCandidate(
                invocation,
                semanticModel,
                generatorOptions,
                cancellationToken
            )
        )
        {
            return typeArgumentCount >= 2;
        }

        return GetUseLinqraftProjectionOperationKind(
            invocation,
            semanticModel,
            generatorOptions,
            cancellationToken
        ) switch
        {
            ProjectionOperationKind.GroupBy => typeArgumentCount >= 2,
            ProjectionOperationKind.Select or ProjectionOperationKind.SelectMany =>
                typeArgumentCount >= 1,
            _ => false,
        };
    }

    /// <summary>
    /// Determines whether the invocation is an use linqraft invocation candidate.
    /// </summary>
    private static bool IsUseLinqraftInvocationCandidate(
        InvocationExpressionSyntax invocation,
        SemanticModel semanticModel,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        return GetUseLinqraftProjectionOperationKind(
            invocation,
            semanticModel,
            generatorOptions,
            cancellationToken
        )
            is not null;
    }

    /// <summary>
    /// Gets lambda body expression.
    /// </summary>
    private static ExpressionSyntax? GetLambdaBodyExpression(LambdaExpressionSyntax lambda)
    {
        return lambda.Body as ExpressionSyntax;
    }

    /// <summary>
    /// Gets lambda parameter name.
    /// </summary>
    private static string GetLambdaParameterName(LambdaExpressionSyntax lambda)
    {
        return lambda switch
        {
            SimpleLambdaExpressionSyntax simple => simple.Parameter.Identifier.ValueText,
            ParenthesizedLambdaExpressionSyntax parenthesized => parenthesized
                .ParameterList.Parameters.FirstOrDefault()
                ?.Identifier.ValueText
                ?? "x",
            _ => "x",
        };
    }

    /// <summary>
    /// Determines whether the lambda uses a projection helper parameter.
    /// </summary>
    private static bool UsesProjectionHelperParameter(LambdaExpressionSyntax lambda)
    {
        return lambda is ParenthesizedLambdaExpressionSyntax parenthesized
            && parenthesized.ParameterList.Parameters.Count == 2;
    }

    /// <summary>
    /// Gets projection helper parameter name.
    /// </summary>
    private static string? GetProjectionHelperParameterName(LambdaExpressionSyntax lambda)
    {
        return
            lambda is ParenthesizedLambdaExpressionSyntax parenthesized
            && parenthesized.ParameterList.Parameters.Count == 2
            ? parenthesized.ParameterList.Parameters[1].Identifier.ValueText
            : null;
    }

    /// <summary>
    /// Gets projection helper parameter type name.
    /// </summary>
    private static string? GetProjectionHelperParameterTypeName(
        LambdaExpressionSyntax lambda,
        SemanticModel semanticModel,
        CancellationToken cancellationToken
    )
    {
        if (
            lambda is not ParenthesizedLambdaExpressionSyntax parenthesized
            || parenthesized.ParameterList.Parameters.Count != 2
        )
        {
            return null;
        }

        return
            semanticModel.GetDeclaredSymbol(
                parenthesized.ParameterList.Parameters[1],
                cancellationToken
            )
                is IParameterSymbol symbol
            ? symbol.Type.ToFullyQualifiedTypeName()
            : null;
    }

    /// <summary>
    /// Resolves receiver kind.
    /// </summary>
    private static ReceiverKind? ResolveReceiverKind(
        ITypeSymbol? receiverType,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        if (SymbolNameHelper.IsQueryable(receiverType))
        {
            return ReceiverKind.IQueryable;
        }

        if (SymbolNameHelper.IsEnumerable(receiverType))
        {
            return ReceiverKind.IEnumerable;
        }

        if (IsMappingDeclarationReceiver(receiverType, generatorOptions))
        {
            return ReceiverKind.IQueryable;
        }

        return null;
    }

    /// <summary>
    /// Resolves source type.
    /// </summary>
    private static ITypeSymbol? ResolveSourceType(
        SemanticModel semanticModel,
        ITypeSymbol? receiverType,
        SeparatedSyntaxList<TypeSyntax> typeArguments,
        CancellationToken cancellationToken = default
    )
    {
        if (typeArguments.Count >= 2)
        {
            return semanticModel.GetTypeInfo(typeArguments[0], cancellationToken).Type;
        }

        if (receiverType is INamedTypeSymbol namedType)
        {
            if (namedType.TypeArguments.Length == 1)
            {
                return namedType.TypeArguments[0];
            }

            var interfaceType = namedType.AllInterfaces.FirstOrDefault(candidate =>
                candidate.TypeArguments.Length == 1
                && (
                    candidate.ConstructedFrom.ToDisplayString() == "System.Linq.IQueryable<T>"
                    || candidate.ConstructedFrom.ToDisplayString()
                        == "System.Collections.Generic.IEnumerable<T>"
                )
            );
            return interfaceType?.TypeArguments[0];
        }

        return null;
    }

    /// <summary>
    /// Creates capture local name.
    /// </summary>
    private static string CreateCaptureLocalName(string propertyName, int index)
    {
        var sanitized = SymbolNameHelper.SanitizeHintName(propertyName);
        if (string.IsNullOrWhiteSpace(sanitized))
        {
            sanitized = "value";
        }

        if (!char.IsLetter(sanitized[0]) && sanitized[0] != '_')
        {
            sanitized = "_" + sanitized;
        }

        return $"__linqraft_capture_{index}_{sanitized}";
    }

    /// <summary>
    /// Determines whether the expression is a capture expression.
    /// </summary>
    private static bool IsCaptureExpression(ExpressionSyntax expression)
    {
        return expression is AnonymousObjectCreationExpressionSyntax or LambdaExpressionSyntax;
    }

    /// <summary>
    /// Gets capture argument.
    /// </summary>
    private static ArgumentSyntax? GetCaptureArgument(
        InvocationExpressionSyntax invocation,
        SemanticModel semanticModel,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        var namedCapture = invocation.ArgumentList.Arguments.FirstOrDefault(argument =>
            argument.NameColon?.Name.Identifier.ValueText == "capture"
        );
        if (namedCapture is not null)
        {
            return namedCapture;
        }

        var captureIndex = GetPositionalCaptureArgumentIndex(
            invocation,
            semanticModel,
            generatorOptions,
            cancellationToken
        );
        if (
            captureIndex is not int index
            || index < 0
            || index >= invocation.ArgumentList.Arguments.Count
        )
        {
            return null;
        }

        var argument = invocation.ArgumentList.Arguments[index];
        return IsCaptureExpression(argument.Expression) ? argument : null;
    }

    /// <summary>
    /// Gets positional capture argument index.
    /// </summary>
    private static int? GetPositionalCaptureArgumentIndex(
        InvocationExpressionSyntax invocation,
        SemanticModel semanticModel,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        if (
            GetUseLinqraftProjectionOperationKind(
                invocation,
                semanticModel,
                generatorOptions,
                cancellationToken
            ) is
            { } useLinqraftOperationKind
        )
        {
            return useLinqraftOperationKind == ProjectionOperationKind.GroupBy ? 2 : 1;
        }

        return GetInvocationName(invocation.Expression) switch
        {
            var name when name == generatorOptions.ObjectGenerationMethodName => 1,
            var name when name == generatorOptions.SelectExprMethodName => 1,
            var name when name == generatorOptions.SelectManyExprMethodName => 1,
            var name when name == generatorOptions.GroupByExprMethodName => 2,
            _ => null,
        };
    }

    /// <summary>
    /// Gets capture member name.
    /// </summary>
    private static string GetCaptureMemberName(ExpressionSyntax expression)
    {
        return expression switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            MemberAccessExpressionSyntax memberAccess => memberAccess.Name.Identifier.ValueText,
            _ => NormalizeExpressionText(expression),
        };
    }

    /// <summary>
    /// Creates capture entry.
    /// </summary>
    private static ProjectionExpressionEmitter.CaptureEntry CreateCaptureEntry(
        string propertyName,
        ExpressionSyntax expression,
        int index,
        SemanticModel semanticModel,
        CancellationToken cancellationToken,
        string? valueAccessor = null
    )
    {
        var type = semanticModel.GetTypeInfo(expression, cancellationToken).Type;
        return new ProjectionExpressionEmitter.CaptureEntry
        {
            PropertyName = propertyName,
            LocalName = CreateCaptureLocalName(propertyName, index),
            TypeName = type?.ToFullyQualifiedTypeName() ?? "object",
            ExpressionText = NormalizeExpressionText(expression),
            RootSymbol = GetCaptureRootSymbol(expression, semanticModel, cancellationToken),
            ValueAccessor = valueAccessor,
        };
    }

    /// <summary>
    /// Normalizes expression text.
    /// </summary>
    private static string NormalizeExpressionText(ExpressionSyntax expression)
    {
        return expression.WithoutTrivia().ToString();
    }

    /// <summary>
    /// Gets capture root symbol.
    /// </summary>
    private static ISymbol? GetCaptureRootSymbol(
        ExpressionSyntax expression,
        SemanticModel semanticModel,
        CancellationToken cancellationToken
    )
    {
        var rootExpression = GetCaptureRootExpression(expression);
        return semanticModel.GetSymbolInfo(rootExpression, cancellationToken).Symbol;
    }

    /// <summary>
    /// Gets capture root expression.
    /// </summary>
    private static ExpressionSyntax GetCaptureRootExpression(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => GetCaptureRootExpression(
                memberAccess.Expression
            ),
            ConditionalAccessExpressionSyntax conditionalAccess => GetCaptureRootExpression(
                conditionalAccess.Expression
            ),
            ElementAccessExpressionSyntax elementAccess => GetCaptureRootExpression(
                elementAccess.Expression
            ),
            InvocationExpressionSyntax invocation
                when invocation.Expression is MemberAccessExpressionSyntax memberAccess =>
                GetCaptureRootExpression(memberAccess.Expression),
            InvocationExpressionSyntax invocation => invocation,
            _ => expression,
        };
    }

    /// <summary>
    /// Represents capture analysis.
    /// </summary>
    private sealed record CaptureAnalysisResult
    {
        public static CaptureAnalysisResult None { get; } =
            new()
            {
                TransportKind = CaptureTransportKind.AnonymousObject,
                TransportTypeName = null,
                Entries = Array.Empty<ProjectionExpressionEmitter.CaptureEntry>(),
            };

        public required CaptureTransportKind TransportKind { get; init; }

        public string? TransportTypeName { get; init; }

        public required ProjectionExpressionEmitter.CaptureEntry[] Entries { get; init; }
    }

    /// <summary>
    /// Resolves caller namespace.
    /// </summary>
    private static string ResolveCallerNamespace(
        SyntaxNode node,
        SemanticModel semanticModel,
        CancellationToken cancellationToken = default
    )
    {
        var symbol = semanticModel.GetEnclosingSymbol(node.SpanStart, cancellationToken);
        return SymbolNameHelper.GetNamespace(symbol?.ContainingNamespace);
    }

    /// <summary>
    /// Resolves named type.
    /// </summary>
    private static string? ResolveNamedType(
        TypeSyntax typeSyntax,
        SemanticModel semanticModel,
        string fallbackNamespace,
        CancellationToken cancellationToken = default
    )
    {
        var typeInfo = semanticModel.GetTypeInfo(typeSyntax, cancellationToken);
        var type = typeInfo.Type ?? typeInfo.ConvertedType;
        if (type is IErrorTypeSymbol)
        {
            type = null;
        }

        if (type is null)
        {
            type = semanticModel.GetSymbolInfo(typeSyntax, cancellationToken).Symbol switch
            {
                ITypeSymbol typeSymbol when typeSymbol is not IErrorTypeSymbol => typeSymbol,
                IAliasSymbol aliasSymbol
                    when aliasSymbol.Target is ITypeSymbol typeSymbol
                        && typeSymbol is not IErrorTypeSymbol => typeSymbol,
                _ => null,
            };
        }

        if (type is null && typeSyntax is IdentifierNameSyntax identifierName)
        {
            type = semanticModel
                .LookupNamespacesAndTypes(
                    identifierName.SpanStart,
                    name: identifierName.Identifier.ValueText
                )
                .OfType<ITypeSymbol>()
                .FirstOrDefault(candidate => candidate is not IErrorTypeSymbol);
        }

        if (type is not null)
        {
            return type.ToFullyQualifiedTypeName();
        }

        if (TryResolveSyntacticallyQualifiedTypeName(typeSyntax, out var qualifiedTypeName))
        {
            return qualifiedTypeName;
        }

        var name = GetUnqualifiedTypeName(typeSyntax);
        return string.IsNullOrWhiteSpace(fallbackNamespace)
            ? $"global::{name}"
            : $"global::{fallbackNamespace}.{name}";
    }

    /// <summary>
    /// Attempts to resolve syntactically qualified type name.
    /// </summary>
    private static bool TryResolveSyntacticallyQualifiedTypeName(
        TypeSyntax typeSyntax,
        out string qualifiedTypeName
    )
    {
        qualifiedTypeName = typeSyntax.WithoutTrivia().ToString();
        if (string.IsNullOrWhiteSpace(qualifiedTypeName))
        {
            return false;
        }

        if (qualifiedTypeName.StartsWith("global::", StringComparison.Ordinal))
        {
            return true;
        }

        if (typeSyntax is QualifiedNameSyntax or AliasQualifiedNameSyntax)
        {
            qualifiedTypeName = $"global::{qualifiedTypeName}";
            return true;
        }

        qualifiedTypeName = string.Empty;
        return false;
    }

    /// <summary>
    /// Gets mapping generated accessibility keyword.
    /// </summary>
    private static string GetMappingGeneratedAccessibilityKeyword(
        Accessibility declaredAccessibility,
        InvocationExpressionSyntax selectExpr,
        SemanticModel semanticModel,
        string? requestedVisibilityKeyword,
        CancellationToken cancellationToken = default
    )
    {
        var nameSyntax = GetInvocationNameSyntax(selectExpr.Expression) as GenericNameSyntax;
        var resultTypeSyntax = nameSyntax?.TypeArgumentList.Arguments.LastOrDefault();
        if (resultTypeSyntax is not null)
        {
            var resultType = semanticModel.GetTypeInfo(resultTypeSyntax, cancellationToken).Type;
            if (nameSyntax!.TypeArgumentList.Arguments.Count >= 2)
            {
                var sourceType = semanticModel
                    .GetTypeInfo(nameSyntax.TypeArgumentList.Arguments[0], cancellationToken)
                    .Type;
                if (!IsPubliclyAccessible(sourceType) || !IsPubliclyAccessible(resultType))
                {
                    return "internal";
                }
            }
            else if (!IsPubliclyAccessible(resultType))
            {
                return "internal";
            }
        }

        return requestedVisibilityKeyword
            ?? SymbolNameHelper.GetAccessibilityKeyword(declaredAccessibility);
    }

    /// <summary>
    /// Determines whether the type symbol is a publicly accessible.
    /// </summary>
    private static bool IsPubliclyAccessible(ITypeSymbol? typeSymbol)
    {
        if (typeSymbol is null)
        {
            return false;
        }

        return typeSymbol switch
        {
            IArrayTypeSymbol arrayType => IsPubliclyAccessible(arrayType.ElementType),
            IDynamicTypeSymbol => true,
            ITypeParameterSymbol => true,
            INamedTypeSymbol namedType => namedType.DeclaredAccessibility == Accessibility.Public
                && (
                    namedType.ContainingType is null
                    || IsPubliclyAccessible(namedType.ContainingType)
                )
                && namedType.TypeArguments.All(IsPubliclyAccessible),
            _ => typeSymbol.DeclaredAccessibility == Accessibility.Public,
        };
    }

    /// <summary>
    /// Gets projection operation kind.
    /// </summary>
    private static ProjectionOperationKind? GetProjectionOperationKind(
        InvocationExpressionSyntax invocation,
        SemanticModel semanticModel,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        if (
            GetUseLinqraftProjectionOperationKind(
                invocation,
                semanticModel,
                generatorOptions,
                cancellationToken
            ) is
            { } useLinqraftOperationKind
        )
        {
            return useLinqraftOperationKind;
        }

        if (
            GetMappingProjectionOperationKind(
                invocation,
                semanticModel,
                generatorOptions,
                cancellationToken
            ) is
            { } mappingOperationKind
        )
        {
            return mappingOperationKind;
        }

        return GetInvocationName(invocation.Expression) switch
        {
            var name when name == generatorOptions.SelectExprMethodName =>
                ProjectionOperationKind.Select,
            var name when name == generatorOptions.SelectManyExprMethodName =>
                ProjectionOperationKind.SelectMany,
            var name when name == generatorOptions.GroupByExprMethodName =>
                ProjectionOperationKind.GroupBy,
            _ => null,
        };
    }

    /// <summary>
    /// Determines whether the invocation is a generate invocation.
    /// </summary>
    private static bool IsGenerateInvocation(
        InvocationExpressionSyntax invocation,
        SemanticModel semanticModel,
        CancellationToken cancellationToken,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        if (generatorOptions.GeneratorKitMetadataName is not { } generatorKitMetadataName)
        {
            return false;
        }

        if (
            !string.Equals(
                GetInvocationName(invocation.Expression),
                generatorOptions.ObjectGenerationMethodName,
                StringComparison.Ordinal
            )
        )
        {
            return false;
        }

        var methodSymbol =
            semanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol as IMethodSymbol;
        if (methodSymbol is null)
        {
            return false;
        }

        var targetMethod = methodSymbol.ReducedFrom ?? methodSymbol;
        return string.Equals(
                targetMethod.ContainingType.ToDisplayString(),
                generatorKitMetadataName,
                StringComparison.Ordinal
            )
            && string.Equals(
                targetMethod.Name,
                generatorOptions.ObjectGenerationMethodName,
                StringComparison.Ordinal
            );
    }

    /// <summary>
    /// Determines whether the invocation is a select expr invocation.
    /// </summary>
    private static bool IsSelectExprInvocation(
        InvocationExpressionSyntax invocation,
        SemanticModel semanticModel,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        return string.Equals(
                GetInvocationName(invocation.Expression),
                generatorOptions.SelectExprMethodName,
                StringComparison.Ordinal
            )
            || IsUseLinqraftSelectInvocation(
                invocation,
                semanticModel,
                generatorOptions,
                cancellationToken
            );
    }

    /// <summary>
    /// Determines whether the invocation is an use linqraft select invocation.
    /// </summary>
    private static bool IsUseLinqraftSelectInvocation(
        InvocationExpressionSyntax invocation,
        SemanticModel semanticModel,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        return GetUseLinqraftProjectionOperationKind(
                invocation,
                semanticModel,
                generatorOptions,
                cancellationToken
            ) == ProjectionOperationKind.Select;
    }

    /// <summary>
    /// Gets use linqraft projection operation kind.
    /// </summary>
    private static ProjectionOperationKind? GetUseLinqraftProjectionOperationKind(
        InvocationExpressionSyntax invocation,
        SemanticModel semanticModel,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        if (
            invocation.Expression
                is not MemberAccessExpressionSyntax
                {
                    Expression: InvocationExpressionSyntax receiverInvocation
                }
            || !IsUseLinqraftInvocation(
                receiverInvocation,
                semanticModel,
                generatorOptions,
                cancellationToken
            )
        )
        {
            return null;
        }

        return GetInvocationName(invocation.Expression) switch
        {
            "Select" => ProjectionOperationKind.Select,
            "SelectMany" => ProjectionOperationKind.SelectMany,
            "GroupBy" => ProjectionOperationKind.GroupBy,
            _ => null,
        };
    }

    /// <summary>
    /// Gets mapping declaration projection operation kind.
    /// </summary>
    private static ProjectionOperationKind? GetMappingProjectionOperationKind(
        InvocationExpressionSyntax invocation,
        SemanticModel semanticModel,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        var methodSymbol =
            semanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol as IMethodSymbol;
        var targetMethod = methodSymbol?.ReducedFrom ?? methodSymbol;
        if (
            targetMethod is null
            || !IsMappingDeclarationReceiver(targetMethod.ContainingType, generatorOptions)
        )
        {
            return null;
        }

        return targetMethod.Name switch
        {
            "Select" => ProjectionOperationKind.Select,
            "SelectMany" => ProjectionOperationKind.SelectMany,
            "GroupBy" => ProjectionOperationKind.GroupBy,
            _ => null,
        };
    }

    /// <summary>
    /// Determines whether the invocation is an use linqraft invocation.
    /// </summary>
    private static bool IsUseLinqraftInvocation(
        InvocationExpressionSyntax invocation,
        SemanticModel semanticModel,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        if (
            !string.Equals(
                GetInvocationName(invocation.Expression),
                "UseLinqraft",
                StringComparison.Ordinal
            )
        )
        {
            return false;
        }

        var methodSymbol =
            semanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol as IMethodSymbol;
        if (methodSymbol is null)
        {
            return false;
        }

        var targetMethod = methodSymbol.ReducedFrom ?? methodSymbol;
        return string.Equals(
                targetMethod.ContainingType.ToDisplayString(),
                $"{generatorOptions.SupportNamespace}.LinqraftQueryExtensions",
                StringComparison.Ordinal
            ) && string.Equals(targetMethod.Name, "UseLinqraft", StringComparison.Ordinal);
    }

    /// <summary>
    /// Determines whether the node is an inside mapping declaration.
    /// </summary>
    private static bool IsInsideMappingDeclaration(
        SyntaxNode node,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        if (generatorOptions.MappingGenerateAttributeName is not { } mappingGenerateAttributeName)
        {
            return false;
        }

        return node.Ancestors()
            .OfType<MemberDeclarationSyntax>()
            .Any(member =>
                member
                    .AttributeLists.SelectMany(list => list.Attributes)
                    .Any(attribute =>
                        attribute
                            .Name.ToString()
                            .Contains(
                                mappingGenerateAttributeName.Replace("Attribute", string.Empty),
                                StringComparison.Ordinal
                            )
                    )
            );
    }

    /// <summary>
    /// Gets receiver expression.
    /// </summary>
    private static ExpressionSyntax? GetReceiverExpression(
        InvocationExpressionSyntax invocation,
        SemanticModel semanticModel,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        return invocation.Expression switch
        {
            MemberAccessExpressionSyntax
            {
                Expression: InvocationExpressionSyntax receiverInvocation
            }
                when receiverInvocation.Expression is MemberAccessExpressionSyntax memberAccess
                    && IsUseLinqraftInvocation(
                        receiverInvocation,
                        semanticModel,
                        generatorOptions,
                        cancellationToken
                    ) => memberAccess.Expression,
            MemberAccessExpressionSyntax memberAccess => memberAccess.Expression,
            MemberBindingExpressionSyntax => null,
            _ => null,
        };
    }

    /// <summary>
    /// Gets invocation name.
    /// </summary>
    private static string GetInvocationName(ExpressionSyntax expression)
    {
        return GetInvocationNameSyntax(expression)?.Identifier.ValueText ?? string.Empty;
    }

    /// <summary>
    /// Gets invocation name syntax.
    /// </summary>
    private static SimpleNameSyntax? GetInvocationNameSyntax(ExpressionSyntax expression)
    {
        return expression switch
        {
            MemberAccessExpressionSyntax memberAccess => memberAccess.Name,
            MemberBindingExpressionSyntax memberBinding => memberBinding.Name,
            IdentifierNameSyntax identifier => identifier,
            GenericNameSyntax genericName => genericName,
            _ => null,
        };
    }

    /// <summary>
    /// Gets anonymous member name.
    /// </summary>
    private static string GetAnonymousMemberName(AnonymousObjectMemberDeclaratorSyntax initializer)
    {
        return initializer.NameEquals?.Name.Identifier.ValueText
            ?? AnonymousMemberNameResolver.Get(initializer.Expression);
    }

    /// <summary>
    /// Determines whether the symbol is a mapping declaration receiver.
    /// </summary>
    private static bool IsMappingDeclarationReceiver(
        ITypeSymbol? receiverType,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        if (generatorOptions.MappingDeclareClassName is not { } mappingDeclareClassName)
        {
            return false;
        }

        return receiverType is INamedTypeSymbol namedType
            && namedType.Arity == 1
            && namedType.Name == mappingDeclareClassName
            && namedType.ContainingNamespace.ToDisplayString() == generatorOptions.SupportNamespace;
    }

    /// <summary>
    /// Gets mapping generate attribute.
    /// </summary>
    private static AttributeData? GetMappingGenerateAttribute(
        ImmutableArray<AttributeData> attributes,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        if (generatorOptions.MappingGenerateAttributeName is not { } mappingGenerateAttributeName)
        {
            return null;
        }

        return attributes.FirstOrDefault(attribute =>
            attribute.AttributeClass?.Name == mappingGenerateAttributeName
        );
    }

    /// <summary>
    /// Gets mapping visibility keyword.
    /// </summary>
    private static string? GetMappingVisibilityKeyword(
        AttributeData? attribute,
        CancellationToken cancellationToken = default
    )
    {
        if (attribute is null)
        {
            return null;
        }

        foreach (var namedArgument in attribute.NamedArguments)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (
                !string.Equals(namedArgument.Key, "Visibility", StringComparison.Ordinal)
                || namedArgument.Value.Value is null
            )
            {
                continue;
            }

            return Convert.ToInt32(namedArgument.Value.Value) switch
            {
                1 => "internal",
                2 => "public",
                _ => null,
            };
        }

        return null;
    }

    /// <summary>
    /// Gets containing types.
    /// </summary>
    private static ContainingTypeInfo[] GetContainingTypes(
        INamedTypeSymbol? symbol,
        CancellationToken cancellationToken = default
    )
    {
        if (symbol?.ContainingType is null)
        {
            return Array.Empty<ContainingTypeInfo>();
        }

        var stack = new Stack<ContainingTypeInfo>();
        var current = symbol.ContainingType;
        while (current is not null)
        {
            cancellationToken.ThrowIfCancellationRequested();
            stack.Push(
                new ContainingTypeInfo
                {
                    AccessibilityKeyword = SymbolNameHelper.GetAccessibilityKeyword(
                        current.DeclaredAccessibility
                    ),
                    DeclarationKeyword = current.IsRecord ? "record" : "class",
                    Name = current.Name,
                }
            );
            current = current.ContainingType;
        }

        return stack.ToArray();
    }

    /// <summary>
    /// Gets unqualified type name.
    /// </summary>
    private static string GetUnqualifiedTypeName(TypeSyntax typeSyntax)
    {
        return typeSyntax switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            QualifiedNameSyntax qualifiedName => qualifiedName.Right.Identifier.ValueText,
            GenericNameSyntax genericName => genericName.Identifier.ValueText,
            AliasQualifiedNameSyntax aliasQualified => aliasQualified.Name.Identifier.ValueText,
            _ => typeSyntax.ToString().Split('.')[^1],
        };
    }

    /// <summary>
    /// Represents collection projection.
    /// </summary>
    private readonly record struct CollectionProjectionInfo
    {
        public required InvocationExpressionSyntax Invocation { get; init; }

        public required ExpressionSyntax LambdaBody { get; init; }

        public required ITypeSymbol? ExpressionType { get; init; }

        public required string ProjectionMethodName { get; init; }

        public required bool IsNestedExplicitDto { get; init; }

        public required TypeSyntax? NestedResultTypeSyntax { get; init; }

        public required TypeSyntax? SourceTypeSyntax { get; init; }
    }

    /// <summary>
    /// Represents projection build.
    /// </summary>
    private readonly record struct ProjectionBuildResult
    {
        public required ProjectionTemplateModel Projection { get; init; }

        public required GeneratedDtoTemplateModel? DtoTemplate { get; init; }

        public required IReadOnlyDictionary<TextSpan, string> ReplacementTypes { get; init; }
    }
}
