using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Linqraft.Core.Configuration;
using Linqraft.Core.Formatting;
using Linqraft.Core.Generation;
using Linqraft.Core.Utilities;

namespace Linqraft.SourceGenerator;

/// <summary>
/// Assembles generated source files from finalized projection models.
/// </summary>
internal static partial class SourceWriters
{
    // These writers translate finalized generator models into concrete declarations.
    /// <summary>
    /// Writes dto declarations.
    /// </summary>
    private static void WriteDtoDeclarations(
        IndentedStringBuilder builder,
        IReadOnlyList<GeneratedDtoModel> dtos,
        LinqraftConfiguration configuration,
        CancellationToken cancellationToken = default
    )
    {
        foreach (var dto in dtos)
        {
            cancellationToken.ThrowIfCancellationRequested();
            builder.AppendLine();
            WriteDtoDeclaration(builder, dto, configuration, cancellationToken);
        }
    }

    /// <summary>
    /// Writes dto declaration.
    /// </summary>
    private static void WriteDtoDeclaration(
        IndentedStringBuilder builder,
        GeneratedDtoModel dto,
        LinqraftConfiguration configuration,
        CancellationToken cancellationToken = default
    )
    {
        WriteNamespaceAndContainingTypesStart(
            builder,
            dto.Namespace,
            dto.ContainingTypes,
            cancellationToken
        );

        if (dto.IsAutoGeneratedNested)
        {
            builder.AppendLine(
                CodeTemplateContents.EditorBrowsableNeverAttribute,
                cancellationToken
            );
            if (configuration.GeneratorOptions.AutoGeneratedDtoAttributeName is { } attributeName)
            {
                builder.AppendLine(
                    $"[global::{configuration.GeneratorOptions.SupportNamespace}.{attributeName}]",
                    cancellationToken
                );
            }
        }

        WriteDocumentation(
            builder,
            dto.Documentation,
            configuration.CommentOutput,
            cancellationToken
        );

        var declarationKeyword = dto.IsRecord ? "record" : "class";
        var suppressedProperties = dto.Properties.Where(property => property.IsSuppressed).ToList();
        builder.AppendLine(
            $"{dto.AccessibilityKeyword} partial {declarationKeyword} {dto.Name}",
            cancellationToken
        );
        builder.AppendLine("{", cancellationToken);
        using (builder.Indent())
        {
            if (suppressedProperties.Count != 0)
            {
                builder.AppendLine(
                    $"{dto.AccessibilityKeyword} {dto.Name}({string.Join(", ", suppressedProperties.Select(property => $"{property.TypeName} {ToParameterName(property.Name)}"))})",
                    cancellationToken
                );
                builder.AppendLine("{", cancellationToken);
                using (builder.Indent())
                {
                    foreach (
                        var propertyName in suppressedProperties.Select(property => property.Name)
                    )
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        builder.AppendLine(
                            $"{propertyName} = {ToParameterName(propertyName)};",
                            cancellationToken
                        );
                    }
                }

                builder.AppendLine("}", cancellationToken);
                builder.AppendLine();
            }

            foreach (var property in dto.Properties.Where(property => !property.IsSuppressed))
            {
                cancellationToken.ThrowIfCancellationRequested();
                WriteDocumentation(
                    builder,
                    property.Documentation,
                    configuration.CommentOutput,
                    cancellationToken
                );
                var required = configuration.HasRequired ? "required " : string.Empty;
                builder.AppendLine(
                    $"public {required}{property.TypeName} {property.Name} {{ {GetAccessor(configuration, dto.IsRecord)} }}",
                    cancellationToken
                );
            }
        }

        builder.AppendLine("}", cancellationToken);
        WriteNamespaceAndContainingTypesEnd(
            builder,
            dto.Namespace,
            dto.ContainingTypes,
            cancellationToken
        );
    }

    /// <summary>
    /// Writes interceptor declaration.
    /// </summary>
    private static void WriteInterceptorDeclaration(
        IndentedStringBuilder builder,
        ProjectionRequest request,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        builder.AppendLine($"namespace {generatorOptions.SupportNamespace}", cancellationToken);
        builder.AppendLine("{", cancellationToken);
        using (builder.Indent())
        {
            builder.AppendLine(
                $"file static partial class {GetProjectionInterceptorClassName(request.OperationKind, generatorOptions)}",
                cancellationToken
            );
            builder.AppendLine("{", cancellationToken);
            using (builder.Indent())
            {
                var lambda = ProjectionBodyEmitter.AppendValueInline(
                    $"{request.SelectorParameterName} => ",
                    request.ProjectionBodyText
                );

                var receiverType = GetReceiverTypeName(
                    request.ReceiverKind,
                    request.UsesFluentQuerySyntax,
                    generatorOptions
                );
                var selectorResultType = GetSelectorResultType(request);
                var captureParameter =
                    request.CaptureTransportKind == CaptureTransportKind.Delegate
                        ? "global::System.Func<object> capture"
                        : "object capture";
                var helperType = $"global::{generatorOptions.SupportNamespace}.IProjectionHelper";
                string selectorType;
                if (request.OperationKind == ProjectionOperationKind.GroupBy)
                {
                    selectorType = request.UsesProjectionHelperParameter
                        ? $"global::System.Func<global::System.Linq.IGrouping<TKey, TIn>, {helperType}, {selectorResultType}>"
                        : $"global::System.Func<global::System.Linq.IGrouping<TKey, TIn>, {selectorResultType}>";
                }
                else
                {
                    selectorType = request.UsesProjectionHelperParameter
                        ? $"global::System.Func<TIn, {helperType}, {selectorResultType}>"
                        : $"global::System.Func<TIn, {selectorResultType}>";
                }
                string signature;
                if (request.UsesFluentQuerySyntax)
                {
                    signature = GetFluentQuerySignature(
                        request,
                        receiverType,
                        selectorType,
                        captureParameter,
                        cancellationToken
                    );
                }
                else
                {
                    signature = CreateNonFluentSignature(
                        request,
                        receiverType,
                        selectorType,
                        captureParameter
                    );
                }
                if (
                    request.InterceptableLocationVersion is { } interceptableLocationVersion
                    && request.InterceptableLocationData is { } interceptableLocationData
                )
                {
                    builder.AppendLine(
                        $"[global::System.Runtime.CompilerServices.InterceptsLocationAttribute({interceptableLocationVersion}, \"{EscapeStringLiteral(interceptableLocationData)}\")]",
                        cancellationToken
                    );
                }
                if (
                    request.Captures.Length != 0
                    && request.CaptureTransportKind == CaptureTransportKind.AnonymousObject
                )
                {
                    builder.AppendLine(
                        "[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2075\", Justification = \"Capture reflection inspects runtime-generated anonymous objects.\")]",
                        cancellationToken
                    );
                }

                builder.AppendLine(signature, cancellationToken);
                builder.AppendLine("{", cancellationToken);
                using (builder.Indent())
                {
                    var matchedQueryType = request.UsesFluentQuerySyntax
                        ? $"{GetReceiverTypeName(request.ReceiverKind)}<{request.SourceTypeName}>"
                        : $"{receiverType}<{request.SourceTypeName}>";

                    if (request.Captures.Length != 0)
                    {
                        WriteCaptureExtraction(
                            builder,
                            request.Captures,
                            request.CaptureTransportKind,
                            request.CaptureTransportTypeName,
                            cancellationToken
                        );
                    }

                    var querySource = request.UsesFluentQuerySyntax
                        ? $"(({matchedQueryType})(object)query.GetSource())"
                        : $"(({matchedQueryType})(object)query)";
                    if (
                        request.InnerJoinFilterBodyText is { } innerJoinFilterBodyText
                        && request.OperationKind != ProjectionOperationKind.GroupBy
                    )
                    {
                        querySource =
                            $"{querySource}.Where({ProjectionBodyEmitter.AppendValueInline($"{request.SelectorParameterName} => ", innerJoinFilterBodyText)})";
                    }
                    var convertedInvocation = request.OperationKind switch
                    {
                        ProjectionOperationKind.Select => $"{querySource}.Select({lambda})",
                        ProjectionOperationKind.SelectMany => $"{querySource}.SelectMany({lambda})",
                        ProjectionOperationKind.GroupBy =>
                            $"{querySource}.GroupBy({ProjectionBodyEmitter.AppendValueInline($"{request.KeySelectorParameterName} => ", request.KeySelectorBodyText ?? "default!")}).Select({lambda})",
                        _ => throw new InvalidOperationException(
                            $"Unsupported projection operation '{request.OperationKind}'."
                        ),
                    };
                    AppendMultilineLine(
                        builder,
                        $"var converted = {convertedInvocation};",
                        cancellationToken
                    );
                    var returnStatement = request.UsesFluentQuerySyntax
                        ? $"return ({GetReceiverTypeName(request.ReceiverKind)}<TResult>)(object)converted;"
                        : $"return ({receiverType}<TResult>)(object)converted;";
                    builder.AppendLine(returnStatement, cancellationToken);
                }

                builder.AppendLine("}", cancellationToken);
            }

            builder.AppendLine("}", cancellationToken);
        }

        builder.AppendLine("}", cancellationToken);
    }

    /// <summary>
    /// Writes object generation declaration.
    /// </summary>
    private static void WriteObjectGenerationDeclaration(
        IndentedStringBuilder builder,
        ObjectGenerationRequest request,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        builder.AppendLine($"namespace {generatorOptions.SupportNamespace}", cancellationToken);
        builder.AppendLine("{", cancellationToken);
        using (builder.Indent())
        {
            builder.AppendLine(
                $"internal static partial class {generatorOptions.GeneratorKitClassName!}",
                cancellationToken
            );
            builder.AppendLine("{", cancellationToken);
            using (builder.Indent())
            {
                if (
                    request.InterceptableLocationVersion is { } interceptableLocationVersion
                    && request.InterceptableLocationData is { } interceptableLocationData
                )
                {
                    builder.AppendLine(
                        $"[global::System.Runtime.CompilerServices.InterceptsLocationAttribute({interceptableLocationVersion}, \"{EscapeStringLiteral(interceptableLocationData)}\")]",
                        cancellationToken
                    );
                }

                if (
                    request.Captures.Length != 0
                    && request.CaptureTransportKind == CaptureTransportKind.AnonymousObject
                )
                {
                    builder.AppendLine(
                        "[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2075\", Justification = \"Capture reflection inspects runtime-generated anonymous objects.\")]",
                        cancellationToken
                    );
                }

                string signature;
                if (request.Captures.Length == 0)
                {
                    signature = $"internal static T {request.MethodName}<T>(object x)";
                }
                else if (request.CaptureTransportKind == CaptureTransportKind.Delegate)
                {
                    signature =
                        $"internal static T {request.MethodName}<T>(object x, global::System.Func<object> capture)";
                }
                else
                {
                    signature =
                        $"internal static T {request.MethodName}<T>(object x, object capture)";
                }

                builder.AppendLine(signature, cancellationToken);
                builder.AppendLine("{", cancellationToken);
                using (builder.Indent())
                {
                    if (request.Captures.Length != 0)
                    {
                        WriteCaptureExtraction(
                            builder,
                            request.Captures,
                            request.CaptureTransportKind,
                            request.CaptureTransportTypeName,
                            cancellationToken
                        );
                    }

                    AppendMultilineLine(
                        builder,
                        $"return (T)(object){request.ProjectionBodyText};",
                        cancellationToken
                    );
                }

                builder.AppendLine("}", cancellationToken);
            }

            builder.AppendLine("}", cancellationToken);
        }

        builder.AppendLine("}", cancellationToken);
    }

    /// <summary>
    /// Writes mapping declaration.
    /// </summary>
    private static void WriteMappingDeclaration(
        IndentedStringBuilder builder,
        MappingRequest request,
        CancellationToken cancellationToken = default
    )
    {
        if (!string.IsNullOrWhiteSpace(request.Namespace))
        {
            builder.AppendLine($"namespace {request.Namespace}", cancellationToken);
            builder.AppendLine("{", cancellationToken);
            builder.IncreaseIndent();
        }

        builder.AppendLine(
            $"{request.AccessibilityKeyword} static partial class {request.ContainingTypeName}",
            cancellationToken
        );
        builder.AppendLine("{", cancellationToken);
        using (builder.Indent())
        {
            var lambda = ProjectionBodyEmitter.AppendValueInline(
                $"{request.SelectorParameterName} => ",
                request.ProjectionBodyText
            );
            var keyLambda =
                request.OperationKind == ProjectionOperationKind.GroupBy
                && request.KeySelectorParameterName is { } keySelectorParameterName
                && request.KeySelectorBodyText is { } keySelectorBodyText
                    ? ProjectionBodyEmitter.AppendValueInline(
                        $"{keySelectorParameterName} => ",
                        keySelectorBodyText
                    )
                    : null;
            foreach (
                var receiverType in new[]
                {
                    "global::System.Linq.IQueryable",
                    "global::System.Collections.Generic.IEnumerable",
                }
            )
            {
                builder.AppendLine(
                    $"{request.MethodAccessibilityKeyword} static {receiverType}<{request.ResultTypeName}> {request.MethodName}(this {receiverType}<{request.SourceTypeName}> source{string.Concat(request.Captures.Select(capture => $", {capture.TypeName} {capture.PropertyName}"))})",
                    cancellationToken
                );
                builder.AppendLine("{", cancellationToken);
                using (builder.Indent())
                {
                    foreach (
                        var capture in request.Captures.Where(capture =>
                            capture.LocalName != capture.PropertyName
                        )
                    )
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        builder.AppendLine(
                            $"var {capture.LocalName} = {capture.PropertyName};",
                            cancellationToken
                        );
                    }

                    var canApplyInnerJoinFilter =
                        request.OperationKind != ProjectionOperationKind.GroupBy;
                    var querySource =
                        request.InnerJoinFilterBodyText is { } innerJoinFilterBodyText
                        && canApplyInnerJoinFilter
                            ? $"source.Where({ProjectionBodyEmitter.AppendValueInline($"{request.SelectorParameterName} => ", innerJoinFilterBodyText)})"
                            : "source";
                    var projectionInvocation = request.OperationKind switch
                    {
                        ProjectionOperationKind.Select => $"{querySource}.Select({lambda})",
                        ProjectionOperationKind.SelectMany =>
                            $"{querySource}.SelectMany({lambda})",
                        ProjectionOperationKind.GroupBy when keyLambda is not null =>
                            $"{querySource}.GroupBy({keyLambda}).Select({lambda})",
                        _ => throw new InvalidOperationException(
                            $"Unsupported mapping operation '{request.OperationKind}'."
                        ),
                    };
                    AppendMultilineLine(
                        builder,
                        $"return {projectionInvocation};",
                        cancellationToken
                    );
                }

                builder.AppendLine("}", cancellationToken);
            }
        }

        builder.AppendLine("}", cancellationToken);

        if (!string.IsNullOrWhiteSpace(request.Namespace))
        {
            builder.DecreaseIndent();
            builder.AppendLine("}", cancellationToken);
        }
    }
}
