using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Linqraft.Core.Configuration;
using Linqraft.Core.Formatting;
using Linqraft.Core.Generation;
using Linqraft.Core.Utilities;

namespace Linqraft.SourceGenerator;

/// <summary>
/// Assembles generated source files from finalized projection models.
/// </summary>
internal static partial class SourceWriters
{
    // Public entry points assemble complete generated files; declaration details live in sibling partial files.

    /// <summary>
    /// Writes a generated source file for a projection request.
    /// </summary>
    public static string WriteProjectionUnit(
        ProjectionRequest request,
        LinqraftConfiguration configuration
    )
    {
        var builder = CreateFileBuilder(configuration);
        WriteInterceptorDeclaration(builder, request, configuration.GeneratorOptions);
        return FinalizeSource(builder);
    }

    /// <summary>
    /// Writes a generated source file for a mapping request.
    /// </summary>
    public static string WriteMappingUnit(
        MappingRequest request,
        LinqraftConfiguration configuration
    )
    {
        var builder = CreateFileBuilder(configuration);
        WriteMappingDeclaration(builder, request);
        return FinalizeSource(builder);
    }

    /// <summary>
    /// Writes a generated source file for an owned projection, mapping, or object-generation artifact.
    /// </summary>
    public static string WriteOwnedUnit(
        OwnedGeneratedSourceModel source,
        IReadOnlyList<GeneratedDtoModel> dtos,
        LinqraftConfiguration configuration,
        CancellationToken cancellationToken = default
    )
    {
        var builder = CreateFileBuilder(configuration, cancellationToken);
        switch (source)
        {
            case ProjectionOwnedGeneratedSourceModel projection:
                WriteInterceptorDeclaration(
                    builder,
                    projection.Request,
                    configuration.GeneratorOptions,
                    cancellationToken
                );
                break;
            case ObjectGenerationOwnedGeneratedSourceModel generation:
                WriteObjectGenerationDeclaration(
                    builder,
                    generation.Request,
                    configuration.GeneratorOptions,
                    cancellationToken
                );
                break;
            case MappingOwnedGeneratedSourceModel mapping:
                WriteMappingDeclaration(builder, mapping.Request, cancellationToken);
                break;
            default:
                throw new InvalidOperationException(
                    $"Unsupported generated source type '{source.GetType().Name}'."
                );
        }

        WriteDtoDeclarations(builder, dtos, configuration, cancellationToken);
        return FinalizeSource(builder, cancellationToken);
    }

    /// <summary>
    /// Writes a generated source file for a standalone DTO declaration.
    /// </summary>
    public static string WriteDtoUnit(
        GeneratedDtoModel dto,
        LinqraftConfiguration configuration,
        CancellationToken cancellationToken = default
    )
    {
        var builder = CreateFileBuilder(configuration, cancellationToken);
        WriteDtoDeclaration(builder, dto, configuration, cancellationToken);
        return FinalizeSource(builder, cancellationToken);
    }

    /// <summary>
    /// Writes the generated global-using source file.
    /// </summary>
    public static string WriteGlobalUsingsUnit(
        LinqraftConfiguration configuration,
        CancellationToken cancellationToken = default
    )
    {
        var builder = new IndentedStringBuilder();
        builder.AppendLines(
            $$"""
            {{CodeTemplateContents.CreateAutoGeneratedHeader(
                configuration.GeneratorOptions.GeneratedHeaderComment
            )}}
            #nullable enable
            #pragma warning disable CS1591
            #pragma warning disable CS8933
            global using {{configuration.GeneratorOptions.GlobalUsingNamespace}};
            """,
            cancellationToken
        );
        return FinalizeSource(builder, cancellationToken);
    }

    /// <summary>
    /// Creates file builder.
    /// </summary>
    private static IndentedStringBuilder CreateFileBuilder(
        LinqraftConfiguration configuration,
        CancellationToken cancellationToken = default
    )
    {
        var builder = new IndentedStringBuilder();
        builder.AppendLines(
            $$"""
            {{CodeTemplateContents.CreateAutoGeneratedHeader(
                configuration.GeneratorOptions.GeneratedHeaderComment
            )}}
            #nullable enable
            #pragma warning disable CS1591
            #pragma warning disable CS8600
            #pragma warning disable CS8601
            #pragma warning disable CS8602
            #pragma warning disable CS8603
            #pragma warning disable CS8604
            #pragma warning disable CS8618
            using System.Linq;
            """,
            cancellationToken
        );
        return builder;
    }

    /// <summary>
    /// Finalizes source.
    /// </summary>
    private static string FinalizeSource(
        IndentedStringBuilder builder,
        CancellationToken cancellationToken = default
    )
    {
        return GeneratedSourceFormatter.FormatGeneratedSource(
            builder.ToString(),
            cancellationToken
        );
    }

    /// <summary>
    /// Gets selector result type.
    /// </summary>
    private static string GetSelectorResultType(ProjectionRequest request)
    {
        if (request.UseObjectSelectorSignature)
        {
            return "object";
        }

        return request.OperationKind == ProjectionOperationKind.SelectMany
            ? "global::System.Collections.Generic.IEnumerable<TResult>"
            : "TResult";
    }

    /// <summary>
    /// Gets projection support class name.
    /// </summary>
    private static string GetProjectionSupportClassName(
        ProjectionOperationKind operationKind,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        return operationKind switch
        {
            ProjectionOperationKind.Select => generatorOptions.SelectExprClassName,
            ProjectionOperationKind.SelectMany => generatorOptions.SelectManyExprClassName,
            ProjectionOperationKind.GroupBy => generatorOptions.GroupByExprClassName,
            _ => throw new InvalidOperationException(
                $"Unsupported projection operation '{operationKind}'."
            ),
        };
    }

    /// <summary>
    /// Gets projection interceptor class name.
    /// </summary>
    private static string GetProjectionInterceptorClassName(
        ProjectionOperationKind operationKind,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        var className = GetProjectionSupportClassName(operationKind, generatorOptions);
        return className.EndsWith("Extensions", StringComparison.Ordinal)
            ? $"{className[..^"Extensions".Length]}InterceptExtensions"
            : $"{className}Interceptors";
    }

    /// <summary>
    /// Gets receiver type name.
    /// </summary>
    private static string GetReceiverTypeName(ReceiverKind receiverKind)
    {
        return receiverKind == ReceiverKind.IQueryable
            ? "global::System.Linq.IQueryable"
            : "global::System.Collections.Generic.IEnumerable";
    }

    /// <summary>
    /// Gets receiver type name.
    /// </summary>
    private static string GetReceiverTypeName(
        ReceiverKind receiverKind,
        bool usesFluentQuerySyntax,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        if (usesFluentQuerySyntax)
        {
            return receiverKind == ReceiverKind.IQueryable
                ? $"global::{generatorOptions.SupportNamespace}.LinqraftQuery"
                : $"global::{generatorOptions.SupportNamespace}.LinqraftEnumerable";
        }

        return receiverKind == ReceiverKind.IQueryable
            ? "global::System.Linq.IQueryable"
            : "global::System.Collections.Generic.IEnumerable";
    }

    /// <summary>
    /// Gets fluent query signature.
    /// </summary>
    private static string GetFluentQuerySignature(
        ProjectionRequest request,
        string receiverType,
        string selectorType,
        string captureParameter,
        CancellationToken cancellationToken = default
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        var fluentReturnType = GetReceiverTypeName(request.ReceiverKind);
        return request.OperationKind switch
        {
            ProjectionOperationKind.Select => request.Captures.Length == 0
                ? $"public static {fluentReturnType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, {selectorType} selector) where TIn : class"
                : $"public static {fluentReturnType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, {selectorType} selector, {captureParameter}) where TIn : class",
            ProjectionOperationKind.SelectMany => request.Captures.Length == 0
                ? $"public static {fluentReturnType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, {selectorType} selector) where TIn : class"
                : $"public static {fluentReturnType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, {selectorType} selector, {captureParameter}) where TIn : class",
            ProjectionOperationKind.GroupBy => request.Captures.Length == 0
                ? $"public static {fluentReturnType}<TResult> {request.MethodName}<TIn, TKey, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, TKey> keySelector, {selectorType} selector) where TIn : class"
                : $"public static {fluentReturnType}<TResult> {request.MethodName}<TIn, TKey, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, TKey> keySelector, {selectorType} selector, {captureParameter}) where TIn : class",
            _ => throw new InvalidOperationException(
                $"Fluent query syntax is not supported for projection operation '{request.OperationKind}'."
            ),
        };
    }

    /// <summary>
    /// Creates non fluent signature.
    /// </summary>
    private static string CreateNonFluentSignature(
        ProjectionRequest request,
        string receiverType,
        string selectorType,
        string captureParameter
    )
    {
        var signatureSuffix = request.Captures.Length == 0 ? string.Empty : $", {captureParameter}";
        return request.OperationKind switch
        {
            ProjectionOperationKind.Select =>
                $"public static {receiverType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, {selectorType} selector{signatureSuffix}) where TIn : class",
            ProjectionOperationKind.SelectMany =>
                $"public static {receiverType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, {selectorType} selector{signatureSuffix}) where TIn : class",
            ProjectionOperationKind.GroupBy =>
                $"public static {receiverType}<TResult> {request.MethodName}<TIn, TKey, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, TKey> keySelector, {selectorType} selector{signatureSuffix}) where TIn : class",
            _ => throw new InvalidOperationException(
                $"Unsupported projection operation '{request.OperationKind}'."
            ),
        };
    }
}
