using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Linqraft.Core.Configuration;
using Linqraft.Core.Formatting;
using Linqraft.Core.Generation;
using Linqraft.Core.Utilities;

namespace Linqraft.SourceGenerator;

internal static class SourceWriters
{
    public static string WriteProjectionUnit(
        ProjectionRequest request,
        LinqraftConfiguration configuration
    )
    {
        var builder = CreateFileBuilder(configuration);
        WriteInterceptorDeclaration(builder, request, configuration.GeneratorOptions);
        return FinalizeSource(builder);
    }

    public static string WriteMappingUnit(
        MappingRequest request,
        LinqraftConfiguration configuration
    )
    {
        var builder = CreateFileBuilder(configuration);
        WriteMappingDeclaration(builder, request);
        return FinalizeSource(builder);
    }

    public static string WriteOwnedUnit(
        OwnedGeneratedSourceModel source,
        IReadOnlyList<GeneratedDtoModel> dtos,
        LinqraftConfiguration configuration,
        CancellationToken cancellationToken = default
    )
    {
        var builder = CreateFileBuilder(configuration, cancellationToken);
        switch (source)
        {
            case ProjectionOwnedGeneratedSourceModel projection:
                WriteInterceptorDeclaration(
                    builder,
                    projection.Request,
                    configuration.GeneratorOptions,
                    cancellationToken
                );
                break;
            case ObjectGenerationOwnedGeneratedSourceModel generation:
                WriteObjectGenerationDeclaration(
                    builder,
                    generation.Request,
                    configuration.GeneratorOptions,
                    cancellationToken
                );
                break;
            case MappingOwnedGeneratedSourceModel mapping:
                WriteMappingDeclaration(builder, mapping.Request, cancellationToken);
                break;
            default:
                throw new InvalidOperationException(
                    $"Unsupported generated source type '{source.GetType().Name}'."
                );
        }

        WriteDtoDeclarations(builder, dtos, configuration, cancellationToken);
        return FinalizeSource(builder, cancellationToken);
    }

    public static string WriteDtoUnit(
        GeneratedDtoModel dto,
        LinqraftConfiguration configuration,
        CancellationToken cancellationToken = default
    )
    {
        var builder = CreateFileBuilder(configuration, cancellationToken);
        WriteDtoDeclaration(builder, dto, configuration, cancellationToken);
        return FinalizeSource(builder, cancellationToken);
    }

    public static string WriteGlobalUsingsUnit(
        LinqraftConfiguration configuration,
        CancellationToken cancellationToken = default
    )
    {
        var builder = new IndentedStringBuilder();
        builder.AppendLines(
            $$"""
            {{CodeTemplateContents.CreateAutoGeneratedHeader(
                configuration.GeneratorOptions.GeneratedHeaderComment
            )}}
            #nullable enable
            #pragma warning disable CS1591
            #pragma warning disable CS8933
            global using {{configuration.GeneratorOptions.GlobalUsingNamespace}};
            """,
            cancellationToken
        );
        return FinalizeSource(builder, cancellationToken);
    }

    private static void WriteDtoDeclarations(
        IndentedStringBuilder builder,
        IReadOnlyList<GeneratedDtoModel> dtos,
        LinqraftConfiguration configuration,
        CancellationToken cancellationToken = default
    )
    {
        foreach (var dto in dtos)
        {
            cancellationToken.ThrowIfCancellationRequested();
            builder.AppendLine();
            WriteDtoDeclaration(builder, dto, configuration, cancellationToken);
        }
    }

    private static void WriteDtoDeclaration(
        IndentedStringBuilder builder,
        GeneratedDtoModel dto,
        LinqraftConfiguration configuration,
        CancellationToken cancellationToken = default
    )
    {
        WriteNamespaceAndContainingTypesStart(
            builder,
            dto.Namespace,
            dto.ContainingTypes,
            cancellationToken
        );

        if (dto.IsAutoGeneratedNested)
        {
            builder.AppendLine(
                CodeTemplateContents.EditorBrowsableNeverAttribute,
                cancellationToken
            );
            if (configuration.GeneratorOptions.AutoGeneratedDtoAttributeName is { } attributeName)
            {
                builder.AppendLine(
                    $"[global::{configuration.GeneratorOptions.SupportNamespace}.{attributeName}]",
                    cancellationToken
                );
            }
        }

        WriteDocumentation(
            builder,
            dto.Documentation,
            configuration.CommentOutput,
            cancellationToken
        );

        var declarationKeyword = dto.IsRecord ? "record" : "class";
        var suppressedProperties = dto.Properties.Where(property => property.IsSuppressed).ToList();
        builder.AppendLine(
            $"{dto.AccessibilityKeyword} partial {declarationKeyword} {dto.Name}",
            cancellationToken
        );
        builder.AppendLine("{", cancellationToken);
        using (builder.Indent())
        {
            if (suppressedProperties.Count != 0)
            {
                builder.AppendLine(
                    $"{dto.AccessibilityKeyword} {dto.Name}({string.Join(", ", suppressedProperties.Select(property => $"{property.TypeName} {ToParameterName(property.Name)}"))})",
                    cancellationToken
                );
                builder.AppendLine("{", cancellationToken);
                using (builder.Indent())
                {
                    foreach (
                        var propertyName in suppressedProperties.Select(property => property.Name)
                    )
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        builder.AppendLine(
                            $"{propertyName} = {ToParameterName(propertyName)};",
                            cancellationToken
                        );
                    }
                }

                builder.AppendLine("}", cancellationToken);
                builder.AppendLine();
            }

            foreach (var property in dto.Properties.Where(property => !property.IsSuppressed))
            {
                cancellationToken.ThrowIfCancellationRequested();
                WriteDocumentation(
                    builder,
                    property.Documentation,
                    configuration.CommentOutput,
                    cancellationToken
                );
                var required = configuration.HasRequired ? "required " : string.Empty;
                builder.AppendLine(
                    $"public {required}{property.TypeName} {property.Name} {{ {GetAccessor(configuration, dto.IsRecord)} }}",
                    cancellationToken
                );
            }
        }

        builder.AppendLine("}", cancellationToken);
        WriteNamespaceAndContainingTypesEnd(
            builder,
            dto.Namespace,
            dto.ContainingTypes,
            cancellationToken
        );
    }

    private static void WriteInterceptorDeclaration(
        IndentedStringBuilder builder,
        ProjectionRequest request,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        builder.AppendLine($"namespace {generatorOptions.SupportNamespace}", cancellationToken);
        builder.AppendLine("{", cancellationToken);
        using (builder.Indent())
        {
            builder.AppendLine(
                $"file static partial class {GetProjectionInterceptorClassName(request.OperationKind, generatorOptions)}",
                cancellationToken
            );
            builder.AppendLine("{", cancellationToken);
            using (builder.Indent())
            {
                var expressionFieldName = $"s_expression_{request.MethodName}";
                var lambda = ProjectionBodyEmitter.AppendValueInline(
                    $"{request.SelectorParameterName} => ",
                    request.ProjectionBodyText
                );
                if (
                    request.CanUsePrebuiltExpression
                    && request.OperationKind == ProjectionOperationKind.Select
                    && request.ReceiverKind == ReceiverKind.IQueryable
                )
                {
                    AppendMultilineLine(
                        builder,
                        $"private static readonly global::System.Linq.Expressions.Expression<global::System.Func<{request.SourceTypeName}, {request.ResultTypeName}>> {expressionFieldName} = {lambda};",
                        cancellationToken
                    );
                    builder.AppendLine();
                }

                var receiverType = GetReceiverTypeName(
                    request.ReceiverKind,
                    request.UsesFluentQuerySyntax,
                    generatorOptions
                );
                var selectorResultType = GetSelectorResultType(request);
                var captureParameter =
                    request.CaptureTransportKind == CaptureTransportKind.Delegate
                        ? "global::System.Func<object> capture"
                        : "object capture";
                var helperType = $"global::{generatorOptions.SupportNamespace}.IProjectionHelper";
                string selectorType;
                if (request.OperationKind == ProjectionOperationKind.GroupBy)
                {
                    selectorType = request.UsesProjectionHelperParameter
                        ? $"global::System.Func<global::System.Linq.IGrouping<TKey, TIn>, {helperType}, {selectorResultType}>"
                        : $"global::System.Func<global::System.Linq.IGrouping<TKey, TIn>, {selectorResultType}>";
                }
                else
                {
                    selectorType = request.UsesProjectionHelperParameter
                        ? $"global::System.Func<TIn, {helperType}, {selectorResultType}>"
                        : $"global::System.Func<TIn, {selectorResultType}>";
                }
                string signature;
                if (request.UsesFluentQuerySyntax)
                {
                    signature = GetFluentQuerySignature(
                        request,
                        receiverType,
                        selectorType,
                        captureParameter,
                        cancellationToken
                    );
                }
                else
                {
                    signature = CreateNonFluentSignature(
                        request,
                        receiverType,
                        selectorType,
                        captureParameter
                    );
                }
                if (
                    request.InterceptableLocationVersion is { } interceptableLocationVersion
                    && request.InterceptableLocationData is { } interceptableLocationData
                )
                {
                    builder.AppendLine(
                        $"[global::System.Runtime.CompilerServices.InterceptsLocationAttribute({interceptableLocationVersion}, \"{EscapeStringLiteral(interceptableLocationData)}\")]",
                        cancellationToken
                    );
                }
                if (
                    request.Captures.Length != 0
                    && request.CaptureTransportKind == CaptureTransportKind.AnonymousObject
                )
                {
                    builder.AppendLine(
                        "[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2075\", Justification = \"Capture reflection inspects runtime-generated anonymous objects.\")]",
                        cancellationToken
                    );
                }

                builder.AppendLine(signature, cancellationToken);
                builder.AppendLine("{", cancellationToken);
                using (builder.Indent())
                {
                    var matchedQueryType = request.UsesFluentQuerySyntax
                        ? $"{GetReceiverTypeName(request.ReceiverKind)}<{request.SourceTypeName}>"
                        : $"{receiverType}<{request.SourceTypeName}>";

                    if (request.Captures.Length != 0)
                    {
                        WriteCaptureExtraction(
                            builder,
                            request.Captures,
                            request.CaptureTransportKind,
                            request.CaptureTransportTypeName,
                            cancellationToken
                        );
                    }

                    var selectArgument =
                        request.CanUsePrebuiltExpression
                        && request.OperationKind == ProjectionOperationKind.Select
                        && request.ReceiverKind == ReceiverKind.IQueryable
                            ? expressionFieldName
                            : lambda;
                    var querySource = request.UsesFluentQuerySyntax
                        ? $"(({matchedQueryType})(object)query.GetSource())"
                        : $"(({matchedQueryType})(object)query)";
                    if (
                        request.InnerJoinFilterBodyText is { } innerJoinFilterBodyText
                        && request.OperationKind != ProjectionOperationKind.GroupBy
                    )
                    {
                        querySource =
                            $"{querySource}.Where({ProjectionBodyEmitter.AppendValueInline($"{request.SelectorParameterName} => ", innerJoinFilterBodyText)})";
                    }
                    var convertedInvocation = request.OperationKind switch
                    {
                        ProjectionOperationKind.Select => $"{querySource}.Select({selectArgument})",
                        ProjectionOperationKind.SelectMany => $"{querySource}.SelectMany({lambda})",
                        ProjectionOperationKind.GroupBy =>
                            $"{querySource}.GroupBy({ProjectionBodyEmitter.AppendValueInline($"{request.KeySelectorParameterName} => ", request.KeySelectorBodyText ?? "default!")}).Select({lambda})",
                        _ => throw new InvalidOperationException(
                            $"Unsupported projection operation '{request.OperationKind}'."
                        ),
                    };
                    AppendMultilineLine(
                        builder,
                        $"var converted = {convertedInvocation};",
                        cancellationToken
                    );
                    var returnStatement = request.UsesFluentQuerySyntax
                        ? $"return ({GetReceiverTypeName(request.ReceiverKind)}<TResult>)(object)converted;"
                        : $"return ({receiverType}<TResult>)(object)converted;";
                    builder.AppendLine(returnStatement, cancellationToken);
                }

                builder.AppendLine("}", cancellationToken);
            }

            builder.AppendLine("}", cancellationToken);
        }

        builder.AppendLine("}", cancellationToken);
    }

    private static void WriteObjectGenerationDeclaration(
        IndentedStringBuilder builder,
        ObjectGenerationRequest request,
        LinqraftGeneratorOptionsCore generatorOptions,
        CancellationToken cancellationToken = default
    )
    {
        builder.AppendLine($"namespace {generatorOptions.SupportNamespace}", cancellationToken);
        builder.AppendLine("{", cancellationToken);
        using (builder.Indent())
        {
            builder.AppendLine(
                $"internal static partial class {generatorOptions.GeneratorKitClassName!}",
                cancellationToken
            );
            builder.AppendLine("{", cancellationToken);
            using (builder.Indent())
            {
                if (
                    request.InterceptableLocationVersion is { } interceptableLocationVersion
                    && request.InterceptableLocationData is { } interceptableLocationData
                )
                {
                    builder.AppendLine(
                        $"[global::System.Runtime.CompilerServices.InterceptsLocationAttribute({interceptableLocationVersion}, \"{EscapeStringLiteral(interceptableLocationData)}\")]",
                        cancellationToken
                    );
                }

                if (
                    request.Captures.Length != 0
                    && request.CaptureTransportKind == CaptureTransportKind.AnonymousObject
                )
                {
                    builder.AppendLine(
                        "[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2075\", Justification = \"Capture reflection inspects runtime-generated anonymous objects.\")]",
                        cancellationToken
                    );
                }

                string signature;
                if (request.Captures.Length == 0)
                {
                    signature = $"internal static T {request.MethodName}<T>(object x)";
                }
                else if (request.CaptureTransportKind == CaptureTransportKind.Delegate)
                {
                    signature =
                        $"internal static T {request.MethodName}<T>(object x, global::System.Func<object> capture)";
                }
                else
                {
                    signature =
                        $"internal static T {request.MethodName}<T>(object x, object capture)";
                }

                builder.AppendLine(signature, cancellationToken);
                builder.AppendLine("{", cancellationToken);
                using (builder.Indent())
                {
                    if (request.Captures.Length != 0)
                    {
                        WriteCaptureExtraction(
                            builder,
                            request.Captures,
                            request.CaptureTransportKind,
                            request.CaptureTransportTypeName,
                            cancellationToken
                        );
                    }

                    AppendMultilineLine(
                        builder,
                        $"return (T)(object){request.ProjectionBodyText};",
                        cancellationToken
                    );
                }

                builder.AppendLine("}", cancellationToken);
            }

            builder.AppendLine("}", cancellationToken);
        }

        builder.AppendLine("}", cancellationToken);
    }

    private static void WriteMappingDeclaration(
        IndentedStringBuilder builder,
        MappingRequest request,
        CancellationToken cancellationToken = default
    )
    {
        if (!string.IsNullOrWhiteSpace(request.Namespace))
        {
            builder.AppendLine($"namespace {request.Namespace}", cancellationToken);
            builder.AppendLine("{", cancellationToken);
            builder.IncreaseIndent();
        }

        builder.AppendLine(
            $"{request.AccessibilityKeyword} static partial class {request.ContainingTypeName}",
            cancellationToken
        );
        builder.AppendLine("{", cancellationToken);
        using (builder.Indent())
        {
            var receiverType = GetReceiverTypeName(request.ReceiverKind);
            var lambda = ProjectionBodyEmitter.AppendValueInline(
                $"{request.SelectorParameterName} => ",
                request.ProjectionBodyText
            );
            var expressionFieldName = $"s_expression_{request.MethodName}";
            if (request.CanUsePrebuiltExpression && request.ReceiverKind == ReceiverKind.IQueryable)
            {
                AppendMultilineLine(
                    builder,
                    $"private static readonly global::System.Linq.Expressions.Expression<global::System.Func<{request.SourceTypeName}, {request.ResultTypeName}>> {expressionFieldName} = {lambda};",
                    cancellationToken
                );
                builder.AppendLine();
            }

            builder.AppendLine(
                $"{request.MethodAccessibilityKeyword} static {receiverType}<{request.ResultTypeName}> {request.MethodName}(this {receiverType}<{request.SourceTypeName}> source{string.Concat(request.Captures.Select(capture => $", {capture.TypeName} {capture.PropertyName}"))})",
                cancellationToken
            );
            builder.AppendLine("{", cancellationToken);
            using (builder.Indent())
            {
                foreach (
                    var capture in request.Captures.Where(capture =>
                        capture.LocalName != capture.PropertyName
                    )
                )
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    builder.AppendLine(
                        $"var {capture.LocalName} = {capture.PropertyName};",
                        cancellationToken
                    );
                }

                if (
                    request.CanUsePrebuiltExpression
                    && request.ReceiverKind == ReceiverKind.IQueryable
                )
                {
                    var querySource = request.InnerJoinFilterBodyText is { } innerJoinFilterBodyText
                        ? $"source.Where({ProjectionBodyEmitter.AppendValueInline($"{request.SelectorParameterName} => ", innerJoinFilterBodyText)})"
                        : "source";
                    builder.AppendLine(
                        $"return {querySource}.Select({expressionFieldName});",
                        cancellationToken
                    );
                }
                else
                {
                    var querySource = request.InnerJoinFilterBodyText is { } innerJoinFilterBodyText
                        ? $"source.Where({ProjectionBodyEmitter.AppendValueInline($"{request.SelectorParameterName} => ", innerJoinFilterBodyText)})"
                        : "source";
                    AppendMultilineLine(
                        builder,
                        $"return {querySource}.Select({lambda});",
                        cancellationToken
                    );
                }
            }

            builder.AppendLine("}", cancellationToken);
        }

        builder.AppendLine("}", cancellationToken);

        if (!string.IsNullOrWhiteSpace(request.Namespace))
        {
            builder.DecreaseIndent();
            builder.AppendLine("}", cancellationToken);
        }
    }

    private static IndentedStringBuilder CreateFileBuilder(
        LinqraftConfiguration configuration,
        CancellationToken cancellationToken = default
    )
    {
        var builder = new IndentedStringBuilder();
        builder.AppendLines(
            $$"""
            {{CodeTemplateContents.CreateAutoGeneratedHeader(
                configuration.GeneratorOptions.GeneratedHeaderComment
            )}}
            #nullable enable
            #pragma warning disable CS1591
            #pragma warning disable CS8600
            #pragma warning disable CS8601
            #pragma warning disable CS8602
            #pragma warning disable CS8603
            #pragma warning disable CS8604
            #pragma warning disable CS8618
            using System.Linq;
            """,
            cancellationToken
        );
        return builder;
    }

    private static string FinalizeSource(
        IndentedStringBuilder builder,
        CancellationToken cancellationToken = default
    )
    {
        return GeneratedSourceFormatter.FormatGeneratedSource(
            builder.ToString(),
            cancellationToken
        );
    }

    private static string GetSelectorResultType(ProjectionRequest request)
    {
        if (request.UseObjectSelectorSignature)
        {
            return "object";
        }

        return request.OperationKind == ProjectionOperationKind.SelectMany
            ? "global::System.Collections.Generic.IEnumerable<TResult>"
            : "TResult";
    }

    private static string GetProjectionSupportClassName(
        ProjectionOperationKind operationKind,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        return operationKind switch
        {
            ProjectionOperationKind.Select => generatorOptions.SelectExprClassName,
            ProjectionOperationKind.SelectMany => generatorOptions.SelectManyExprClassName,
            ProjectionOperationKind.GroupBy => generatorOptions.GroupByExprClassName,
            _ => throw new InvalidOperationException(
                $"Unsupported projection operation '{operationKind}'."
            ),
        };
    }

    private static string GetProjectionInterceptorClassName(
        ProjectionOperationKind operationKind,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        var className = GetProjectionSupportClassName(operationKind, generatorOptions);
        return className.EndsWith("Extensions", StringComparison.Ordinal)
            ? $"{className[..^"Extensions".Length]}InterceptExtensions"
            : $"{className}Interceptors";
    }

    private static string GetReceiverTypeName(ReceiverKind receiverKind)
    {
        return receiverKind == ReceiverKind.IQueryable
            ? "global::System.Linq.IQueryable"
            : "global::System.Collections.Generic.IEnumerable";
    }

    private static string GetReceiverTypeName(
        ReceiverKind receiverKind,
        bool usesFluentQuerySyntax,
        LinqraftGeneratorOptionsCore generatorOptions
    )
    {
        if (usesFluentQuerySyntax)
        {
            return receiverKind == ReceiverKind.IQueryable
                ? $"global::{generatorOptions.SupportNamespace}.LinqraftQuery"
                : $"global::{generatorOptions.SupportNamespace}.LinqraftEnumerable";
        }

        return receiverKind == ReceiverKind.IQueryable
            ? "global::System.Linq.IQueryable"
            : "global::System.Collections.Generic.IEnumerable";
    }

    private static string GetFluentQuerySignature(
        ProjectionRequest request,
        string receiverType,
        string selectorType,
        string captureParameter,
        CancellationToken cancellationToken = default
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        var fluentReturnType = GetReceiverTypeName(request.ReceiverKind);
        return request.OperationKind switch
        {
            ProjectionOperationKind.Select => request.Captures.Length == 0
                ? $"public static {fluentReturnType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, {selectorType} selector) where TIn : class"
                : $"public static {fluentReturnType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, {selectorType} selector, {captureParameter}) where TIn : class",
            ProjectionOperationKind.SelectMany => request.Captures.Length == 0
                ? $"public static {fluentReturnType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, {selectorType} selector) where TIn : class"
                : $"public static {fluentReturnType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, {selectorType} selector, {captureParameter}) where TIn : class",
            ProjectionOperationKind.GroupBy => request.Captures.Length == 0
                ? $"public static {fluentReturnType}<TResult> {request.MethodName}<TIn, TKey, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, TKey> keySelector, {selectorType} selector) where TIn : class"
                : $"public static {fluentReturnType}<TResult> {request.MethodName}<TIn, TKey, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, TKey> keySelector, {selectorType} selector, {captureParameter}) where TIn : class",
            _ => throw new InvalidOperationException(
                $"Fluent query syntax is not supported for projection operation '{request.OperationKind}'."
            ),
        };
    }

    private static string CreateNonFluentSignature(
        ProjectionRequest request,
        string receiverType,
        string selectorType,
        string captureParameter
    )
    {
        var signatureSuffix = request.Captures.Length == 0 ? string.Empty : $", {captureParameter}";
        return request.OperationKind switch
        {
            ProjectionOperationKind.Select =>
                $"public static {receiverType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, {selectorType} selector{signatureSuffix}) where TIn : class",
            ProjectionOperationKind.SelectMany =>
                $"public static {receiverType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, {selectorType} selector{signatureSuffix}) where TIn : class",
            ProjectionOperationKind.GroupBy =>
                $"public static {receiverType}<TResult> {request.MethodName}<TIn, TKey, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, TKey> keySelector, {selectorType} selector{signatureSuffix}) where TIn : class",
            _ => throw new InvalidOperationException(
                $"Unsupported projection operation '{request.OperationKind}'."
            ),
        };
    }

    private static void WriteCaptureExtraction(
        IndentedStringBuilder builder,
        IEnumerable<CaptureParameterModel> captures,
        CaptureTransportKind transportKind,
        string? transportTypeName,
        CancellationToken cancellationToken = default
    )
    {
        if (transportKind == CaptureTransportKind.Delegate)
        {
            WriteDelegateCaptureExtraction(builder, captures, transportTypeName, cancellationToken);
            return;
        }

#pragma warning disable LSG013 // Reflection API usage detected. Source generators should generate static code without using reflection, which defeats the purpose of compile-time code generation.
        builder.AppendLine("var captureType = capture.GetType();", cancellationToken);
        foreach (var capture in captures)
        {
            cancellationToken.ThrowIfCancellationRequested();
            builder.AppendLines(
                $$"""
                var {{capture.LocalName}}Property = captureType.GetProperty("{{EscapeStringLiteral(
                    capture.PropertyName
                )}}", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public);
                if ({{capture.LocalName}}Property is null)
                {
                    throw new global::System.InvalidOperationException("Captured value '{{EscapeStringLiteral(
                    capture.PropertyName
                )}}' was not found.");
                }
                var {{capture.LocalName}}Value = {{capture.LocalName}}Property.GetValue(capture);
                var {{capture.LocalName}} = {{capture.LocalName}}Value is null ? default! : ({{capture.TypeName}}){{capture.LocalName}}Value;
                """,
                cancellationToken
            );
        }
    }
#pragma warning restore LSG013

    private static void WriteDelegateCaptureExtraction(
        IndentedStringBuilder builder,
        IEnumerable<CaptureParameterModel> captures,
        string? transportTypeName,
        CancellationToken cancellationToken = default
    )
    {
        if (string.IsNullOrWhiteSpace(transportTypeName))
        {
            throw new InvalidOperationException("Delegate captures require a transport type.");
        }

        var captureArray = captures.ToArray();
        builder.AppendLine("var captureValueBoxed = capture();", cancellationToken);
        builder.AppendLine(
            $"var captureValue = captureValueBoxed is null ? default! : ({transportTypeName})captureValueBoxed;",
            cancellationToken
        );
        foreach (var capture in captureArray)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var valueExpression = capture.ValueAccessor is null
                ? "captureValue"
                : $"captureValue.{capture.ValueAccessor}";
            builder.AppendLine($"var {capture.LocalName} = {valueExpression};", cancellationToken);
        }
    }

    private static string GetAccessor(LinqraftConfiguration configuration, bool isRecord)
    {
        return configuration.PropertyAccessor switch
        {
            LinqraftPropertyAccessor.GetAndSet => "get; set;",
            LinqraftPropertyAccessor.GetAndInit => "get; init;",
            LinqraftPropertyAccessor.GetAndInternalSet => "get; internal set;",
            _ => isRecord ? "get; init;" : "get; set;",
        };
    }

    private static void WriteDocumentation(
        IndentedStringBuilder builder,
        Linqraft.Core.Documentation.DocumentationInfo? documentation,
        LinqraftCommentOutput outputMode,
        CancellationToken cancellationToken = default
    )
    {
        if (documentation is null || outputMode == LinqraftCommentOutput.None)
        {
            return;
        }

        if (!string.IsNullOrWhiteSpace(documentation.Summary))
        {
            var summary = documentation.Summary!;
            builder.AppendLine("/// <summary>", cancellationToken);
            foreach (var line in summary.Split('\n'))
            {
                cancellationToken.ThrowIfCancellationRequested();
                builder.AppendLine($"/// {line.Trim()}", cancellationToken);
            }

            builder.AppendLine("/// </summary>", cancellationToken);
        }

        if (
            outputMode == LinqraftCommentOutput.All
            && !string.IsNullOrWhiteSpace(documentation.Remarks)
        )
        {
            var remarks = documentation.Remarks!;
            builder.AppendLine("/// <remarks>", cancellationToken);
            foreach (var line in remarks.Split('\n'))
            {
                cancellationToken.ThrowIfCancellationRequested();
                builder.AppendLine($"/// {line.Trim()}", cancellationToken);
            }

            builder.AppendLine("/// </remarks>", cancellationToken);
        }
    }

    private static void WriteNamespaceAndContainingTypesStart(
        IndentedStringBuilder builder,
        string namespaceName,
        Linqraft.Core.Collections.EquatableArray<ContainingTypeInfo> containingTypes,
        CancellationToken cancellationToken = default
    )
    {
        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            builder.AppendLine($"namespace {namespaceName}", cancellationToken);
            builder.AppendLine("{", cancellationToken);
            builder.IncreaseIndent();
        }

        foreach (var containingType in containingTypes)
        {
            cancellationToken.ThrowIfCancellationRequested();
            builder.AppendLine(
                $"{containingType.AccessibilityKeyword} partial {containingType.DeclarationKeyword} {containingType.Name}",
                cancellationToken
            );
            builder.AppendLine("{", cancellationToken);
            builder.IncreaseIndent();
        }
    }

    private static void WriteNamespaceAndContainingTypesEnd(
        IndentedStringBuilder builder,
        string namespaceName,
        Linqraft.Core.Collections.EquatableArray<ContainingTypeInfo> containingTypes,
        CancellationToken cancellationToken = default
    )
    {
        for (var index = containingTypes.Length - 1; index >= 0; index--)
        {
            cancellationToken.ThrowIfCancellationRequested();
            builder.DecreaseIndent();
            builder.AppendLine("}", cancellationToken);
        }

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            builder.DecreaseIndent();
            builder.AppendLine("}", cancellationToken);
        }
    }

    private static string EscapeStringLiteral(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static void AppendMultilineLine(
        IndentedStringBuilder builder,
        string value,
        CancellationToken cancellationToken = default
    )
    {
        foreach (var line in SplitLines(value))
        {
            cancellationToken.ThrowIfCancellationRequested();
            builder.AppendLine(line, cancellationToken);
        }
    }

    private static string[] SplitLines(string value)
    {
        return value.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n');
    }

    private static string ToParameterName(string propertyName)
    {
        return string.IsNullOrEmpty(propertyName)
            ? "value"
            : char.ToLowerInvariant(propertyName[0]) + propertyName[1..];
    }
}
