using Linqraft.Core.Configuration;
using Linqraft.Core.Formatting;
using static Linqraft.Core.Generation.CodeTemplateContents;

namespace Linqraft.SourceGenerator;

internal static class SupportSourceEmitter
{
    public static string CreateSupportSource(LinqraftGeneratorOptionsCore generatorOptions)
    {
        var builder = new IndentedStringBuilder();
        builder.AppendLines(
            $$"""
            {{CreateAutoGeneratedHeader(generatorOptions.GeneratedHeaderComment)}}
            #nullable enable
            #pragma warning disable CS1591

            namespace Microsoft.CodeAnalysis
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.All)]
                internal sealed partial class EmbeddedAttribute : global::System.Attribute
                {
                }
            }

            namespace System.Runtime.CompilerServices
            {
                {{EmbeddedAttribute}}
                {{MethodAttributes}}
                internal sealed partial class InterceptsLocationAttribute : global::System.Attribute
                {
                    public InterceptsLocationAttribute(int version, string data)
                    {
                        Version = version;
                        Data = data;
                    }

                    public int Version { get; }

                    public string Data { get; }
                }
            }

            """
        );

        builder.AppendLine($"namespace {generatorOptions.SupportNamespace}");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            builder.AppendLines(
                $$"""
                {{EmbeddedAttribute}}
                file static class LinqraftDeclarationThrowHelpers
                {
                    public static global::System.InvalidOperationException ForProjectionMethod()
                        => new global::System.InvalidOperationException("{{generatorOptions.GeneratorDisplayName}} source generator should replace invocations before execution.");

                    public static global::System.InvalidOperationException ForProjectionHelper()
                        => new global::System.InvalidOperationException("{{generatorOptions.GeneratorDisplayName}} source generator should replace projection helper invocations before execution.");

                    public static global::System.InvalidOperationException ForFluentProjection()
                        => new global::System.InvalidOperationException("{{generatorOptions.GeneratorDisplayName}} source generator should replace UseLinqraft projection invocations before execution.");

                    public static global::System.InvalidOperationException ForObjectGeneration()
                        => new global::System.InvalidOperationException("{{generatorOptions.GeneratorDisplayName}} source generator should replace {{generatorOptions.ObjectGenerationMethodName}} invocations before execution.");

                    public static global::System.InvalidOperationException ForMappingDeclaration()
                        => new global::System.InvalidOperationException("{{generatorOptions.GeneratorDisplayName}} source generator should replace mapping declarations before execution.");
                }

                """
            );
            if (
                generatorOptions.MappingVisibilityEnumName is { } mappingVisibilityEnumName
                && generatorOptions.MappingGenerateAttributeName is { } mappingGenerateAttributeName
            )
            {
                builder.AppendLines(
                    $$"""
                    /// <summary>
                    /// Controls the accessibility of generated mapping helpers.
                    /// </summary>
                    {{EmbeddedAttribute}}
                    internal enum {{mappingVisibilityEnumName}}
                    {
                        Default = 0,
                        Internal = 1,
                        Public = 2,
                    }

                    /// <summary>
                    /// Marks a mapping declaration that {{generatorOptions.GeneratorDisplayName}} should turn into a reusable projection method.
                    /// </summary>
                    {{EmbeddedAttribute}}
                    {{ClassAndMethodAttributes}}
                    internal sealed partial class {{mappingGenerateAttributeName}} : global::System.Attribute
                    {
                        public {{mappingGenerateAttributeName}}()
                        {
                        }

                        public {{mappingGenerateAttributeName}}(string methodName)
                        {
                            MethodName = methodName;
                        }

                        public string? MethodName { get; }

                        public {{mappingVisibilityEnumName}} Visibility { get; set; }
                    }

                    """
                );
            }

            if (generatorOptions.AutoGeneratedDtoAttributeName is { } autoGeneratedDtoAttributeName)
            {
                builder.AppendLines(
                    $$"""
                    /// <summary>
                    /// Marks DTO types that {{generatorOptions.GeneratorDisplayName}} generated as implementation details for nested projections.
                    /// </summary>
                    {{EmbeddedAttribute}}
                    {{EditorBrowsableNeverAttribute}}
                    {{ClassAttributes}}
                    internal sealed partial class {{autoGeneratedDtoAttributeName}} : global::System.Attribute
                    {
                    }

                    """
                );
            }

            if (generatorOptions.MappingDeclareClassName is { } mappingDeclareClassName)
            {
                builder.AppendLines(
                    $$"""
                    /// <summary>
                    /// Base type for reusable mapping declarations. Override <see cref="DefineMapping"/> and describe the projection with <c>{{generatorOptions.SelectExprMethodName}}</c>.
                    /// </summary>
                    {{EmbeddedAttribute}}
                    internal abstract partial class {{mappingDeclareClassName}}<T>
                    {
                        protected global::System.Linq.IQueryable<T> Source => throw LinqraftDeclarationThrowHelpers.ForMappingDeclaration();

                        protected abstract void DefineMapping();
                    }

                    """
                );
            }

            if (generatorOptions.GeneratorKitClassName is { } generatorKitClassName)
            {
                builder.AppendLines(
                    $$"""
                    /// <summary>
                    /// Provides the object-conversion entry point that {{generatorOptions.GeneratorDisplayName}} rewrites into a generated DTO factory before the stub can run.
                    /// </summary>
                    {{EmbeddedAttribute}}
                    internal static partial class {{generatorKitClassName}}
                    {
                        /// <summary>
                        /// Generates a DTO of type <typeparamref name="T"/> from the supplied anonymous object initializer.
                        /// {{generatorOptions.GeneratorDisplayName}} inspects the initializer, lifts any nested projection calls such as <c>{{generatorOptions.SelectExprMethodName}}</c>,
                        /// and replaces this stub with generated code that materializes a concrete DTO.
                        /// </summary>
                        /// <typeparam name="T">The generated DTO type to return.</typeparam>
                        /// <param name="x">
                        /// An anonymous object initializer that describes the shape of the DTO to create.
                        /// </param>
                        /// <returns>The generated DTO instance.</returns>
                        /// <example>
                        /// <code>
                        /// var dto = {{generatorOptions.GeneratorKitClassName}}.{{generatorOptions.ObjectGenerationMethodName}}&lt;OrderSummaryDto&gt;(new
                        /// {
                        ///     Id = order.Id,
                        ///     Items = order.Items.{{generatorOptions.SelectExprMethodName}}&lt;OrderItem, OrderItemDto&gt;(item =&gt; new { item.Id })
                        /// });
                        /// </code>
                        /// </example>
                        public static T {{generatorOptions.ObjectGenerationMethodName}}<T>(object x)
                            => throw LinqraftDeclarationThrowHelpers.ForObjectGeneration();

                        /// <summary>
                        /// Generates a DTO of type <typeparamref name="T"/> from the supplied anonymous object initializer
                        /// and a NativeAOT-safe capture provider.
                        /// </summary>
                        /// <typeparam name="T">The generated DTO type to return.</typeparam>
                        /// <param name="x">
                        /// An anonymous object initializer that describes the DTO members to generate.
                        /// </param>
                        /// <param name="capture">
                        /// A callback that returns any external values the generated projection should inline without reflection-based anonymous-object capture.
                        /// </param>
                        /// <returns>The generated DTO instance.</returns>
                        /// <example>
                        /// <code>
                        /// var dto = {{generatorOptions.GeneratorKitClassName}}.{{generatorOptions.ObjectGenerationMethodName}}&lt;OrderSummaryDto&gt;(
                        ///     new { Total = order.Total + offset },
                        ///     () =&gt; new { offset }
                        /// );
                        /// </code>
                        /// </example>
                        public static T {{generatorOptions.ObjectGenerationMethodName}}<T>(object x, global::System.Func<object> capture)
                            => throw LinqraftDeclarationThrowHelpers.ForObjectGeneration();
                    }

                    """
                );
            }

            var extensionDeclarations =
                ProjectionSupportExtensionClassGenerator.CreateAllDeclarations(generatorOptions);
            if (!string.IsNullOrWhiteSpace(extensionDeclarations))
            {
                builder.AppendLines(extensionDeclarations);
            }
        }

        builder.AppendLine("}");
        return builder.ToString();
    }
}
