/// <auto-generated />
#pragma warning disable IDE0060

namespace EFCore.ExprGenerator.Sample
{
    // --- below is generated code ---
#if true

    internal static class GeneratedExpression
    {
        /// <summary>
        /// generated method
        /// </summary>
        public static IQueryable<SampleDto> SelectExpr<TResult>(
            this IQueryable<SampleClass> query,
            Func<SampleClass, TResult> selector
        )
        {
            Console.WriteLine("Generated SelectExpr called");
            return query.Select(s => new SampleDto
            {
                Id = s.Id,
                Foo = s.Foo,
                Bar = s.Bar,
                Childs = s
                    .Childs.Select(c => new SampleChildDto
                    {
                        Id = c.Id,
                        Baz = c.Baz,
                        ChildId = c.Child != null ? c.Child.Id : null,
                        ChildQux = c.Child != null ? c.Child.Qux : null,
                    })
                    .ToList(),
                Child2Id = s.Child2 != null ? s.Child2.Id : null,
                Child2Quux = s.Child2 != null ? s.Child2.Quux : null,
                Child3Id = s.Child3.Id,
                Child3Corge = s.Child3.Corge,
                Child3ChildId = s.Child3.Child != null ? s.Child3.Child.Id : null,
                Child3ChildGrault = s.Child3.Child != null ? s.Child3.Child.Grault : null,
            });
        }
    }

    public class SampleDto
    {
        public int Id { get; set; }
        public string Foo { get; set; } = string.Empty;
        public string Bar { get; set; } = string.Empty;

        public List<SampleChildDto> Childs { get; set; } = new();

        public int? Child2Id { get; set; }
        public string? Child2Quux { get; set; }

        public int Child3Id { get; set; }
        public string Child3Corge { get; set; } = string.Empty;

        public int? Child3ChildId { get; set; }
        public string? Child3ChildGrault { get; set; }
    }

    public class SampleChildDto
    {
        public int Id { get; set; }
        public string Baz { get; set; } = string.Empty;

        public int? ChildId { get; set; }
        public string? ChildQux { get; set; }
    }

#endif
}
