using Linqraft.Core.Configuration;

namespace Linqraft.Generator;

public sealed class LinqraftGeneratorOptions : LinqraftGeneratorOptionsCore
{
    public override string GeneratorDisplayName => "Linqraft";

    public override string GeneratedHeaderComment =>
        $"This file is auto-generated by Linqraft (Ver. {ThisAssembly.AssemblyInformationalVersion})";
}
