using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Linqraft.Core.Documentation;

namespace Linqraft.SourceGenerator;

internal enum ReceiverKind
{
    IQueryable,
    IEnumerable,
}

internal enum ProjectionPattern
{
    Anonymous,
    ExplicitDto,
    PredefinedDto,
}

internal sealed record CaptureEntryModel
{
    public required string PropertyName { get; init; }

    public required string LocalName { get; init; }

    public required string TypeName { get; init; }
}

internal sealed record ProjectionMemberModel
{
    public required string Name { get; init; }

    public required ExpressionSyntax Expression { get; init; }

    public required string TypeName { get; init; }

    public required bool UseEmptyCollectionFallback { get; init; }

    public required DocumentationInfo? Documentation { get; init; }

    public required Dictionary<SyntaxNode, string> ReplacementTypes { get; init; }
}

internal sealed record ProjectionObjectModel
{
    public required ExpressionSyntax Syntax { get; init; }

    public required string? ReplacementTypeName { get; init; }

    public required IReadOnlyList<ProjectionMemberModel> Members { get; init; }

    public required Dictionary<SyntaxNode, string> ReplacementTypes { get; init; }
}

internal sealed record ContainingTypeInfo
{
    public required string AccessibilityKeyword { get; init; }

    public required string DeclarationKeyword { get; init; }

    public required string Name { get; init; }
}

internal sealed record GeneratedPropertyModel
{
    public required string Name { get; init; }

    public required string TypeName { get; init; }

    public required DocumentationInfo? Documentation { get; init; }

    public required bool IsSuppressed { get; init; }
}

internal sealed record GeneratedDtoModel
{
    public required string Key { get; init; }

    public required string Namespace { get; init; }

    public required string Name { get; init; }

    public required string FullyQualifiedName { get; init; }

    public required string AccessibilityKeyword { get; init; }

    public required bool IsRecord { get; init; }

    public required bool IsRoot { get; init; }

    public required bool IsAutoGeneratedNested { get; init; }

    public required DocumentationInfo? Documentation { get; init; }

    public required string ShapeSignature { get; set; }

    public required IReadOnlyList<ContainingTypeInfo> ContainingTypes { get; init; }

    public required List<GeneratedPropertyModel> Properties { get; init; }
}

internal sealed record ProjectionRequest
{
    public required string HintName { get; init; }

    public required string MethodName { get; init; }

    public required ReceiverKind ReceiverKind { get; init; }

    public required ProjectionPattern Pattern { get; init; }

    public required InvocationExpressionSyntax Invocation { get; init; }

    public required string SourceTypeName { get; init; }

    public required string ResultTypeName { get; init; }

    public required string SelectorParameterName { get; init; }

    public required bool UseObjectSelectorSignature { get; init; }

    public required bool CanUsePrebuiltExpression { get; init; }

    public required Microsoft.CodeAnalysis.CSharp.InterceptableLocation? InterceptableLocation { get; init; }

    public required IReadOnlyList<CaptureEntryModel> Captures { get; init; }

    public required ProjectionObjectModel RootProjection { get; init; }

    public required DocumentationInfo? RootDocumentation { get; init; }
}

internal sealed record MappingRequest
{
    public required string HintName { get; init; }

    public required SyntaxNode SourceNode { get; init; }

    public required string Namespace { get; init; }

    public required string ContainingTypeName { get; init; }

    public required string AccessibilityKeyword { get; init; }

    public required string MethodName { get; init; }

    public required ReceiverKind ReceiverKind { get; init; }

    public required string SourceTypeName { get; init; }

    public required string ResultTypeName { get; init; }

    public required string SelectorParameterName { get; init; }

    public required bool CanUsePrebuiltExpression { get; init; }

    public required IReadOnlyList<CaptureEntryModel> Captures { get; init; }

    public required ProjectionObjectModel RootProjection { get; init; }
}

internal static class GeneratorDiagnostics
{
    public static readonly DiagnosticDescriptor InvalidSelectExpr =
        new(
            id: "LinqraftSG001",
            title: "Unsupported SelectExpr shape",
            messageFormat: "{0}",
            category: "Linqraft",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true
        );

    public static readonly DiagnosticDescriptor ConflictingDtoShape =
        new(
            id: "LinqraftSG002",
            title: "Conflicting DTO shape",
            messageFormat: "Generated DTO '{0}' was requested with incompatible shapes. {1}",
            category: "Linqraft",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true
        );
}
