using Linqraft.Core.Collections;
using Linqraft.Core.Documentation;

namespace Linqraft.SourceGenerator;

internal enum ReceiverKind
{
    IQueryable,
    IEnumerable,
}

internal enum ProjectionPattern
{
    Anonymous,
    ExplicitDto,
    PredefinedDto,
}

internal enum ProjectionOperationKind
{
    Select,
    SelectMany,
    GroupBy,
}

internal enum GeneratedDtoTemplateKind
{
    RootExplicit,
    NestedAuto,
}

internal sealed record CaptureParameterModel
{
    public required string PropertyName { get; init; }

    public required string LocalName { get; init; }

    public required string TypeName { get; init; }
}

internal sealed record ContainingTypeInfo
{
    public required string AccessibilityKeyword { get; init; }

    public required string DeclarationKeyword { get; init; }

    public required string Name { get; init; }
}

internal sealed record GeneratedPropertyTemplateModel
{
    public required string Name { get; init; }

    public required string TypeTemplate { get; init; }

    public required string FallbackTypeTemplate { get; init; }

    public required DocumentationInfo? Documentation { get; init; }

    public required bool IsSuppressed { get; init; }
}

internal sealed record ProjectionMemberTemplateModel
{
    public required string Name { get; init; }

    public required string TypeTemplate { get; init; }

    public required string FallbackTypeTemplate { get; init; }

    public required DocumentationInfo? Documentation { get; init; }

    public required bool IsSuppressed { get; init; }

    public required string ValueTemplate { get; init; }

    public required string FallbackValueTemplate { get; init; }
}

internal sealed record ProjectionTemplateModel
{
    public required EquatableArray<ProjectionMemberTemplateModel> Members { get; init; }
}

internal sealed record GeneratedDtoTemplateModel
{
    public required string TemplateId { get; init; }

    public required string PlaceholderToken { get; init; }

    public required GeneratedDtoTemplateKind Kind { get; init; }

    public required string PreferredNamespace { get; init; }

    public required bool UseGlobalNamespaceFallback { get; init; }

    public required string Name { get; init; }

    public required string ShapeHash { get; init; }

    public required string AccessibilityKeyword { get; init; }

    public required bool? DeclaredIsRecord { get; init; }

    public required bool IsRoot { get; init; }

    public required bool IsAutoGeneratedNested { get; init; }

    public required DocumentationInfo? Documentation { get; init; }

    public required string OwnerHintName { get; init; }

    public required string ShapeSignature { get; init; }

    public required EquatableArray<ContainingTypeInfo> ContainingTypes { get; init; }

    public required EquatableArray<GeneratedPropertyTemplateModel> Properties { get; init; }
}

internal sealed record ProjectionRequestTemplate
{
    public required string HintName { get; init; }

    public required string MethodName { get; init; }

    public required ProjectionOperationKind OperationKind { get; init; }

    public required ReceiverKind ReceiverKind { get; init; }

    public required ProjectionPattern Pattern { get; init; }

    public required string SourceTypeName { get; init; }

    public required string ResultTypeTemplate { get; init; }

    public required string SelectorParameterName { get; init; }

    public string? KeySelectorParameterName { get; init; }

    public string? KeySelectorBodyTemplate { get; init; }

    public required bool UseObjectSelectorSignature { get; init; }

    public required bool CanUsePrebuiltExpressionWhenConfigured { get; init; }

    public required int? InterceptableLocationVersion { get; init; }

    public required string? InterceptableLocationData { get; init; }

    public required EquatableArray<CaptureParameterModel> Captures { get; init; }

    public ProjectionTemplateModel? Projection { get; init; }

    public string? ProjectionBodyTemplate { get; init; }
}

internal sealed record MappingRequestTemplate
{
    public required string HintName { get; init; }

    public required string Namespace { get; init; }

    public required string ContainingTypeName { get; init; }

    public required string AccessibilityKeyword { get; init; }

    public required string MethodAccessibilityKeyword { get; init; }

    public required string MethodName { get; init; }

    public required ReceiverKind ReceiverKind { get; init; }

    public required string SourceTypeName { get; init; }

    public required string ResultTypeTemplate { get; init; }

    public required string SelectorParameterName { get; init; }

    public required bool CanUsePrebuiltExpressionWhenConfigured { get; init; }

    public required ProjectionTemplateModel Projection { get; init; }
}

internal sealed record ProjectionSourceTemplateModel
{
    public required ProjectionRequestTemplate Request { get; init; }

    public required EquatableArray<GeneratedDtoTemplateModel> GeneratedDtos { get; init; }
}

internal sealed record MappingSourceTemplateModel
{
    public required MappingRequestTemplate Request { get; init; }

    public required EquatableArray<GeneratedDtoTemplateModel> GeneratedDtos { get; init; }
}

internal sealed record GeneratedPropertyModel
{
    public required string Name { get; init; }

    public required string TypeName { get; init; }

    public required DocumentationInfo? Documentation { get; init; }

    public required bool IsSuppressed { get; init; }
}

internal sealed record GeneratedDtoModel
{
    public required string Key { get; init; }

    public required string Namespace { get; init; }

    public required string Name { get; init; }

    public required string FullyQualifiedName { get; init; }

    public required string AccessibilityKeyword { get; init; }

    public required bool IsRecord { get; init; }

    public required bool IsRoot { get; init; }

    public required bool IsAutoGeneratedNested { get; init; }

    public required DocumentationInfo? Documentation { get; init; }

    public required string OwnerHintName { get; init; }

    public required string ShapeSignature { get; init; }

    public required EquatableArray<ContainingTypeInfo> ContainingTypes { get; init; }

    public required EquatableArray<GeneratedPropertyModel> Properties { get; init; }
}

internal sealed record GeneratedDtoEmissionModel
{
    public required GeneratedDtoModel Dto { get; init; }

    public required EquatableArray<string> OwnerHintNames { get; init; }
}

internal sealed record ProjectionRequest
{
    public required string HintName { get; init; }

    public required string MethodName { get; init; }

    public required ProjectionOperationKind OperationKind { get; init; }

    public required ReceiverKind ReceiverKind { get; init; }

    public required ProjectionPattern Pattern { get; init; }

    public required string SourceTypeName { get; init; }

    public required string ResultTypeName { get; init; }

    public required string SelectorParameterName { get; init; }

    public string? KeySelectorParameterName { get; init; }

    public string? KeySelectorBodyText { get; init; }

    public required bool UseObjectSelectorSignature { get; init; }

    public required bool CanUsePrebuiltExpression { get; init; }

    public required int? InterceptableLocationVersion { get; init; }

    public required string? InterceptableLocationData { get; init; }

    public required EquatableArray<CaptureParameterModel> Captures { get; init; }

    public required string ProjectionBodyText { get; init; }
}

internal sealed record ObjectGenerationRequestTemplate
{
    public required string HintName { get; init; }

    public required string MethodName { get; init; }

    public required string ResultTypeTemplate { get; init; }

    public required ProjectionTemplateModel Projection { get; init; }

    public required int? InterceptableLocationVersion { get; init; }

    public required string? InterceptableLocationData { get; init; }
}

internal sealed record ObjectGenerationSourceTemplateModel
{
    public required ObjectGenerationRequestTemplate Request { get; init; }

    public required EquatableArray<GeneratedDtoTemplateModel> GeneratedDtos { get; init; }
}

internal sealed record ObjectGenerationRequest
{
    public required string HintName { get; init; }

    public required string MethodName { get; init; }

    public required string ResultTypeName { get; init; }

    public required string ProjectionBodyText { get; init; }

    public required int? InterceptableLocationVersion { get; init; }

    public required string? InterceptableLocationData { get; init; }
}

internal sealed record ObjectGenerationModel
{
    public required ObjectGenerationRequest Request { get; init; }

    public required EquatableArray<GeneratedDtoModel> GeneratedDtos { get; init; }
}

internal sealed record MappingRequest
{
    public required string HintName { get; init; }

    public required string Namespace { get; init; }

    public required string ContainingTypeName { get; init; }

    public required string AccessibilityKeyword { get; init; }

    public required string MethodAccessibilityKeyword { get; init; }

    public required string MethodName { get; init; }

    public required ReceiverKind ReceiverKind { get; init; }

    public required string SourceTypeName { get; init; }

    public required string ResultTypeName { get; init; }

    public required string SelectorParameterName { get; init; }

    public required bool CanUsePrebuiltExpression { get; init; }

    public required string ProjectionBodyText { get; init; }
}

internal sealed record ProjectionGenerationModel
{
    public required ProjectionRequest Request { get; init; }

    public required EquatableArray<GeneratedDtoModel> GeneratedDtos { get; init; }
}

internal sealed record MappingGenerationModel
{
    public required MappingRequest Request { get; init; }

    public required EquatableArray<GeneratedDtoModel> GeneratedDtos { get; init; }
}
