using System.Collections.Generic;
using Linqraft.Core.Formatting;
using static Linqraft.Core.Generation.CodeTemplateContents;

namespace Linqraft.SourceGenerator;

internal static class LinqraftExtensionStubEmitter
{
    public static string EmitExtensionStubSource(LinqraftExtensionMethodInfo extension)
    {
        var targetNamespace = string.IsNullOrWhiteSpace(extension.GenerateNamespace)
            ? "Linqraft"
            : extension.GenerateNamespace;
        var className = $"Linqraft{extension.MethodName}Extensions";

        var builder = new IndentedStringBuilder();
        builder.AppendLines(
            $"""
            {AutoGeneratedHeader}
            #nullable enable
            #pragma warning disable CS1591

            """
        );

        builder.AppendLine($"namespace {targetNamespace}");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            builder.AppendLine("/// <summary>");
            builder.AppendLine(
                $"/// Linqraft extension stub for <c>{extension.MethodName}</c>. This method is intercepted by the Linqraft source generator and is never executed directly."
            );
            builder.AppendLine("/// </summary>");
            builder.AppendLine(
                "[global::Microsoft.CodeAnalysis.EmbeddedAttribute]"
            );
            builder.AppendLine($"internal static partial class {className}");
            builder.AppendLine("{");
            using (builder.Indent())
            {
                builder.AppendLine("/// <summary>");
                builder.AppendLine(
                    $"/// Linqraft extension stub. This call is intercepted by the Linqraft source generator."
                );
                builder.AppendLine("/// </summary>");
                builder.AppendLine(
                    $"[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]"
                );
                builder.AppendLine(GetStubMethodSignature(extension));
                using (builder.Indent())
                {
                    builder.AppendLine(GetStubMethodBody(extension));
                }
            }
            builder.AppendLine("}");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string GetStubMethodSignature(LinqraftExtensionMethodInfo extension)
    {
        return extension.Behavior switch
        {
            LinqraftExtensionBehaviorKind.CastToFirstTypeArgument =>
                $"public static TResult {extension.MethodName}<TResult>(this object source)",
            _ =>
                $"public static T {extension.MethodName}<T>(this T source) where T : class",
        };
    }

    private static string GetStubMethodBody(LinqraftExtensionMethodInfo extension)
    {
        return extension.Behavior switch
        {
            LinqraftExtensionBehaviorKind.CastToFirstTypeArgument =>
                "=> throw new global::System.InvalidOperationException(\"Linqraft source generator should replace this invocation before execution.\");",
            _ =>
                "=> source;",
        };
    }

    public static IEnumerable<(string HintName, string Source)> EmitAllExtensionStubSources(
        IEnumerable<LinqraftExtensionMethodInfo> extensions
    )
    {
        foreach (var extension in extensions)
        {
            var hintName =
                $"LinqraftExtensionStub_{extension.MethodName}.g.cs";
            yield return (hintName, EmitExtensionStubSource(extension));
        }
    }
}
