using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Linqraft;

internal class SelectExprGroups
{
    public required List<SelectExprLocations> Exprs { get; set; }

    public required string TargetNamespace
    {
        get
        {
            if (IsGlobalNamespace)
            {
                return "Linqraft";
            }
            return targetNamespace;
        }
        set => targetNamespace = value.Trim();
    }
    private string targetNamespace = "";

    // Determine if the target namespace is global (empty or compiler-generated)
    private bool IsGlobalNamespace =>
        string.IsNullOrEmpty(targetNamespace) || targetNamespace.Contains("<");

    public string GetUniqueId()
    {
        if (IsGlobalNamespace)
        {
            return "Global";
        }
        return TargetNamespace.Replace('.', '_');
    }

    // Generate source code
    public virtual void GenerateCode(SourceProductionContext context)
    {
        try
        {
            var dtoClassInfos = new List<GenerateDtoClassInfo>();
            var selectExprMethods = new List<string>();

            foreach (var expr in Exprs)
            {
                var info = expr.Info;
                var classInfos = info.GenerateDtoClasses();
                var exprMethods = info.GenerateSelectExprCodes(expr.Location);
                dtoClassInfos.AddRange(classInfos);
                selectExprMethods.AddRange(exprMethods);
            }

            // drop duplicate DTO classes based on full name
            var dtoClassesDistinct = dtoClassInfos
                .GroupBy(c => c.FullName)
                .Select(g => g.First())
                .ToList();
            var dtoClassesCode = dtoClassesDistinct.Select(c => c.BuildCode()).ToList();

            // Build final source code
            var sourceCode = BuildSourceCode(dtoClassesCode, selectExprMethods);

            // Register with Source Generator
            var uniqueId = GetUniqueId();
            context.AddSource($"GeneratedExpression_{uniqueId}.g.cs", sourceCode);
        }
        catch (Exception ex)
        {
            // Output error information for debugging
            var errorMessage = $"""
                /*
                 * Source Generator Error: {ex.Message}
                 * Stack Trace: {ex.StackTrace}
                 */
                """;
            var hash = Guid.NewGuid().ToString("N")[..8];
            context.AddSource($"GeneratorError_{hash}.g.cs", errorMessage);
        }
    }

    private string BuildSourceCode(List<string> dtoClasses, List<string> selectExprMethods)
    {
        var indentedExpr = IndentUtility(string.Join("\n", selectExprMethods), 8);
        var indentedClasses = IndentUtility(string.Join("\n", dtoClasses), 4);
        return $$"""
            {{GenerateFileHeaderPart()}}

            namespace Linqraft
            {
                file static partial class GeneratedExpression
                {
            {{indentedExpr}}
                }
            }

            namespace {{TargetNamespace}}
            {
            {{indentedClasses}}
            }
            """;
    }

    protected string GenerateFileHeaderPart()
    {
        return $"""
            // <auto-generated />
            #nullable enable
            #pragma warning disable IDE0060
            #pragma warning disable CS8601
            #pragma warning disable CS8603
            #pragma warning disable CS8604

            {GetUsingNamespaceString()}
            """;
    }

    protected string GetUsingNamespaceString()
    {
        return $"""
            using System;
            using System.Linq;
            using System.Collections.Generic;
            using {TargetNamespace};
            """;
    }

    private string IndentUtility(string code, int indentSpaces)
    {
        var indent = new string(' ', indentSpaces);
        var indentedLines = code.Split('\n')
            .Select(line => string.IsNullOrWhiteSpace(line) ? line : indent + line);
        return string.Join("\n", indentedLines);
    }
}

internal class SelectExprLocations
{
    public required SelectExprInfo Info { get; init; }
    public required InterceptableLocation Location { get; init; }
}
