using System.Linq;
using Linqraft.Core.Configuration;
using Linqraft.Core.Formatting;
using Linqraft.Core.Generation;
using Linqraft.Core.Utilities;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Linqraft.SourceGenerator;

internal static class SourceWriters
{
    public static string WriteDtoSource(GeneratedDtoModel dto, LinqraftConfiguration configuration)
    {
        var builder = CreateFileBuilder();

        WriteNamespaceAndContainingTypesStart(builder, dto.Namespace, dto.ContainingTypes);

        if (dto.IsAutoGeneratedNested)
        {
            builder.AppendLine(CodeTemplateContents.EditorBrowsableNeverAttribute);
            builder.AppendLine("[global::Linqraft.LinqraftAutoGeneratedDtoAttribute]");
        }

        WriteDocumentation(builder, dto.Documentation, configuration.CommentOutput);

        var declarationKeyword = dto.IsRecord ? "record" : "class";
        builder.AppendLine($"{dto.AccessibilityKeyword} partial {declarationKeyword} {dto.Name}");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            foreach (var property in dto.Properties.Where(property => !property.IsSuppressed))
            {
                WriteDocumentation(builder, property.Documentation, configuration.CommentOutput);
                var required = configuration.HasRequired ? "required " : string.Empty;
                builder.AppendLine(
                    $"public {required}{property.TypeName} {property.Name} {{ {GetAccessor(configuration, dto.IsRecord)} }}"
                );
            }
        }

        builder.AppendLine("}");

        WriteNamespaceAndContainingTypesEnd(builder, dto.Namespace, dto.ContainingTypes);
        return builder.ToString();
    }

    public static string WriteInterceptorSource(
        ProjectionRequest request,
        SemanticModel semanticModel,
        LinqraftConfiguration configuration
    )
    {
        var builder = CreateFileBuilder();
        builder.AppendLine("namespace Linqraft");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            builder.AppendLine("file static partial class GeneratedExpression");
            builder.AppendLine("{");
            using (builder.Indent())
            {
                if (request.InterceptableLocation is not null)
                {
                    builder.AppendLine(
                        $"[global::System.Runtime.CompilerServices.InterceptsLocationAttribute({request.InterceptableLocation.Version}, \"{EscapeStringLiteral(request.InterceptableLocation.Data)}\")]"
                    );
                }

                var lambda = WriteProjectionLambda(request.RootProjection, request, semanticModel);
                var expressionFieldName = $"s_expression_{request.MethodName}";
                if (request.CanUsePrebuiltExpression && request.ReceiverKind == ReceiverKind.IQueryable)
                {
                    builder.AppendLine(
                        $"private static readonly global::System.Linq.Expressions.Expression<global::System.Func<{request.SourceTypeName}, {request.ResultTypeName}>> {expressionFieldName} = {lambda};"
                    );
                    builder.AppendLine();
                }

                var receiverType = request.ReceiverKind == ReceiverKind.IQueryable
                    ? "global::System.Linq.IQueryable"
                    : "global::System.Collections.Generic.IEnumerable";
                var selectorResultType = request.UseObjectSelectorSignature ? "object" : "TResult";
                var signature = request.Captures.Count == 0
                    ? $"public static {receiverType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, {selectorResultType}> selector)"
                    : $"public static {receiverType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, {selectorResultType}> selector, object capture)";
                builder.AppendLine(signature);
                builder.AppendLine("{");
                using (builder.Indent())
                {
                    builder.AppendLine(
                        $"var matchedQuery = query as {receiverType}<{request.SourceTypeName}> ?? throw new global::System.InvalidOperationException(\"Linqraft intercepted a SelectExpr call with an unexpected source type.\");"
                    );
                    foreach (var capture in request.Captures)
                    {
                        builder.AppendLine(
                            $"var {capture.LocalName} = global::Linqraft.LinqraftCaptureHelper.GetRequired<{capture.TypeName}>(capture, \"{EscapeStringLiteral(capture.PropertyName)}\");"
                        );
                    }

                    if (request.CanUsePrebuiltExpression && request.ReceiverKind == ReceiverKind.IQueryable)
                    {
                        builder.AppendLine($"var converted = matchedQuery.Select({expressionFieldName});");
                        builder.AppendLine(
                            $"return converted as {receiverType}<TResult> ?? throw new global::System.InvalidOperationException(\"Linqraft intercepted a SelectExpr call with an unexpected result type.\");"
                        );
                    }
                    else
                    {
                        builder.AppendLine($"var converted = matchedQuery.Select({lambda});");
                        builder.AppendLine(
                            $"return converted as {receiverType}<TResult> ?? throw new global::System.InvalidOperationException(\"Linqraft intercepted a SelectExpr call with an unexpected result type.\");"
                        );
                    }
                }

                builder.AppendLine("}");
            }

            builder.AppendLine("}");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    public static string WriteMappingSource(
        MappingRequest request,
        SemanticModel semanticModel,
        LinqraftConfiguration configuration
    )
    {
        var builder = CreateFileBuilder();
        if (!string.IsNullOrWhiteSpace(request.Namespace))
        {
            builder.AppendLine($"namespace {request.Namespace}");
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }

        builder.AppendLine($"{request.AccessibilityKeyword} static partial class {request.ContainingTypeName}");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            var receiverType = request.ReceiverKind == ReceiverKind.IQueryable
                ? "global::System.Linq.IQueryable"
                : "global::System.Collections.Generic.IEnumerable";
            var lambda = WriteProjectionLambda(request.RootProjection, request, semanticModel);
            var expressionFieldName = $"s_expression_{request.MethodName}";
            if (request.CanUsePrebuiltExpression && request.ReceiverKind == ReceiverKind.IQueryable)
            {
                builder.AppendLine(
                    $"private static readonly global::System.Linq.Expressions.Expression<global::System.Func<{request.SourceTypeName}, {request.ResultTypeName}>> {expressionFieldName} = {lambda};"
                );
                builder.AppendLine();
            }

            builder.AppendLine(
                $"{request.AccessibilityKeyword} static {receiverType}<{request.ResultTypeName}> {request.MethodName}(this {receiverType}<{request.SourceTypeName}> source)"
            );
            builder.AppendLine("{");
            using (builder.Indent())
            {
                if (request.CanUsePrebuiltExpression && request.ReceiverKind == ReceiverKind.IQueryable)
                {
                    builder.AppendLine($"return source.Select({expressionFieldName});");
                }
                else
                {
                    builder.AppendLine($"return source.Select({lambda});");
                }
            }

            builder.AppendLine("}");
        }

        builder.AppendLine("}");

        if (!string.IsNullOrWhiteSpace(request.Namespace))
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static string WriteProjectionLambda(
        ProjectionObjectModel projection,
        ProjectionRequest request,
        SemanticModel semanticModel
    )
    {
        return $"{request.SelectorParameterName} => {WriteProjectionBody(projection, request.Pattern, request.ResultTypeName, semanticModel)}";
    }

    private static string WriteProjectionLambda(
        ProjectionObjectModel projection,
        MappingRequest request,
        SemanticModel semanticModel
    )
    {
        return $"{request.SelectorParameterName} => {WriteProjectionBody(projection, ProjectionPattern.ExplicitDto, request.ResultTypeName, semanticModel)}";
    }

    private static string WriteProjectionBody(
        ProjectionObjectModel projection,
        ProjectionPattern pattern,
        string resultTypeName,
        SemanticModel semanticModel
    )
    {
        var kind = pattern == ProjectionPattern.Anonymous ? "anonymous" : "named";
        var targetType = pattern == ProjectionPattern.Anonymous ? null : resultTypeName;
        var assignments = projection.Members.Select(
            member =>
            {
                var visited = new AnonymousReplacementRewriter(member.ReplacementTypes).Visit(member.Expression);
                var transformed = visited as ExpressionSyntax ?? member.Expression;
                var emitter = new ProjectionExpressionEmitter(
                    semanticModel,
                    transformed,
                    member.TypeName,
                    member.UseEmptyCollectionFallback
                );
                return $"{member.Name} = {emitter.Emit(transformed)}";
            }
        );

        return kind == "anonymous"
            ? $"new {{ {string.Join(", ", assignments)} }}"
            : $"new {targetType} {{ {string.Join(", ", assignments)} }}";
    }

    private static IndentedStringBuilder CreateFileBuilder()
    {
        var builder = new IndentedStringBuilder();
        builder.AppendLine(CodeTemplateContents.AutoGeneratedHeader);
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CS1591");
        builder.AppendLine("#pragma warning disable CS8600");
        builder.AppendLine("#pragma warning disable CS8601");
        builder.AppendLine("#pragma warning disable CS8602");
        builder.AppendLine("#pragma warning disable CS8603");
        builder.AppendLine("#pragma warning disable CS8604");
        builder.AppendLine("#pragma warning disable CS8618");
        return builder;
    }

    private static string GetAccessor(LinqraftConfiguration configuration, bool isRecord)
    {
        return configuration.PropertyAccessor switch
        {
            LinqraftPropertyAccessor.GetAndSet => "get; set;",
            LinqraftPropertyAccessor.GetAndInit => "get; init;",
            LinqraftPropertyAccessor.GetAndInternalSet => "get; internal set;",
            _ => isRecord ? "get; init;" : "get; set;",
        };
    }

    private static void WriteDocumentation(
        IndentedStringBuilder builder,
        Linqraft.Core.Documentation.DocumentationInfo? documentation,
        LinqraftCommentOutput outputMode
    )
    {
        if (documentation is null || outputMode == LinqraftCommentOutput.None)
        {
            return;
        }

        if (!string.IsNullOrWhiteSpace(documentation.Summary))
        {
            builder.AppendLine("/// <summary>");
            foreach (var line in documentation.Summary.Split('\n'))
            {
                builder.AppendLine($"/// {line.Trim()}");
            }

            builder.AppendLine("/// </summary>");
        }

        if (outputMode == LinqraftCommentOutput.All && !string.IsNullOrWhiteSpace(documentation.Remarks))
        {
            builder.AppendLine("/// <remarks>");
            foreach (var line in documentation.Remarks.Split('\n'))
            {
                builder.AppendLine($"/// {line.Trim()}");
            }

            builder.AppendLine("/// </remarks>");
        }
    }

    private static void WriteNamespaceAndContainingTypesStart(
        IndentedStringBuilder builder,
        string namespaceName,
        IReadOnlyList<ContainingTypeInfo> containingTypes
    )
    {
        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            builder.AppendLine($"namespace {namespaceName}");
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }

        foreach (var containingType in containingTypes)
        {
            builder.AppendLine(
                $"{containingType.AccessibilityKeyword} partial {containingType.DeclarationKeyword} {containingType.Name}"
            );
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }
    }

    private static void WriteNamespaceAndContainingTypesEnd(
        IndentedStringBuilder builder,
        string namespaceName,
        IReadOnlyList<ContainingTypeInfo> containingTypes
    )
    {
        for (var index = containingTypes.Count - 1; index >= 0; index--)
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }
    }

    private static string EscapeStringLiteral(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
