using System;
using System.Collections.Generic;
using System.Linq;
using Linqraft.Core.Configuration;
using Linqraft.Core.Formatting;
using Linqraft.Core.Generation;
using Linqraft.Core.Utilities;

namespace Linqraft.SourceGenerator;

internal static class SourceWriters
{
    public static string WriteProjectionUnit(ProjectionRequest request)
    {
        var builder = CreateFileBuilder();
        WriteInterceptorDeclaration(builder, request);
        return FinalizeSource(builder);
    }

    public static string WriteMappingUnit(MappingRequest request)
    {
        var builder = CreateFileBuilder();
        WriteMappingDeclaration(builder, request);
        return FinalizeSource(builder);
    }

    public static string WriteOwnedUnit(
        OwnedGeneratedSourceModel source,
        IReadOnlyList<GeneratedDtoModel> dtos,
        LinqraftConfiguration configuration
    )
    {
        var builder = CreateFileBuilder();
        switch (source)
        {
            case ProjectionOwnedGeneratedSourceModel projection:
                WriteInterceptorDeclaration(builder, projection.Request);
                break;
            case ObjectGenerationOwnedGeneratedSourceModel generation:
                WriteObjectGenerationDeclaration(builder, generation.Request);
                break;
            case MappingOwnedGeneratedSourceModel mapping:
                WriteMappingDeclaration(builder, mapping.Request);
                break;
            default:
                throw new InvalidOperationException(
                    $"Unsupported generated source type '{source.GetType().Name}'."
                );
        }

        WriteDtoDeclarations(builder, dtos, configuration);
        return FinalizeSource(builder);
    }

    public static string WriteDtoUnit(GeneratedDtoModel dto, LinqraftConfiguration configuration)
    {
        var builder = CreateFileBuilder();
        WriteDtoDeclaration(builder, dto, configuration);
        return FinalizeSource(builder);
    }

    public static string WriteGlobalUsingsUnit()
    {
        var builder = new IndentedStringBuilder();
        builder.AppendLines(
            $$"""
            {{CodeTemplateContents.AutoGeneratedHeader}}
            #nullable enable
            #pragma warning disable CS1591
            global using Linqraft;
            """
        );
        return FinalizeSource(builder);
    }

    private static void WriteDtoDeclarations(
        IndentedStringBuilder builder,
        IReadOnlyList<GeneratedDtoModel> dtos,
        LinqraftConfiguration configuration
    )
    {
        foreach (var dto in dtos)
        {
            builder.AppendLine();
            WriteDtoDeclaration(builder, dto, configuration);
        }
    }

    private static void WriteDtoDeclaration(
        IndentedStringBuilder builder,
        GeneratedDtoModel dto,
        LinqraftConfiguration configuration
    )
    {
        WriteNamespaceAndContainingTypesStart(builder, dto.Namespace, dto.ContainingTypes);

        if (dto.IsAutoGeneratedNested)
        {
            builder.AppendLine(CodeTemplateContents.EditorBrowsableNeverAttribute);
            builder.AppendLine("[global::Linqraft.LinqraftAutoGeneratedDtoAttribute]");
        }

        WriteDocumentation(builder, dto.Documentation, configuration.CommentOutput);

        var declarationKeyword = dto.IsRecord ? "record" : "class";
        var suppressedProperties = dto.Properties.Where(property => property.IsSuppressed).ToList();
        builder.AppendLine($"{dto.AccessibilityKeyword} partial {declarationKeyword} {dto.Name}");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            if (suppressedProperties.Count != 0)
            {
                builder.AppendLine(
                    $"{dto.AccessibilityKeyword} {dto.Name}({string.Join(", ", suppressedProperties.Select(property => $"{property.TypeName} {ToParameterName(property.Name)}"))})"
                );
                builder.AppendLine("{");
                using (builder.Indent())
                {
                    foreach (var property in suppressedProperties)
                    {
                        builder.AppendLine($"{property.Name} = {ToParameterName(property.Name)};");
                    }
                }

                builder.AppendLine("}");
                builder.AppendLine();
            }

            foreach (var property in dto.Properties.Where(property => !property.IsSuppressed))
            {
                WriteDocumentation(builder, property.Documentation, configuration.CommentOutput);
                var required = configuration.HasRequired ? "required " : string.Empty;
                builder.AppendLine(
                    $"public {required}{property.TypeName} {property.Name} {{ {GetAccessor(configuration, dto.IsRecord)} }}"
                );
            }
        }

        builder.AppendLine("}");
        WriteNamespaceAndContainingTypesEnd(builder, dto.Namespace, dto.ContainingTypes);
    }

    private static void WriteInterceptorDeclaration(
        IndentedStringBuilder builder,
        ProjectionRequest request
    )
    {
        builder.AppendLine("namespace Linqraft");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            builder.AppendLine(
                $"internal static partial class {GetProjectionSupportClassName(request.OperationKind)}"
            );
            builder.AppendLine("{");
            using (builder.Indent())
            {
                var expressionFieldName = $"s_expression_{request.MethodName}";
                var lambda = ProjectionBodyEmitter.AppendValueInline(
                    $"{request.SelectorParameterName} => ",
                    request.ProjectionBodyText
                );
                if (
                    request.CanUsePrebuiltExpression
                    && request.OperationKind == ProjectionOperationKind.Select
                    && request.ReceiverKind == ReceiverKind.IQueryable
                )
                {
                    AppendMultilineLine(
                        builder,
                        $"private static readonly global::System.Linq.Expressions.Expression<global::System.Func<{request.SourceTypeName}, {request.ResultTypeName}>> {expressionFieldName} = {lambda};"
                    );
                    builder.AppendLine();
                }

                var receiverType = GetReceiverTypeName(request.ReceiverKind);
                var selectorResultType = GetSelectorResultType(request);
                var captureParameter =
                    request.CaptureTransportKind == CaptureTransportKind.Delegate
                        ? "global::System.Func<object> capture"
                        : "object capture";
                var signature = request.OperationKind switch
                {
                    ProjectionOperationKind.Select => request.Captures.Length == 0
                        ? $"public static {receiverType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, {selectorResultType}> selector) where TIn : class"
                        : $"public static {receiverType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, {selectorResultType}> selector, {captureParameter}) where TIn : class",
                    ProjectionOperationKind.SelectMany => request.Captures.Length == 0
                        ? $"public static {receiverType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, {selectorResultType}> selector) where TIn : class"
                        : $"public static {receiverType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, {selectorResultType}> selector, {captureParameter}) where TIn : class",
                    ProjectionOperationKind.GroupBy => request.Captures.Length == 0
                        ? $"public static {receiverType}<TResult> {request.MethodName}<TIn, TKey, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, TKey> keySelector, global::System.Func<global::System.Linq.IGrouping<TKey, TIn>, {selectorResultType}> selector) where TIn : class"
                        : $"public static {receiverType}<TResult> {request.MethodName}<TIn, TKey, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, TKey> keySelector, global::System.Func<global::System.Linq.IGrouping<TKey, TIn>, {selectorResultType}> selector, {captureParameter}) where TIn : class",
                    _ => throw new InvalidOperationException(
                        $"Unsupported projection operation '{request.OperationKind}'."
                    ),
                };
                if (
                    request.InterceptableLocationVersion is { } interceptableLocationVersion
                    && request.InterceptableLocationData is { } interceptableLocationData
                )
                {
                    builder.AppendLine(
                        $"[global::System.Runtime.CompilerServices.InterceptsLocationAttribute({interceptableLocationVersion}, \"{EscapeStringLiteral(interceptableLocationData)}\")]"
                    );
                }
                if (
                    request.Captures.Length != 0
                    && request.CaptureTransportKind == CaptureTransportKind.AnonymousObject
                )
                {
                    builder.AppendLine(
                        "[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2075\", Justification = \"Capture reflection inspects runtime-generated anonymous objects.\")]"
                    );
                }

                builder.AppendLine(signature);
                builder.AppendLine("{");
                using (builder.Indent())
                {
                    var matchedQueryType = $"{receiverType}<{request.SourceTypeName}>";

                    if (request.Captures.Length != 0)
                    {
                        WriteCaptureExtraction(
                            builder,
                            request.Captures,
                            request.CaptureTransportKind,
                            request.CaptureTransportTypeName
                        );
                    }

                    var selectArgument =
                        request.CanUsePrebuiltExpression
                        && request.OperationKind == ProjectionOperationKind.Select
                        && request.ReceiverKind == ReceiverKind.IQueryable
                            ? expressionFieldName
                            : lambda;
                    var convertedInvocation = request.OperationKind switch
                    {
                        ProjectionOperationKind.Select =>
                            $"(({matchedQueryType})(object)query).Select({selectArgument})",
                        ProjectionOperationKind.SelectMany =>
                            $"(({matchedQueryType})(object)query).SelectMany({lambda})",
                        ProjectionOperationKind.GroupBy =>
                            $"(({matchedQueryType})(object)query).GroupBy({ProjectionBodyEmitter.AppendValueInline($"{request.KeySelectorParameterName} => ", request.KeySelectorBodyText ?? "default!")}).Select({lambda})",
                        _ => throw new InvalidOperationException(
                            $"Unsupported projection operation '{request.OperationKind}'."
                        ),
                    };
                    AppendMultilineLine(builder, $"var converted = {convertedInvocation};");
                    builder.AppendLine($"return ({receiverType}<TResult>)(object)converted;");
                }

                builder.AppendLine("}");
            }

            builder.AppendLine("}");
        }

        builder.AppendLine("}");
    }

    private static void WriteObjectGenerationDeclaration(
        IndentedStringBuilder builder,
        ObjectGenerationRequest request
    )
    {
        builder.AppendLine("namespace Linqraft");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            builder.AppendLine("internal static partial class LinqraftKit");
            builder.AppendLine("{");
            using (builder.Indent())
            {
                if (
                    request.InterceptableLocationVersion is { } interceptableLocationVersion
                    && request.InterceptableLocationData is { } interceptableLocationData
                )
                {
                    builder.AppendLine(
                        $"[global::System.Runtime.CompilerServices.InterceptsLocationAttribute({interceptableLocationVersion}, \"{EscapeStringLiteral(interceptableLocationData)}\")]"
                    );
                }

                if (
                    request.Captures.Length != 0
                    && request.CaptureTransportKind == CaptureTransportKind.AnonymousObject
                )
                {
                    builder.AppendLine(
                        "[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2075\", Justification = \"Capture reflection inspects runtime-generated anonymous objects.\")]"
                    );
                }

                builder.AppendLine(
                    request.Captures.Length == 0
                        ? $"internal static T {request.MethodName}<T>(object x)"
                    : request.CaptureTransportKind == CaptureTransportKind.Delegate
                        ? $"internal static T {request.MethodName}<T>(object x, global::System.Func<object> capture)"
                    : $"internal static T {request.MethodName}<T>(object x, object capture)"
                );
                builder.AppendLine("{");
                using (builder.Indent())
                {
                    if (request.Captures.Length != 0)
                    {
                        WriteCaptureExtraction(
                            builder,
                            request.Captures,
                            request.CaptureTransportKind,
                            request.CaptureTransportTypeName
                        );
                    }

                    AppendMultilineLine(
                        builder,
                        $"return (T)(object){request.ProjectionBodyText};"
                    );
                }

                builder.AppendLine("}");
            }

            builder.AppendLine("}");
        }

        builder.AppendLine("}");
    }

    private static void WriteMappingDeclaration(
        IndentedStringBuilder builder,
        MappingRequest request
    )
    {
        if (!string.IsNullOrWhiteSpace(request.Namespace))
        {
            builder.AppendLine($"namespace {request.Namespace}");
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }

        builder.AppendLine(
            $"{request.AccessibilityKeyword} static partial class {request.ContainingTypeName}"
        );
        builder.AppendLine("{");
        using (builder.Indent())
        {
            var receiverType = GetReceiverTypeName(request.ReceiverKind);
            var lambda = ProjectionBodyEmitter.AppendValueInline(
                $"{request.SelectorParameterName} => ",
                request.ProjectionBodyText
            );
            var expressionFieldName = $"s_expression_{request.MethodName}";
            if (request.CanUsePrebuiltExpression && request.ReceiverKind == ReceiverKind.IQueryable)
            {
                AppendMultilineLine(
                    builder,
                    $"private static readonly global::System.Linq.Expressions.Expression<global::System.Func<{request.SourceTypeName}, {request.ResultTypeName}>> {expressionFieldName} = {lambda};"
                );
                builder.AppendLine();
            }

            builder.AppendLine(
                $"{request.MethodAccessibilityKeyword} static {receiverType}<{request.ResultTypeName}> {request.MethodName}(this {receiverType}<{request.SourceTypeName}> source{string.Concat(request.Captures.Select(capture => $", {capture.TypeName} {capture.PropertyName}"))})"
            );
            builder.AppendLine("{");
            using (builder.Indent())
            {
                foreach (
                    var capture in request.Captures.Where(capture =>
                        capture.LocalName != capture.PropertyName
                    )
                )
                {
                    builder.AppendLine($"var {capture.LocalName} = {capture.PropertyName};");
                }

                if (
                    request.CanUsePrebuiltExpression
                    && request.ReceiverKind == ReceiverKind.IQueryable
                )
                {
                    builder.AppendLine($"return source.Select({expressionFieldName});");
                }
                else
                {
                    AppendMultilineLine(builder, $"return source.Select({lambda});");
                }
            }

            builder.AppendLine("}");
        }

        builder.AppendLine("}");

        if (!string.IsNullOrWhiteSpace(request.Namespace))
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }
    }

    private static IndentedStringBuilder CreateFileBuilder()
    {
        var builder = new IndentedStringBuilder();
        builder.AppendLines(
            $$"""
            {{CodeTemplateContents.AutoGeneratedHeader}}
            #nullable enable
            #pragma warning disable CS1591
            #pragma warning disable CS8600
            #pragma warning disable CS8601
            #pragma warning disable CS8602
            #pragma warning disable CS8603
            #pragma warning disable CS8604
            #pragma warning disable CS8618
            using System.Linq;
            """
        );
        return builder;
    }

    private static string FinalizeSource(IndentedStringBuilder builder)
    {
        return GeneratedSourceFormatter.FormatGeneratedSource(builder.ToString());
    }

    private static string GetSelectorResultType(ProjectionRequest request)
    {
        if (request.UseObjectSelectorSignature)
        {
            return "object";
        }

        return request.OperationKind == ProjectionOperationKind.SelectMany
            ? "global::System.Collections.Generic.IEnumerable<TResult>"
            : "TResult";
    }

    private static string GetProjectionSupportClassName(ProjectionOperationKind operationKind)
    {
        return operationKind switch
        {
            ProjectionOperationKind.Select => "SelectExprExtensions",
            ProjectionOperationKind.SelectMany => "SelectManyExprExtensions",
            ProjectionOperationKind.GroupBy => "GroupByExprExtensions",
            _ => throw new InvalidOperationException(
                $"Unsupported projection operation '{operationKind}'."
            ),
        };
    }

    private static string GetReceiverTypeName(ReceiverKind receiverKind)
    {
        return receiverKind == ReceiverKind.IQueryable
            ? "global::System.Linq.IQueryable"
            : "global::System.Collections.Generic.IEnumerable";
    }

    private static void WriteCaptureExtraction(
        IndentedStringBuilder builder,
        IEnumerable<CaptureParameterModel> captures,
        CaptureTransportKind transportKind,
        string? transportTypeName
    )
    {
        if (transportKind == CaptureTransportKind.Delegate)
        {
            WriteDelegateCaptureExtraction(builder, captures, transportTypeName);
            return;
        }

        builder.AppendLine("var captureType = capture.GetType();");
        foreach (var capture in captures)
        {
            builder.AppendLine(
                $"var {capture.LocalName}Property = captureType.GetProperty(\"{EscapeStringLiteral(capture.PropertyName)}\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public);"
            );
            builder.AppendLine($"if ({capture.LocalName}Property is null)");
            builder.AppendLine("{");
            using (builder.Indent())
            {
                builder.AppendLine(
                    $"throw new global::System.InvalidOperationException(\"Captured value '{EscapeStringLiteral(capture.PropertyName)}' was not found.\");"
                );
            }

            builder.AppendLine("}");
            builder.AppendLine(
                $"var {capture.LocalName}Value = {capture.LocalName}Property.GetValue(capture);"
            );
            builder.AppendLine(
                $"var {capture.LocalName} = {capture.LocalName}Value is null ? default! : ({capture.TypeName}){capture.LocalName}Value;"
            );
        }
    }

    private static void WriteDelegateCaptureExtraction(
        IndentedStringBuilder builder,
        IEnumerable<CaptureParameterModel> captures,
        string? transportTypeName
    )
    {
        if (string.IsNullOrWhiteSpace(transportTypeName))
        {
            throw new InvalidOperationException("Delegate captures require a transport type.");
        }

        var captureArray = captures.ToArray();
        builder.AppendLine("var captureValueBoxed = capture();");
        builder.AppendLine(
            $"var captureValue = captureValueBoxed is null ? default! : ({transportTypeName})captureValueBoxed;"
        );
        foreach (var capture in captureArray)
        {
            var valueExpression = capture.ValueAccessor is null
                ? "captureValue"
                : $"captureValue.{capture.ValueAccessor}";
            builder.AppendLine($"var {capture.LocalName} = {valueExpression};");
        }
    }

    private static string GetAccessor(LinqraftConfiguration configuration, bool isRecord)
    {
        return configuration.PropertyAccessor switch
        {
            LinqraftPropertyAccessor.GetAndSet => "get; set;",
            LinqraftPropertyAccessor.GetAndInit => "get; init;",
            LinqraftPropertyAccessor.GetAndInternalSet => "get; internal set;",
            _ => isRecord ? "get; init;" : "get; set;",
        };
    }

    private static void WriteDocumentation(
        IndentedStringBuilder builder,
        Linqraft.Core.Documentation.DocumentationInfo? documentation,
        LinqraftCommentOutput outputMode
    )
    {
        if (documentation is null || outputMode == LinqraftCommentOutput.None)
        {
            return;
        }

        if (!string.IsNullOrWhiteSpace(documentation.Summary))
        {
            var summary = documentation.Summary!;
            builder.AppendLine("/// <summary>");
            foreach (var line in summary.Split('\n'))
            {
                builder.AppendLine($"/// {line.Trim()}");
            }

            builder.AppendLine("/// </summary>");
        }

        if (
            outputMode == LinqraftCommentOutput.All
            && !string.IsNullOrWhiteSpace(documentation.Remarks)
        )
        {
            var remarks = documentation.Remarks!;
            builder.AppendLine("/// <remarks>");
            foreach (var line in remarks.Split('\n'))
            {
                builder.AppendLine($"/// {line.Trim()}");
            }

            builder.AppendLine("/// </remarks>");
        }
    }

    private static void WriteNamespaceAndContainingTypesStart(
        IndentedStringBuilder builder,
        string namespaceName,
        Linqraft.Core.Collections.EquatableArray<ContainingTypeInfo> containingTypes
    )
    {
        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            builder.AppendLine($"namespace {namespaceName}");
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }

        foreach (var containingType in containingTypes)
        {
            builder.AppendLine(
                $"{containingType.AccessibilityKeyword} partial {containingType.DeclarationKeyword} {containingType.Name}"
            );
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }
    }

    private static void WriteNamespaceAndContainingTypesEnd(
        IndentedStringBuilder builder,
        string namespaceName,
        Linqraft.Core.Collections.EquatableArray<ContainingTypeInfo> containingTypes
    )
    {
        for (var index = containingTypes.Length - 1; index >= 0; index--)
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }
    }

    private static string EscapeStringLiteral(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static void AppendMultilineLine(IndentedStringBuilder builder, string value)
    {
        foreach (var line in SplitLines(value))
        {
            builder.AppendLine(line);
        }
    }

    private static string[] SplitLines(string value)
    {
        return value.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n');
    }

    private static string ToParameterName(string propertyName)
    {
        return string.IsNullOrEmpty(propertyName)
            ? "value"
            : char.ToLowerInvariant(propertyName[0]) + propertyName[1..];
    }
}
