using System.Collections.Generic;
using System.Linq;
using Linqraft.Core.Configuration;
using Linqraft.Core.Formatting;
using Linqraft.Core.Generation;
using Linqraft.Core.Utilities;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Linqraft.SourceGenerator;

internal static class SourceWriters
{
    public static string WriteProjectionUnit(
        ProjectionRequest request,
        IReadOnlyCollection<GeneratedDtoModel> ownedDtos,
        SemanticModel semanticModel,
        LinqraftConfiguration configuration
    )
    {
        var builder = CreateFileBuilder();
        WriteOwnedDtos(builder, ownedDtos, configuration);
        if (ownedDtos.Count != 0)
        {
            builder.AppendLine();
        }

        WriteInterceptorDeclaration(builder, request, semanticModel);
        return FinalizeSource(builder);
    }

    public static string WriteMappingUnit(
        MappingRequest request,
        IReadOnlyCollection<GeneratedDtoModel> ownedDtos,
        SemanticModel semanticModel,
        LinqraftConfiguration configuration
    )
    {
        var builder = CreateFileBuilder();
        WriteOwnedDtos(builder, ownedDtos, configuration);
        if (ownedDtos.Count != 0)
        {
            builder.AppendLine();
        }

        WriteMappingDeclaration(builder, request, semanticModel);
        return FinalizeSource(builder);
    }

    public static string WriteDtoUnit(GeneratedDtoModel dto, LinqraftConfiguration configuration)
    {
        var builder = CreateFileBuilder();
        WriteDtoDeclaration(builder, dto, configuration);
        return FinalizeSource(builder);
    }

    private static void WriteOwnedDtos(
        IndentedStringBuilder builder,
        IReadOnlyCollection<GeneratedDtoModel> ownedDtos,
        LinqraftConfiguration configuration
    )
    {
        foreach (
            var dto in ownedDtos
                .OrderByDescending(model => model.IsRoot)
                .ThenBy(model => model.Namespace, System.StringComparer.Ordinal)
                .ThenBy(model => model.FullyQualifiedName, System.StringComparer.Ordinal)
        )
        {
            WriteDtoDeclaration(builder, dto, configuration);
            builder.AppendLine();
        }
    }

    private static void WriteDtoDeclaration(
        IndentedStringBuilder builder,
        GeneratedDtoModel dto,
        LinqraftConfiguration configuration
    )
    {
        WriteNamespaceAndContainingTypesStart(builder, dto.Namespace, dto.ContainingTypes);

        if (dto.IsAutoGeneratedNested)
        {
            builder.AppendLine(CodeTemplateContents.EditorBrowsableNeverAttribute);
            builder.AppendLine("[global::Linqraft.LinqraftAutoGeneratedDtoAttribute]");
        }

        WriteDocumentation(builder, dto.Documentation, configuration.CommentOutput);

        var declarationKeyword = dto.IsRecord ? "record" : "class";
        var suppressedProperties = dto.Properties.Where(property => property.IsSuppressed).ToList();
        builder.AppendLine($"{dto.AccessibilityKeyword} partial {declarationKeyword} {dto.Name}");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            if (suppressedProperties.Count != 0)
            {
                builder.AppendLine(
                    $"{dto.AccessibilityKeyword} {dto.Name}({string.Join(", ", suppressedProperties.Select(property => $"{property.TypeName} {ToParameterName(property.Name)}"))})"
                );
                builder.AppendLine("{");
                using (builder.Indent())
                {
                    foreach (var property in suppressedProperties)
                    {
                        builder.AppendLine($"{property.Name} = {ToParameterName(property.Name)};");
                    }
                }

                builder.AppendLine("}");
                builder.AppendLine();
            }

            foreach (var property in dto.Properties.Where(property => !property.IsSuppressed))
            {
                WriteDocumentation(builder, property.Documentation, configuration.CommentOutput);
                var required = configuration.HasRequired ? "required " : string.Empty;
                builder.AppendLine(
                    $"public {required}{property.TypeName} {property.Name} {{ {GetAccessor(configuration, dto.IsRecord)} }}"
                );
            }
        }

        builder.AppendLine("}");
        WriteNamespaceAndContainingTypesEnd(builder, dto.Namespace, dto.ContainingTypes);
    }

    private static void WriteInterceptorDeclaration(
        IndentedStringBuilder builder,
        ProjectionRequest request,
        SemanticModel semanticModel
    )
    {
        builder.AppendLine("namespace Linqraft");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            builder.AppendLine("file static partial class GeneratedExpression");
            builder.AppendLine("{");
            using (builder.Indent())
            {
                var expressionFieldName = $"s_expression_{request.MethodName}";
                var lambda = WriteProjectionLambda(request.RootProjection, request, semanticModel, request.Captures);
                if (request.CanUsePrebuiltExpression && request.ReceiverKind == ReceiverKind.IQueryable)
                {
                    AppendMultilineLine(
                        builder,
                        $"private static readonly global::System.Linq.Expressions.Expression<global::System.Func<{request.SourceTypeName}, {request.ResultTypeName}>> {expressionFieldName} = {lambda};"
                    );
                    builder.AppendLine();
                }

                var receiverType = GetReceiverTypeName(request.ReceiverKind);
                var selectorResultType = request.UseObjectSelectorSignature ? "object" : "TResult";
                var captureParameter =
                    "[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties)] object capture";
                var signature = request.Captures.Count == 0
                    ? $"public static {receiverType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, {selectorResultType}> selector) where TIn : class"
                    : $"public static {receiverType}<TResult> {request.MethodName}<TIn, TResult>(this {receiverType}<TIn> query, global::System.Func<TIn, {selectorResultType}> selector, {captureParameter}) where TIn : class";
                if (request.InterceptableLocation is not null)
                {
                    builder.AppendLine(
                        $"[global::System.Runtime.CompilerServices.InterceptsLocationAttribute({request.InterceptableLocation.Version}, \"{EscapeStringLiteral(request.InterceptableLocation.Data)}\")]"
                    );
                }

                builder.AppendLine(signature);
                builder.AppendLine("{");
                using (builder.Indent())
                {
                    var matchedQueryType = $"{receiverType}<{request.SourceTypeName}>";
                    builder.AppendLine("global::System.ArgumentNullException.ThrowIfNull(query);");
                    builder.AppendLine("global::System.ArgumentNullException.ThrowIfNull(selector);");
                    if (request.Captures.Count != 0)
                    {
                        builder.AppendLine("global::System.ArgumentNullException.ThrowIfNull(capture);");
                    }

                    builder.AppendLine($"var matchedQuery = query as object as {matchedQueryType};");
                    builder.AppendLine("if (matchedQuery is null)");
                    builder.AppendLine("{");
                    using (builder.Indent())
                    {
                        builder.AppendLine(
                            $"throw new global::System.InvalidOperationException(\"Linqraft generated projection expected a source assignable to '{EscapeStringLiteral(request.SourceTypeName)}'.\");"
                        );
                    }

                    builder.AppendLine("}");

                    if (request.Captures.Count != 0)
                    {
                        builder.AppendLine();
                        builder.AppendLine("var captureType = capture.GetType();");
                        foreach (var capture in request.Captures)
                        {
                            builder.AppendLine(
                                $"var {capture.LocalName}Property = captureType.GetProperty(\"{EscapeStringLiteral(capture.PropertyName)}\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public);"
                            );
                            builder.AppendLine($"if ({capture.LocalName}Property is null)");
                            builder.AppendLine("{");
                            using (builder.Indent())
                            {
                                builder.AppendLine(
                                    $"throw new global::System.InvalidOperationException(\"Captured value '{EscapeStringLiteral(capture.PropertyName)}' was not found.\");"
                                );
                            }

                            builder.AppendLine("}");
                            builder.AppendLine(
                                $"var {capture.LocalName}Value = {capture.LocalName}Property.GetValue(capture);"
                            );
                            builder.AppendLine(
                                $"var {capture.LocalName} = {capture.LocalName}Value is null ? default! : ({capture.TypeName}){capture.LocalName}Value;"
                            );
                        }
                    }

                    builder.AppendLine();
                    var selectArgument = request.CanUsePrebuiltExpression && request.ReceiverKind == ReceiverKind.IQueryable
                        ? expressionFieldName
                        : lambda;
                    AppendMultilineLine(builder, $"var converted = matchedQuery.Select({selectArgument});");
                    builder.AppendLine(
                        $"return converted as object as {receiverType}<TResult> ?? throw new global::System.InvalidOperationException(\"Linqraft generated projection returned an unexpected result type.\");"
                    );
                }

                builder.AppendLine("}");
            }

            builder.AppendLine("}");
        }

        builder.AppendLine("}");
    }

    private static void WriteMappingDeclaration(
        IndentedStringBuilder builder,
        MappingRequest request,
        SemanticModel semanticModel
    )
    {
        if (!string.IsNullOrWhiteSpace(request.Namespace))
        {
            builder.AppendLine($"namespace {request.Namespace}");
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }

        builder.AppendLine($"{request.AccessibilityKeyword} static partial class {request.ContainingTypeName}");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            var receiverType = GetReceiverTypeName(request.ReceiverKind);
            var lambda = WriteProjectionLambda(request.RootProjection, request, semanticModel);
            var expressionFieldName = $"s_expression_{request.MethodName}";
            if (request.CanUsePrebuiltExpression && request.ReceiverKind == ReceiverKind.IQueryable)
            {
                AppendMultilineLine(
                    builder,
                    $"private static readonly global::System.Linq.Expressions.Expression<global::System.Func<{request.SourceTypeName}, {request.ResultTypeName}>> {expressionFieldName} = {lambda};"
                );
                builder.AppendLine();
            }

            builder.AppendLine(
                $"{request.MethodAccessibilityKeyword} static {receiverType}<{request.ResultTypeName}> {request.MethodName}(this {receiverType}<{request.SourceTypeName}> source)"
            );
            builder.AppendLine("{");
            using (builder.Indent())
            {
                if (request.CanUsePrebuiltExpression && request.ReceiverKind == ReceiverKind.IQueryable)
                {
                    builder.AppendLine($"return source.Select({expressionFieldName});");
                }
                else
                {
                    AppendMultilineLine(builder, $"return source.Select({lambda});");
                }
            }

            builder.AppendLine("}");
        }

        builder.AppendLine("}");

        if (!string.IsNullOrWhiteSpace(request.Namespace))
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }
    }

    private static string WriteProjectionLambda(
        ProjectionObjectModel projection,
        ProjectionRequest request,
        SemanticModel semanticModel,
        IReadOnlyList<CaptureEntryModel> captures
    )
    {
        return AppendValueInline(
            $"{request.SelectorParameterName} => ",
            WriteProjectionBody(projection, request.Pattern, request.ResultTypeName, semanticModel, captures)
        );
    }

    private static string WriteProjectionLambda(
        ProjectionObjectModel projection,
        MappingRequest request,
        SemanticModel semanticModel
    )
    {
        return AppendValueInline(
            $"{request.SelectorParameterName} => ",
            WriteProjectionBody(
                projection,
                ProjectionPattern.ExplicitDto,
                request.ResultTypeName,
                semanticModel,
                request.Captures
            )
        );
    }

    private static string WriteProjectionBody(
        ProjectionObjectModel projection,
        ProjectionPattern pattern,
        string resultTypeName,
        SemanticModel semanticModel,
        IReadOnlyList<CaptureEntryModel> captures
    )
    {
        var kind = pattern == ProjectionPattern.Anonymous ? "anonymous" : "named";
        var targetType = pattern == ProjectionPattern.Anonymous ? null : resultTypeName;
        var constructorArguments = projection.Members
            .Where(member => member.IsSuppressed)
            .Select(
                member =>
                {
                    var emitter = new ProjectionExpressionEmitter(
                        semanticModel,
                        member.Expression,
                        member.TypeName,
                        member.UseEmptyCollectionFallback,
                        member.ReplacementTypes,
                        captures
                    );
                    return AppendValueWithContinuation(
                        $"{ToParameterName(member.Name)}: ",
                        emitter.Emit(member.Expression)
                    );
                }
            )
            .ToList();
        var assignments = projection.Members
            .Where(member => !member.IsSuppressed)
            .Select(
                member =>
                {
                    var emitter = new ProjectionExpressionEmitter(
                        semanticModel,
                        member.Expression,
                        member.TypeName,
                        member.UseEmptyCollectionFallback,
                        member.ReplacementTypes,
                        captures
                    );
                    return AppendValueWithContinuation(
                        $"{member.Name} = ",
                        emitter.Emit(member.Expression)
                    );
                }
            )
            .ToList();

        return kind == "anonymous"
            ? BuildInitializerExpression("new", assignments)
            : WriteNamedProjection(targetType!, constructorArguments, assignments);
    }

    private static IndentedStringBuilder CreateFileBuilder()
    {
        var builder = new IndentedStringBuilder();
        builder.AppendLines(
            $$"""
            {{CodeTemplateContents.AutoGeneratedHeader}}
            #nullable enable
            #pragma warning disable CS1591
            #pragma warning disable CS8600
            #pragma warning disable CS8601
            #pragma warning disable CS8602
            #pragma warning disable CS8603
            #pragma warning disable CS8604
            #pragma warning disable CS8618
            using System.Linq;
            """
        );
        return builder;
    }

    private static string FinalizeSource(IndentedStringBuilder builder)
    {
        return GeneratedSourceFormatter.FormatGeneratedSource(builder.ToString());
    }

    private static string GetReceiverTypeName(ReceiverKind receiverKind)
    {
        return receiverKind == ReceiverKind.IQueryable
            ? "global::System.Linq.IQueryable"
            : "global::System.Collections.Generic.IEnumerable";
    }

    private static string GetAccessor(LinqraftConfiguration configuration, bool isRecord)
    {
        return configuration.PropertyAccessor switch
        {
            LinqraftPropertyAccessor.GetAndSet => "get; set;",
            LinqraftPropertyAccessor.GetAndInit => "get; init;",
            LinqraftPropertyAccessor.GetAndInternalSet => "get; internal set;",
            _ => isRecord ? "get; init;" : "get; set;",
        };
    }

    private static void WriteDocumentation(
        IndentedStringBuilder builder,
        Linqraft.Core.Documentation.DocumentationInfo? documentation,
        LinqraftCommentOutput outputMode
    )
    {
        if (documentation is null || outputMode == LinqraftCommentOutput.None)
        {
            return;
        }

        if (!string.IsNullOrWhiteSpace(documentation.Summary))
        {
            var summary = documentation.Summary!;
            builder.AppendLine("/// <summary>");
            foreach (var line in summary.Split('\n'))
            {
                builder.AppendLine($"/// {line.Trim()}");
            }

            builder.AppendLine("/// </summary>");
        }

        if (outputMode == LinqraftCommentOutput.All && !string.IsNullOrWhiteSpace(documentation.Remarks))
        {
            var remarks = documentation.Remarks!;
            builder.AppendLine("/// <remarks>");
            foreach (var line in remarks.Split('\n'))
            {
                builder.AppendLine($"/// {line.Trim()}");
            }

            builder.AppendLine("/// </remarks>");
        }
    }

    private static void WriteNamespaceAndContainingTypesStart(
        IndentedStringBuilder builder,
        string namespaceName,
        IReadOnlyList<ContainingTypeInfo> containingTypes
    )
    {
        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            builder.AppendLine($"namespace {namespaceName}");
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }

        foreach (var containingType in containingTypes)
        {
            builder.AppendLine(
                $"{containingType.AccessibilityKeyword} partial {containingType.DeclarationKeyword} {containingType.Name}"
            );
            builder.AppendLine("{");
            builder.IncreaseIndent();
        }
    }

    private static void WriteNamespaceAndContainingTypesEnd(
        IndentedStringBuilder builder,
        string namespaceName,
        IReadOnlyList<ContainingTypeInfo> containingTypes
    )
    {
        for (var index = containingTypes.Count - 1; index >= 0; index--)
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            builder.DecreaseIndent();
            builder.AppendLine("}");
        }
    }

    private static string EscapeStringLiteral(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string WriteNamedProjection(
        string targetType,
        IReadOnlyList<string> constructorArguments,
        IReadOnlyList<string> assignments
    )
    {
        var constructorSuffix = constructorArguments.Count == 0
            ? "()"
            : $"({string.Join(", ", constructorArguments)})";
        if (assignments.Count == 0)
        {
            return $"new {targetType}{constructorSuffix}";
        }

        return BuildInitializerExpression($"new {targetType}{constructorSuffix}", assignments);
    }

    private static string BuildInitializerExpression(string header, IReadOnlyList<string> items)
    {
        if (!ShouldExpandInitializer(items))
        {
            return items.Count == 0
                ? $"{header} {{ }}"
                : $"{header} {{ {string.Join(", ", items)} }}";
        }

        var builder = new IndentedStringBuilder();
        builder.AppendLine($"{header} {{");
        using (builder.Indent())
        {
            foreach (var item in items)
            {
                AppendMultilineItem(builder, item, ",");
            }
        }

        builder.Append("}");
        return builder.ToString();
    }

    private static void AppendMultilineLine(IndentedStringBuilder builder, string value)
    {
        foreach (var line in SplitLines(value))
        {
            builder.AppendLine(line);
        }
    }

    private static bool ShouldExpandInitializer(IReadOnlyList<string> items)
    {
        return items.Count > 1 || items.Any(ContainsLineBreak);
    }

    private static void AppendMultilineItem(IndentedStringBuilder builder, string value, string suffix)
    {
        var lines = SplitLines(value);
        for (var index = 0; index < lines.Length; index++)
        {
            var line = index == lines.Length - 1 ? lines[index] + suffix : lines[index];
            builder.AppendLine(line);
        }
    }

    private static string AppendValueWithContinuation(string prefix, string value)
    {
        var lines = SplitLines(value);
        if (lines.Length == 0)
        {
            return prefix;
        }

        if (lines.Length == 1)
        {
            return prefix + lines[0];
        }

        var formattedLines = new List<string> { prefix + lines[0] };
        formattedLines.AddRange(lines.Skip(1).Select(IndentAllLines));
        return string.Join("\n", formattedLines);
    }

    private static string AppendValueInline(string prefix, string value)
    {
        var lines = SplitLines(value);
        if (lines.Length == 0)
        {
            return prefix;
        }

        lines[0] = prefix + lines[0];
        return string.Join("\n", lines);
    }

    private static string IndentAllLines(string value, int indentLevel = 1)
    {
        var prefix = new string(' ', indentLevel * 4);
        return string.Join("\n", SplitLines(value).Select(line => prefix + line));
    }

    private static bool ContainsLineBreak(string value)
    {
        return value.IndexOf('\n') >= 0 || value.IndexOf('\r') >= 0;
    }

    private static string[] SplitLines(string value)
    {
        return value.Replace("\r\n", "\n")
            .Replace('\r', '\n')
            .Split('\n');
    }

    private static string ToParameterName(string propertyName)
    {
        return string.IsNullOrEmpty(propertyName)
            ? "value"
            : char.ToLowerInvariant(propertyName[0]) + propertyName[1..];
    }
}
