using Linqraft.Core.Configuration;
using Linqraft.Core.Formatting;
using static Linqraft.Core.Generation.CodeTemplateContents;

namespace Linqraft.SourceGenerator;

internal static class SupportSourceEmitter
{
    public static string CreateSupportSource(LinqraftGeneratorOptionsCore generatorOptions)
    {
        var builder = new IndentedStringBuilder();
        var extensionDeclarations =
            ProjectionSupportExtensionClassGenerator.CreateAllDeclarations(generatorOptions);
        builder.AppendLines(
            $$"""
            {{CreateAutoGeneratedHeader(generatorOptions.GeneratedHeaderComment)}}
            #nullable enable
            #pragma warning disable CS1591
            using System.Collections.Generic;
            using System.Linq;

            namespace {{generatorOptions.EmbeddedAttributeNamespace}}
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.All)]
                internal sealed partial class EmbeddedAttribute : global::System.Attribute
                {
                }
            }

            namespace {{generatorOptions.InterceptsLocationAttributeNamespace}}
            {
                [global::{{generatorOptions.EmbeddedAttributeNamespace}}.EmbeddedAttribute]
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
                internal sealed partial class InterceptsLocationAttribute : global::System.Attribute
                {
                    public InterceptsLocationAttribute(int version, string data)
                    {
                        Version = version;
                        Data = data;
                    }

                    public int Version { get; }

                    public string Data { get; }
                }
            }

            namespace {{generatorOptions.SupportNamespace}}
            {
                /// <summary>
                 /// Controls the accessibility of generated mapping helpers.
                 /// </summary>
                [global::{{generatorOptions.EmbeddedAttributeNamespace}}.EmbeddedAttribute]
                internal enum {{generatorOptions.MappingVisibilityEnumName}}
                {
                    Default = 0,
                    Internal = 1,
                    Public = 2,
                }

                /// <summary>
                /// Marks a mapping declaration that {{generatorOptions.GeneratorDisplayName}} should turn into a reusable projection method.
                /// </summary>
                [global::{{generatorOptions.EmbeddedAttributeNamespace}}.EmbeddedAttribute]
                [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                internal sealed partial class {{generatorOptions.MappingGenerateAttributeName}} : global::System.Attribute
                {
                    public {{generatorOptions.MappingGenerateAttributeName}}()
                    {
                    }

                    public {{generatorOptions.MappingGenerateAttributeName}}(string methodName)
                    {
                        MethodName = methodName;
                    }

                    public string? MethodName { get; }

                    public {{generatorOptions.MappingVisibilityEnumName}} Visibility { get; set; }
                }

                [global::{{generatorOptions.EmbeddedAttributeNamespace}}.EmbeddedAttribute]
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                internal sealed partial class {{generatorOptions.AutoGeneratedDtoAttributeName}} : global::System.Attribute
                {
                }

                /// <summary>
                /// Base type for reusable mapping declarations. Override <see cref="DefineMapping"/> and describe the projection with <c>{{generatorOptions.SelectExprMethodName}}</c>.
                /// </summary>
                [global::{{generatorOptions.EmbeddedAttributeNamespace}}.EmbeddedAttribute]
                internal abstract partial class {{generatorOptions.MappingDeclareClassName}}<T>
                {
                    protected IQueryable<T> Source => throw new global::System.InvalidOperationException("{{generatorOptions.GeneratorDisplayName}} source generator should replace mapping declarations before execution.");

                    protected abstract void DefineMapping();
                }

                /// <summary>
                /// Provides the object-conversion entry point that {{generatorOptions.GeneratorDisplayName}} intercepts before execution.
                /// </summary>
                [global::{{generatorOptions.EmbeddedAttributeNamespace}}.EmbeddedAttribute]
                internal static partial class {{generatorOptions.GeneratorKitClassName}}
                {
                    private static global::System.InvalidOperationException ThrowInterceptionRequired
                        => new global::System.InvalidOperationException("{{generatorOptions.GeneratorDisplayName}} source generator should replace {{generatorOptions.ObjectGenerationMethodName}} invocations before execution.");

                    /// <summary>
                    /// Generates a DTO of type <typeparamref name="T"/> by evaluating the provided anonymous object initializer.
                    /// The initializer can contain any number of projections using <c>{{generatorOptions.SelectExprMethodName}}</c> and other supported {{generatorOptions.GeneratorDisplayName}} features,
                    /// and {{generatorOptions.GeneratorDisplayName}} will combine them into a single generated DTO type.
                    /// </summary>
                    public static T {{generatorOptions.ObjectGenerationMethodName}}<T>(object x)
                        => throw ThrowInterceptionRequired;

                    /// <summary>
                    /// Generates a DTO of type <typeparamref name="T"/> by evaluating the provided anonymous object initializer
                    /// together with anonymous-object capture data.
                    /// </summary>
                    [global::System.Obsolete("Anonymous-object capture is obsolete. Use the delegate-based capture pattern instead.", false)]
                    public static T {{generatorOptions.ObjectGenerationMethodName}}<T>(object x, object capture)
                        => throw ThrowInterceptionRequired;

                    /// <summary>
                    /// Generates a DTO of type <typeparamref name="T"/> by evaluating the provided anonymous object initializer
                    /// together with NativeAOT-safe capture data returned from <paramref name="capture"/>.
                    /// </summary>
                    public static T {{generatorOptions.ObjectGenerationMethodName}}<T>(object x, global::System.Func<object> capture)
                        => throw ThrowInterceptionRequired;
                }
            }

            """
        );
        builder.AppendLine($"namespace {generatorOptions.SupportNamespace}");
        builder.AppendLine("{");
        using (builder.Indent())
        {
            builder.AppendLines(extensionDeclarations);
        }
        builder.AppendLine("}");

        return builder.ToString();
    }
}
