using static Linqraft.Core.Generation.CodeTemplateContents;

namespace Linqraft.SourceGenerator;

internal static class SupportSourceEmitter
{
    public static string CreateSupportSource()
    {
        var extensionDeclarations =
            ProjectionSupportExtensionClassGenerator.CreateAllDeclarations();
        var source = $$"""
            {{AutoGeneratedHeader}}
            #nullable enable
            #pragma warning disable CS1591
            using System.Collections.Generic;
            using System.Linq;

            namespace Microsoft.CodeAnalysis
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.All)]
                internal sealed partial class EmbeddedAttribute : global::System.Attribute
                {
                }
            }

            namespace System.Runtime.CompilerServices
            {
                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
                internal sealed partial class InterceptsLocationAttribute : global::System.Attribute
                {
                    public InterceptsLocationAttribute(int version, string data)
                    {
                        Version = version;
                        Data = data;
                    }

                    public int Version { get; }

                    public string Data { get; }
                }
            }

            namespace Linqraft
            {
                /// <summary>
                /// Controls the accessibility of generated mapping helpers.
                /// </summary>
                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                internal enum LinqraftMappingVisibility
                {
                    Default = 0,
                    Internal = 1,
                    Public = 2,
                }

                /// <summary>
                /// Marks a mapping declaration that Linqraft should turn into a reusable projection method.
                /// </summary>
                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                internal sealed partial class LinqraftMappingGenerateAttribute : global::System.Attribute
                {
                    public LinqraftMappingGenerateAttribute()
                    {
                    }

                    public LinqraftMappingGenerateAttribute(string methodName)
                    {
                        MethodName = methodName;
                    }

                    public string? MethodName { get; }

                    public LinqraftMappingVisibility Visibility { get; set; }
                }

                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                internal sealed partial class LinqraftAutoGeneratedDtoAttribute : global::System.Attribute
                {
                }

                /// <summary>
                /// Base type for reusable mapping declarations. Override <see cref="DefineMapping"/> and describe the projection with <c>SelectExpr</c>.
                /// </summary>
                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                internal abstract partial class LinqraftMappingDeclare<T>
                {
                    protected IQueryable<T> Source => throw new global::System.InvalidOperationException("Linqraft source generator should replace mapping declarations before execution.");

                    protected abstract void DefineMapping();
                }

                /// <summary>
                /// Provides the object-conversion entry point that Linqraft intercepts before execution.
                /// </summary>
                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                internal static partial class LinqraftKit
                {
                    private static global::System.InvalidOperationException ThrowInterceptionRequired
                        => new global::System.InvalidOperationException("Linqraft source generator should replace Generate invocations before execution.");

                    /// <summary>
                    /// Generates a DTO of type <typeparamref name="T"/> by evaluating the provided anonymous object initializer.
                    /// The initializer can contain any number of projections using <c>SelectExpr</c> and other supported Linqraft features,
                    /// and Linqraft will combine them into a single generated DTO type.
                    /// </summary>
                    public static T Generate<T>(object x)
                        => throw ThrowInterceptionRequired;

                    /// <summary>
                    /// Generates a DTO of type <typeparamref name="T"/> by evaluating the provided anonymous object initializer
                    /// together with anonymous-object capture data.
                    /// </summary>
                    public static T Generate<T>(object x, object capture)
                        => throw ThrowInterceptionRequired;

                    /// <summary>
                    /// Generates a DTO of type <typeparamref name="T"/> by evaluating the provided anonymous object initializer
                    /// together with NativeAOT-safe capture data returned from <paramref name="capture"/>.
                    /// </summary>
                    public static T Generate<T>(object x, global::System.Func<object> capture)
                        => throw ThrowInterceptionRequired;
                }

            }

            namespace Linqraft
            {
            {{extensionDeclarations}}
            }
            """;

        return source;
    }
}
