using static Linqraft.Core.Generation.CodeTemplateContents;

namespace Linqraft.SourceGenerator;

internal static class SupportSourceEmitter
{
    public static string CreateSupportSource()
    {
        var source = $$"""
            {{AutoGeneratedHeader}}
            #nullable enable
            #pragma warning disable CS1591
            using System.Collections;
            using System.Collections.Generic;
            using System.Linq;
            namespace Microsoft.CodeAnalysis
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.All)]
                internal sealed partial class EmbeddedAttribute : global::System.Attribute
                {
                }
            }

            namespace System.Runtime.CompilerServices
            {
                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
                internal sealed partial class InterceptsLocationAttribute : global::System.Attribute
                {
                    public InterceptsLocationAttribute(int version, string data)
                    {
                        Version = version;
                        Data = data;
                    }

                    public int Version { get; }

                    public string Data { get; }
                }
            }

            namespace Linqraft
            {
                /// <summary>
                /// Marks a mapping declaration that Linqraft should turn into a reusable projection method.
                /// </summary>
                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                internal sealed partial class LinqraftMappingGenerateAttribute : global::System.Attribute
                {
                    /// <summary>
                    /// Creates the attribute with the default generated method name.
                    /// </summary>
                    public LinqraftMappingGenerateAttribute()
                    {
                    }

                    /// <summary>
                    /// Creates the attribute with an explicit generated method name.
                    /// </summary>
                    /// <param name="methodName">The method name that should be emitted for the mapping helper.</param>
                    public LinqraftMappingGenerateAttribute(string methodName)
                    {
                        MethodName = methodName;
                    }

                    /// <summary>
                    /// Gets the generated method name when one was provided explicitly.
                    /// </summary>
                    public string? MethodName { get; }
                }

                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                internal sealed partial class LinqraftAutoGeneratedDtoAttribute : global::System.Attribute
                {
                }

                /// <summary>
                /// Base type for reusable mapping declarations. Override <see cref="DefineMapping"/> and describe the projection with <c>SelectExpr</c>.
                /// </summary>
                /// <typeparam name="T">The source element type exposed by the declaration.</typeparam>
                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                public abstract partial class LinqraftMappingDeclare<T>
                {
                    /// <summary>
                    /// Gets the placeholder queryable source used only while the source generator inspects the mapping definition.
                    /// </summary>
                    protected IQueryable<T> Source => throw new global::System.InvalidOperationException("Linqraft source generator should replace mapping declarations before execution.");

                    /// <summary>
                    /// Describes the projection that should be turned into a reusable mapping method.
                    /// </summary>
                    protected abstract void DefineMapping();
                }

            }

            namespace System.Linq
            {
                /// <summary>
                /// Provides the entry points that Linqraft intercepts when it can generate a typed projection ahead of time.
                /// </summary>
                [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                internal static partial class SelectExprExtensions
                {
                    private static InvalidOperationException ThrowInterceptionRequired
                        => new global::System.InvalidOperationException("Linqraft source generator should replace SelectExpr invocations before execution.");

                    /// <summary>
                    /// Projects an <see cref="IQueryable{T}"/> source through Linqraft. This placeholder must be intercepted by generated code before execution.
                    /// </summary>
                    public static IQueryable<TResult> SelectExpr<TIn, TResult>(this IQueryable<TIn> query, global::System.Func<TIn, TResult> selector)
                        where TIn : class => throw ThrowInterceptionRequired;

                    /// <summary>
                    /// Projects an <see cref="IQueryable{T}"/> source into a named DTO. This placeholder must be intercepted by generated code before execution.
                    /// </summary>
                    {{OverloadResolutionLowPriority}}
                    public static IQueryable<TResult> SelectExpr<TIn, TResult>(this IQueryable<TIn> query, global::System.Func<TIn, object> selector)
                        where TIn : class => throw ThrowInterceptionRequired;

                    /// <summary>
                    /// Projects an <see cref="IQueryable{T}"/> source with captured values supplied separately for generator-friendly interception.
                    /// </summary>
                    public static IQueryable<TResult> SelectExpr<TIn, TResult>(this IQueryable<TIn> query, global::System.Func<TIn, TResult> selector, {{DynamicallyAccessedPublicProperties}} object capture)
                        where TIn : class => throw ThrowInterceptionRequired;

                    /// <summary>
                    /// Projects an <see cref="IQueryable{T}"/> source into a named DTO with an explicit capture object. This placeholder must be intercepted by generated code before execution.
                    /// </summary>
                    {{OverloadResolutionLowPriority}}
                    public static IQueryable<TResult> SelectExpr<TIn, TResult>(this IQueryable<TIn> query, global::System.Func<TIn, object> selector, {{DynamicallyAccessedPublicProperties}} object capture)
                        where TIn : class => throw ThrowInterceptionRequired;

                    /// <summary>
                    /// Projects an <see cref="IEnumerable{T}"/> source through Linqraft. This placeholder must be intercepted by generated code before execution.
                    /// </summary>
                    public static IEnumerable<TResult> SelectExpr<TIn, TResult>(this IEnumerable<TIn> query, global::System.Func<TIn, TResult> selector)
                        where TIn : class => throw ThrowInterceptionRequired;

                    /// <summary>
                    /// Projects an <see cref="IEnumerable{T}"/> source into a named DTO. This placeholder must be intercepted by generated code before execution.
                    /// </summary>
                    {{OverloadResolutionLowPriority}}
                    public static IEnumerable<TResult> SelectExpr<TIn, TResult>(this IEnumerable<TIn> query, global::System.Func<TIn, object> selector)
                        where TIn : class => throw ThrowInterceptionRequired;

                    /// <summary>
                    /// Projects an <see cref="IEnumerable{T}"/> source with captured values supplied separately for generator-friendly interception.
                    /// </summary>
                    public static IEnumerable<TResult> SelectExpr<TIn, TResult>(this IEnumerable<TIn> query, global::System.Func<TIn, TResult> selector, {{DynamicallyAccessedPublicProperties}} object capture)
                        where TIn : class => throw ThrowInterceptionRequired;

                    /// <summary>
                    /// Projects an <see cref="IEnumerable{T}"/> source into a named DTO with an explicit capture object. This placeholder must be intercepted by generated code before execution.
                    /// </summary>
                    {{OverloadResolutionLowPriority}}
                    public static IEnumerable<TResult> SelectExpr<TIn, TResult>(this IEnumerable<TIn> query, global::System.Func<TIn, object> selector, {{DynamicallyAccessedPublicProperties}} object capture)
                        where TIn : class => throw ThrowInterceptionRequired;
                }
            }
            """;

        return source;
    }
}
