namespace Linqraft.Core.Configuration;

public abstract class LinqraftGeneratorOptionsCore
{
    public virtual string GeneratorDisplayName => "Linqraft";

    public virtual string GeneratedHeaderComment => "This file is auto-generated.";

    public virtual string SupportNamespace => "Linqraft";

    public virtual string GlobalUsingNamespace => SupportNamespace;

    public virtual string DeclarationSourceHintName => $"{SupportNamespace}.Declarations.g.cs";

    public virtual string GlobalUsingsSourceHintName => $"{SupportNamespace}.GlobalUsings.g.cs";

    public virtual string EmbeddedAttributeNamespace => "Microsoft.CodeAnalysis";

    public virtual string InterceptsLocationAttributeNamespace => "System.Runtime.CompilerServices";

    public virtual string MappingVisibilityEnumName => "LinqraftMappingVisibility";

    public virtual string MappingGenerateAttributeName => "LinqraftMappingGenerateAttribute";

    public virtual string AutoGeneratedDtoAttributeName => "LinqraftAutoGeneratedDtoAttribute";

    public virtual string MappingDeclareClassName => "LinqraftMappingDeclare";

    public virtual string GeneratorKitClassName => "LinqraftKit";

    public virtual string ObjectGenerationMethodName => "Generate";

    public virtual string SelectExprClassName => "SelectExprExtensions";

    public virtual string SelectExprMethodName => "SelectExpr";

    public virtual string SelectManyExprClassName => "SelectManyExprExtensions";

    public virtual string SelectManyExprMethodName => "SelectManyExpr";

    public virtual string GroupByExprClassName => "GroupByExprExtensions";

    public virtual string GroupByExprMethodName => "GroupByExpr";

    public virtual string GlobalNamespacePropertyName => "build_property.LinqraftGlobalNamespace";

    public virtual string RecordGeneratePropertyName => "build_property.LinqraftRecordGenerate";

    public virtual string PropertyAccessorPropertyName => "build_property.LinqraftPropertyAccessor";

    public virtual string HasRequiredPropertyName => "build_property.LinqraftHasRequired";

    public virtual string CommentOutputPropertyName => "build_property.LinqraftCommentOutput";

    public virtual string ArrayNullabilityRemovalPropertyName =>
        "build_property.LinqraftArrayNullabilityRemoval";

    public virtual string NestedDtoUseHashNamespacePropertyName =>
        "build_property.LinqraftNestedDtoUseHashNamespace";

    public virtual string UsePrebuildExpressionPropertyName =>
        "build_property.LinqraftUsePrebuildExpression";

    public virtual string GlobalUsingPropertyName => "build_property.LinqraftGlobalUsing";

    public virtual string MappingHintNamePrefix => "Mapping";

    public virtual string ObjectGenerationHintNamePrefix => "Generate";

    public virtual string StandaloneDtoHintNamePrefix => "Model";

    public virtual string NestedDtoNamespacePrefix => "LinqraftGenerated";

    public virtual string DtoPlaceholderPrefix => "__LinqraftDto";

    public string MappingGenerateAttributeMetadataName =>
        $"{SupportNamespace}.{MappingGenerateAttributeName}";

    public string GeneratorKitMetadataName => $"{SupportNamespace}.{GeneratorKitClassName}";
}
