name: Bug Report(Analyzer)
description: File a bug report about the Analyzer.
title: "bug: "
labels: 
  - bug
  - analyzer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: minimal-repro
    attributes:
      label: Minimal Reproducible Example
      description: Please provide a minimal reproducible example that demonstrates the issue.
      placeholder: query.SelectExpr(s => ...);
      render: csharp
    validations:
      required: true
  - type: textarea
    id: error-details
    attributes:
      label: Error Details
      description: |
        Please provide the error details you actually got.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected Result
      description: Please provide the result you expected to see.
      placeholder: e.g., No diagnostics reported.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please provide any additional information that might be relevant to the issue.
      render: markdown
    validations:
      required: false