namespace Linqraft.Core.Generation;

internal static class CodeTemplateContents
{
    public static string CreateAutoGeneratedHeader(string generatedHeaderComment) =>
        $$"""
            // <auto-generated>
            // {{generatedHeaderComment}}
            // see: https://github.com/arika0093/Linqraft
            // </auto-generated>
            """;

    public const string EmbeddedAttribute =
		"[global::Microsoft.CodeAnalysis.EmbeddedAttribute]";

	public const string ClassAndMethodAttributes =
        "[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]";

    public const string ClassAttributes =
        "[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]";

	public const string MethodAttributes =
        "[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]";

	public const string EditorBrowsableNeverAttribute =
        "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";

    public const string DynamicallyAccessedPublicProperties =
        "[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties)]";

    public const string OverloadResolutionLowPriority = """
        #if NET9_0_OR_GREATER
            [System.Runtime.CompilerServices.OverloadResolutionPriorityAttribute(-1)]
            #endif
        """;
}
