namespace Linqraft.Core.Generation;

internal static class CodeTemplateContents
{
    public const string AutoGeneratedHeader = $"""
        // <auto-generated>
        // This file is auto-generated by Linqraft (Ver. {ThisAssembly.AssemblyInformationalVersion})
        // see: https://github.com/arika0093/Linqraft
        // </auto-generated>
        """;
    public const string EditorBrowsableNeverAttribute =
        "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";

    public const string DynamicallyAccessedPublicProperties =
        "[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties)]";

    public const string OverloadResolutionLowPriority = """
        #if NET9_0_OR_GREATER
            [System.Runtime.CompilerServices.OverloadResolutionPriorityAttribute(-1)]
            #endif
        """;
}
