namespace Linqraft.Core.Generation;

internal static class CodeTemplateContents
{
    public const string AutoGeneratedHeader = "// <auto-generated>\r\n// This file is auto-generated by Linqraft\r\n// </auto-generated>";
    public const string EditorBrowsableNeverAttribute =
        "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";
}
