using System.Linq;
using Microsoft.CodeAnalysis;

namespace Linqraft.Core.AnalyzerHelpers;

/// <summary>
/// Helper methods for working with DTO types in analyzers
/// </summary>
public static class DtoTypeHelper
{
    /// <summary>
    /// Checks if a type has the LinqraftAutoGeneratedDtoAttribute, indicating it was generated by the source generator.
    /// </summary>
    /// <param name="type">The type symbol to check</param>
    /// <returns>True if the type has the auto-generated attribute, false otherwise</returns>
    public static bool HasAutoGeneratedDtoAttribute(ITypeSymbol type)
    {
        return type.GetAttributes().Any(attr =>
        {
            var attrClass = attr.AttributeClass;
            if (attrClass == null)
            {
                return false;
            }

            // Check for LinqraftAutoGeneratedDtoAttribute in Linqraft namespace
            if (attrClass.Name != "LinqraftAutoGeneratedDtoAttribute")
            {
                return false;
            }

            var containingNamespace = attrClass.ContainingNamespace;
            return containingNamespace != null
                && !containingNamespace.IsGlobalNamespace
                && containingNamespace.Name == "Linqraft"
                && containingNamespace.ContainingNamespace?.IsGlobalNamespace == true;
        });
    }
}
