using System.Linq;
using Microsoft.CodeAnalysis;

namespace Linqraft.Core.AnalyzerHelpers;

/// <summary>
/// Helper methods for working with DTO types in analyzers
/// </summary>
public static class DtoTypeHelper
{
    /// <summary>
    /// Checks if a type symbol represents a source-generated DTO that doesn't need a user-defined partial declaration.
    /// This includes both auto-generated nested DTOs (marked with LinqraftAutoGeneratedDtoAttribute) 
    /// and explicit DTOs that were already generated by the source generator (found in .g.cs files).
    /// </summary>
    /// <param name="type">The type symbol to check</param>
    /// <returns>True if the type is source-generated and doesn't need manual partial declaration, false otherwise</returns>
    public static bool IsSourceGeneratedDto(ITypeSymbol type)
    {
        // Check 1: Does it have the auto-generated attribute? (for nested/implicit DTOs)
        var hasAutoGeneratedAttribute = type.GetAttributes().Any(attr =>
        {
            var attrClass = attr.AttributeClass;
            if (attrClass == null)
            {
                return false;
            }

            // Check for LinqraftAutoGeneratedDtoAttribute in Linqraft namespace
            if (attrClass.Name != "LinqraftAutoGeneratedDtoAttribute")
            {
                return false;
            }

            var containingNamespace = attrClass.ContainingNamespace;
            return containingNamespace != null
                && !containingNamespace.IsGlobalNamespace
                && containingNamespace.Name == "Linqraft"
                && containingNamespace.ContainingNamespace?.IsGlobalNamespace == true;
        });

        if (hasAutoGeneratedAttribute)
        {
            return true;
        }

        // Check 2: Is it defined in a .g.cs file? (for explicit DTOs already generated)
        foreach (var location in type.Locations)
        {
            if (location.IsInSource)
            {
                var sourceTree = location.SourceTree;
                if (sourceTree?.FilePath != null && sourceTree.FilePath.EndsWith(".g.cs"))
                {
                    return true;
                }
            }
        }

        return false;
    }
}
