using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace Linqraft.Analyzer;

internal static class DiagnosticDescriptors
{
    public static readonly DiagnosticDescriptor AnonymousTypeToDto = new(
        "LQRF001",
        "Anonymous object can be converted to DTO",
        "Anonymous object can be converted to a DTO class",
        "Design",
        DiagnosticSeverity.Hidden,
        isEnabledByDefault: true
    );

    public static readonly DiagnosticDescriptor ApiControllerProducesResponseType = new(
        "LQRF002",
        "Action can declare ProducesResponseType",
        "Action '{0}' can declare ProducesResponseType(typeof({1}))",
        "Design",
        DiagnosticSeverity.Info,
        isEnabledByDefault: true
    );

    public static readonly DiagnosticDescriptor AsyncApiResponseMethod = new(
        "LQRF003",
        "Method can be converted to API response method",
        "Method '{0}' can be converted to an async API response method",
        "Design",
        DiagnosticSeverity.Info,
        isEnabledByDefault: true
    );

    public static readonly DiagnosticDescriptor SyncApiResponseMethod = new(
        "LQRF004",
        "Method can be converted to synchronous API response method",
        "Method '{0}' can be converted to a synchronous API response method",
        "Design",
        DiagnosticSeverity.Info,
        isEnabledByDefault: true
    );

    public static readonly DiagnosticDescriptor SelectExprToTyped = new(
        "LQRS001",
        "SelectExpr can be converted to typed form",
        "SelectExpr can be converted to SelectExpr<TSource, TDto>",
        "Design",
        DiagnosticSeverity.Hidden,
        isEnabledByDefault: true
    );

    public static readonly DiagnosticDescriptor SelectToSelectExprAnonymous = new(
        "LQRS002",
        "IQueryable.Select can be converted to SelectExpr",
        "IQueryable.Select can be converted to SelectExpr",
        "Design",
        DiagnosticSeverity.Info,
        isEnabledByDefault: true
    );

    public static readonly DiagnosticDescriptor SelectToSelectExprNamed = new(
        "LQRS003",
        "IQueryable.Select can be converted to SelectExpr",
        "IQueryable.Select can be converted to SelectExpr",
        "Design",
        DiagnosticSeverity.Info,
        isEnabledByDefault: true
    );

    public static readonly DiagnosticDescriptor TernaryNullCheckToConditional = new(
        "LQRS004",
        "Ternary can be simplified",
        "Null-guard ternary can be simplified with null-conditional access",
        "Design",
        DiagnosticSeverity.Info,
        isEnabledByDefault: true
    );

    public static readonly DiagnosticDescriptor UnnecessaryCapture = new(
        "LQRS005",
        "Capture entry is unused",
        "Capture value '{0}' is not used by the SelectExpr selector",
        "Usage",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true
    );

    public static readonly DiagnosticDescriptor GeneratedHashedNamespaceUsage = new(
        "LQRW001",
        "Avoid hash-based generated namespaces",
        "Hash-based generated namespace '{0}' is an unstable implementation detail",
        "Usage",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true
    );

    public static readonly DiagnosticDescriptor AutoGeneratedDtoUsage = new(
        "LQRW002",
        "Avoid explicit use of auto-generated DTOs",
        "Type '{0}' is an auto-generated DTO and should not be referenced explicitly",
        "Usage",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true
    );

    public static readonly DiagnosticDescriptor LocalVariableCapture = new(
        "LQRE001",
        "Capture variable is missing",
        "SelectExpr references outer value '{0}' without capture",
        "Usage",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    public static readonly DiagnosticDescriptor GroupByAnonymousKey = new(
        "LQRE002",
        "Anonymous GroupBy key is unsupported",
        "Anonymous GroupBy keys cannot flow into SelectExpr",
        "Usage",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    public static ImmutableArray<DiagnosticDescriptor> All { get; } =
        ImmutableArray.Create(
            AnonymousTypeToDto,
            ApiControllerProducesResponseType,
            AsyncApiResponseMethod,
            SyncApiResponseMethod,
            SelectExprToTyped,
            SelectToSelectExprAnonymous,
            SelectToSelectExprNamed,
            TernaryNullCheckToConditional,
            UnnecessaryCapture,
            GeneratedHashedNamespaceUsage,
            AutoGeneratedDtoUsage,
            LocalVariableCapture,
            GroupByAnonymousKey
        );
}
