using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Linqraft.Analyzer;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Linqraft.Analyzer.Tests;

public sealed class AnalyzerSmokeTests
{
    [Test]
    public async Task Missing_capture_reports_LQRE001()
    {
        const string source = """
            using System;
            using System.Linq;

            public class Entity
            {
                public int Id { get; set; }
                public int Value { get; set; }
            }

            public class EntityDto { }

            namespace System.Linq
            {
                public static class SelectExprExtensions
                {
                    public static IQueryable<TResult> SelectExpr<TIn, TResult>(this IQueryable<TIn> query, Func<TIn, object> selector)
                        where TIn : class => throw null!;
                }
            }

            public class QueryHolder
            {
                public IQueryable<EntityDto> Project(IQueryable<Entity> source, int threshold)
                {
                    return source.SelectExpr<Entity, EntityDto>(entity => new
                    {
                        entity.Id,
                        IsLarge = entity.Value > threshold,
                    });
                }
            }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRE001");
    }

    [Test]
    public async Task Queryable_select_anonymous_reports_LQRS002()
    {
        const string source = """
            using System.Linq;

            public class Entity
            {
                public int Id { get; set; }
            }

            public class QueryHolder
            {
                public IQueryable<object> Project(IQueryable<Entity> source)
                {
                    return source.Select(entity => new { entity.Id });
                }
            }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRS002");
    }

    [Test]
    public async Task Hash_namespace_usage_reports_LQRW001()
    {
        const string source = """
            using Demo.LinqraftGenerated_1234ABCD;

            public class Sample { }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRW001");
    }

    [Test]
    public async Task Auto_generated_dto_usage_reports_LQRW002()
    {
        const string source = """
            namespace Linqraft
            {
                internal sealed class LinqraftAutoGeneratedDtoAttribute : System.Attribute { }
            }

            [Linqraft.LinqraftAutoGeneratedDto]
            public sealed class GeneratedItemsDto
            {
            }

            public sealed class QueryModel
            {
                public GeneratedItemsDto Item { get; set; } = new();
            }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRW002");
    }

    [Test]
    public async Task Untyped_selectexpr_reports_LQRS001()
    {
        const string source = """
            using System;
            using System.Linq;

            namespace System.Linq
            {
                public static class SelectExprExtensions
                {
                    public static IQueryable<TResult> SelectExpr<TIn, TResult>(this IQueryable<TIn> query, Func<TIn, TResult> selector)
                        where TIn : class => throw null!;
                }
            }

            public class Entity
            {
                public int Id { get; set; }
            }

            public class QueryHolder
            {
                public object Project(IQueryable<Entity> source)
                {
                    return source.SelectExpr(entity => new
                    {
                        entity.Id,
                    });
                }
            }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRS001");
    }

    [Test]
    public async Task Queryable_select_named_reports_LQRS003()
    {
        const string source = """
            using System.Linq;

            public class Entity
            {
                public int Id { get; set; }
            }

            public class EntityDto
            {
                public int Id { get; set; }
            }

            public class QueryHolder
            {
                public IQueryable<EntityDto> Project(IQueryable<Entity> source)
                {
                    return source.Select(entity => new EntityDto
                    {
                        Id = entity.Id,
                    });
                }
            }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRS003");
    }

    [Test]
    public async Task Ternary_inside_selectexpr_reports_LQRS004()
    {
        const string source = """
            using System;
            using System.Linq;

            namespace System.Linq
            {
                public static class SelectExprExtensions
                {
                    public static IQueryable<TResult> SelectExpr<TIn, TResult>(this IQueryable<TIn> query, Func<TIn, TResult> selector)
                        where TIn : class => throw null!;
                }
            }

            public class Child
            {
                public int Id { get; set; }
            }

            public class Entity
            {
                public Child? Child { get; set; }
            }

            public class QueryHolder
            {
                public object Project(IQueryable<Entity> source)
                {
                    return source.SelectExpr(entity => entity.Child != null
                        ? new { ChildId = entity.Child.Id }
                        : null);
                }
            }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRS004");
    }

    [Test]
    public async Task Unused_capture_reports_LQRS005()
    {
        const string source = """
            using System;
            using System.Linq;

            namespace System.Linq
            {
                public static class SelectExprExtensions
                {
                    public static IQueryable<TResult> SelectExpr<TIn, TResult>(this IQueryable<TIn> query, Func<TIn, object> selector, object capture)
                        where TIn : class => throw null!;
                }
            }

            public class Entity
            {
                public int Id { get; set; }
            }

            public class EntityDto { }

            public class QueryHolder
            {
                public IQueryable<EntityDto> Project(IQueryable<Entity> source, int threshold)
                {
                    return source.SelectExpr<Entity, EntityDto>(entity => new
                    {
                        entity.Id,
                    }, capture: new { threshold });
                }
            }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRS005");
    }

    [Test]
    public async Task Anonymous_groupby_key_reports_LQRE002()
    {
        const string source = """
            using System;
            using System.Linq;

            namespace System.Linq
            {
                public static class SelectExprExtensions
                {
                    public static IQueryable<TResult> SelectExpr<TIn, TResult>(this IQueryable<TIn> query, Func<TIn, TResult> selector)
                        where TIn : class => throw null!;
                }
            }

            public class Entity
            {
                public int Id { get; set; }
            }

            public class QueryHolder
            {
                public object Project(IQueryable<Entity> source)
                {
                    return source
                        .GroupBy(entity => new { entity.Id })
                        .SelectExpr(group => new { group.Key });
                }
            }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRE002");
    }

    [Test]
    public async Task Anonymous_object_reports_LQRF001()
    {
        const string source = """
            public class Builder
            {
                public object Create()
                {
                    return new { Id = 1 };
                }
            }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRF001");
    }

    [Test]
    public async Task Api_controller_without_response_metadata_reports_LQRF002()
    {
        const string source = """
            using System;
            using System.Linq;

            namespace Microsoft.AspNetCore.Mvc
            {
                public sealed class ApiControllerAttribute : Attribute { }
                public interface IActionResult { }
                public abstract class ControllerBase { }
            }

            namespace System.Linq
            {
                public static class SelectExprExtensions
                {
                    public static IQueryable<TResult> SelectExpr<TIn, TResult>(this IQueryable<TIn> query, Func<TIn, object> selector)
                        where TIn : class => throw null!;
                }
            }

            public class Entity
            {
                public int Id { get; set; }
            }

            public class EntityDto { }

            [Microsoft.AspNetCore.Mvc.ApiController]
            public sealed class EntityController : Microsoft.AspNetCore.Mvc.ControllerBase
            {
                public Microsoft.AspNetCore.Mvc.IActionResult Get(IQueryable<Entity> source)
                {
                    var _ = source.SelectExpr<Entity, EntityDto>(entity => new
                    {
                        entity.Id,
                    });
                    return default!;
                }
            }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRF002");
    }

    [Test]
    public async Task Void_dbset_select_reports_LQRF003()
    {
        const string source = """
            using System;
            using System.Collections;
            using System.Collections.Generic;
            using System.Linq;
            using System.Linq.Expressions;

            namespace Microsoft.EntityFrameworkCore
            {
                public class DbSet<T> : IQueryable<T>
                {
                    public Type ElementType => throw null!;
                    public Expression Expression => throw null!;
                    public IQueryProvider Provider => throw null!;
                    public IEnumerator<T> GetEnumerator() => throw null!;
                    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
                }
            }

            public class Entity
            {
                public int Id { get; set; }
            }

            public sealed class Context
            {
                public Microsoft.EntityFrameworkCore.DbSet<Entity> Entities { get; } = null!;
            }

            public class ApiService
            {
                public void Execute(Context db)
                {
                    db.Entities.Select(entity => new { entity.Id });
                }
            }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRF003");
    }

    [Test]
    public async Task Void_queryable_select_reports_LQRF004()
    {
        const string source = """
            using System.Linq;

            public class Entity
            {
                public int Id { get; set; }
            }

            public class ApiService
            {
                public void Execute(IQueryable<Entity> source)
                {
                    source.Select(entity => new { entity.Id });
                }
            }
            """;

        var diagnostics = await GetDiagnosticsAsync(source);
        diagnostics.Select(diagnostic => diagnostic.Id).ShouldContain("LQRF004");
    }

    private static async Task<ImmutableArray<Diagnostic>> GetDiagnosticsAsync(string source)
    {
        var parseOptions = new CSharpParseOptions(LanguageVersion.Preview);
        var syntaxTree = CSharpSyntaxTree.ParseText(source, parseOptions, path: "Test0.cs");
        var compilation = CSharpCompilation.Create(
            assemblyName: "AnalyzerTests",
            syntaxTrees: [syntaxTree],
            references: GetMetadataReferences(),
            options: new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable
            )
        );

        var analyzer = new LinqraftCompositeAnalyzer();
        var compilationWithAnalyzers = compilation.WithAnalyzers(
            ImmutableArray.Create<DiagnosticAnalyzer>(analyzer)
        );
        return await compilationWithAnalyzers.GetAnalyzerDiagnosticsAsync();
    }

    private static IEnumerable<MetadataReference> GetMetadataReferences()
    {
        var explicitAssemblies = new List<Assembly>
        {
            typeof(object).Assembly,
            typeof(Enumerable).Assembly,
            typeof(Queryable).Assembly,
            typeof(System.Linq.Expressions.Expression).Assembly,
            typeof(List<>).Assembly,
            typeof(Task).Assembly,
        };

        foreach (
            var assemblyName in new[]
            {
                "System.Runtime",
                "netstandard",
                "System.Collections",
                "System.Linq",
                "System.Linq.Queryable",
                "System.Linq.Expressions",
                "System.Threading.Tasks",
            }
        )
        {
            try
            {
                explicitAssemblies.Add(System.Reflection.Assembly.Load(assemblyName));
            }
            catch
            {
                // Best-effort load for compilation metadata.
            }
        }

        return AppDomain
            .CurrentDomain.GetAssemblies()
            .Concat(explicitAssemblies)
            .Where(assembly => !assembly.IsDynamic && !string.IsNullOrWhiteSpace(assembly.Location))
            .Where(assembly =>
            {
                var name = assembly.GetName().Name ?? string.Empty;
                return !name.StartsWith("Linqraft", StringComparison.Ordinal);
            })
            .Select(assembly => MetadataReference.CreateFromFile(assembly.Location))
            .GroupBy(reference => reference.Display, StringComparer.OrdinalIgnoreCase)
            .Select(group => group.First());
    }
}
