using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Xunit;

namespace Linqraft.Analyzer.Tests;

public class SelectExprExtendAnalyzerTests
{
    [Fact]
    public async Task CodeFix_AnonymousSelectExprToAutoGeneratedSelectExpr()
    {
        var testCode =
            @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.{|#0:SelectExpr|}(x => new { x.FirstName, x.LastName });
    }
}";

        var fixedCode =
            @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.{|#1:SelectExpr|}<Person, PersonDto>(x => new { x.FirstName, x.LastName });
    }
}";

        var expected = new DiagnosticResult(DiagnosticDescriptors.EnhanceSelectExpr).WithLocation(
            0
        );

        var expectedAfterFix = new DiagnosticResult(
            DiagnosticDescriptors.EnhanceSelectExpr
        ).WithLocation(1);

        var test = new CSharpCodeFixTest<
            SelectToSelectExprAnalyzer,
            SelectToSelectExprCodeFixProvider,
            DefaultVerifier
        >
        {
            TestCode = testCode,
            FixedCode = fixedCode,
            ExpectedDiagnostics = { expected },
            CodeActionEquivalenceKey = "ConvertAnonymousSelectExprToAutoGeneratedSelectExpr",
        };
        test.FixedState.ExpectedDiagnostics.Add(expectedAfterFix);
        test.CompilerDiagnostics = CompilerDiagnostics.None;

        await test.RunAsync();
    }
}
