using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Xunit;

namespace Linqraft.Analyzer.Tests;

public class SelectToSelectExprAnalyzerTests
{
    [Fact]
    public async Task NoDiagnostic_WhenNotUsingSelect()
    {
        var test = @"
using System.Linq;

class TestClass
{
    void TestMethod()
    {
        var data = new[] { 1, 2, 3 };
        var result = data.Where(x => x > 1);
    }
}";

        await new CSharpAnalyzerTest<SelectToSelectExprAnalyzer, DefaultVerifier>
        {
            TestCode = test,
        }.RunAsync();
    }

    [Fact]
    public async Task ProducesDiagnostic_WhenUsingSelect()
    {
        var test = @"
using System.Linq;

class TestClass
{
    void TestMethod()
    {
        var data = new[] { 1, 2, 3 };
        var result = data.{|#0:Select|}(x => x * 2);
    }
}";

        var expected = new DiagnosticResult(DiagnosticDescriptors.SelectToSelectExpr)
            .WithLocation(0);

        await new CSharpAnalyzerTest<SelectToSelectExprAnalyzer, DefaultVerifier>
        {
            TestCode = test,
            ExpectedDiagnostics = { expected },
        }.RunAsync();
    }

    [Fact]
    public async Task CodeFix_ConvertsSelectToSelectExpr()
    {
        var test = @"
using System.Linq;

class TestClass
{
    void TestMethod()
    {
        var data = new[] { 1, 2, 3 };
        var result = data.{|#0:Select|}(x => x * 2);
    }
}";

        var fixedCode = @"
using System.Linq;

class TestClass
{
    void TestMethod()
    {
        var data = new[] { 1, 2, 3 };
        var result = data.{|CS1061:SelectExpr|}(x => x * 2);
    }
}";

        var expected = new DiagnosticResult(DiagnosticDescriptors.SelectToSelectExpr)
            .WithLocation(0);

        await new CSharpCodeFixTest<SelectToSelectExprAnalyzer, SelectToSelectExprCodeFixProvider, DefaultVerifier>
        {
            TestCode = test,
            FixedCode = fixedCode,
            ExpectedDiagnostics = { expected },
        }.RunAsync();
    }

    [Fact]
    public async Task CodeFix_AnonymousSelectToAnonymousSelectExpr()
    {
        var testCode = @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.{|#0:Select|}(x => new { x.FirstName, x.LastName });
    }
}";

        var fixedCode = @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.SelectExpr(x => new { x.FirstName, x.LastName });
    }
}";

        var expected = new DiagnosticResult(DiagnosticDescriptors.SelectToSelectExpr)
            .WithLocation(0);

        var test = new CSharpCodeFixTest<SelectToSelectExprAnalyzer, SelectToSelectExprCodeFixProvider, DefaultVerifier>
        {
            TestCode = testCode,
            FixedCode = fixedCode,
            ExpectedDiagnostics = { expected },
            CodeActionEquivalenceKey = "ConvertToAnonymousSelectExpr",
        };
        test.CompilerDiagnostics = CompilerDiagnostics.None;
        
        await test.RunAsync();
    }

    [Fact]
    public async Task CodeFix_AnonymousSelectToAutoGeneratedSelectExpr()
    {
        var testCode = @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.{|#0:Select|}(x => new { x.FirstName, x.LastName });
    }
}";

        var fixedCode = @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.SelectExpr<Person, PersonDto>(x => new { x.FirstName, x.LastName });
    }
}";

        var expected = new DiagnosticResult(DiagnosticDescriptors.SelectToSelectExpr)
            .WithLocation(0);

        var test = new CSharpCodeFixTest<SelectToSelectExprAnalyzer, SelectToSelectExprCodeFixProvider, DefaultVerifier>
        {
            TestCode = testCode,
            FixedCode = fixedCode,
            ExpectedDiagnostics = { expected },
            CodeActionEquivalenceKey = "ConvertToAutoGeneratedSelectExpr",
        };
        test.CompilerDiagnostics = CompilerDiagnostics.None;
        
        await test.RunAsync();
    }

    [Fact]
    public async Task CodeFix_PredefinedDtoSelectToAutoGeneratedSelectExpr()
    {
        var testCode = @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class PersonDto
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.{|#0:Select|}(x => new PersonDto { FirstName = x.FirstName, LastName = x.LastName });
    }
}";

        var fixedCode = @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class PersonDto
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.SelectExpr<Person, PersonDto>(x => new { FirstName = x.FirstName, LastName = x.LastName });
    }
}";

        var expected = new DiagnosticResult(DiagnosticDescriptors.SelectToSelectExpr)
            .WithLocation(0);

        var test = new CSharpCodeFixTest<SelectToSelectExprAnalyzer, SelectToSelectExprCodeFixProvider, DefaultVerifier>
        {
            TestCode = testCode,
            FixedCode = fixedCode,
            ExpectedDiagnostics = { expected },
            CodeActionEquivalenceKey = "ConvertPredefinedToAutoGeneratedSelectExpr",
        };
        test.CompilerDiagnostics = CompilerDiagnostics.None;
        
        await test.RunAsync();
    }
}
