using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Xunit;

namespace Linqraft.Analyzer.Tests;

public class SelectToSelectExprAnalyzerTests
{
    [Fact]
    public async Task CodeFix_AnonymousSelectToAnonymousSelectExpr()
    {
        var testCode =
            @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.{|#0:Select|}(x => new { x.FirstName, x.LastName });
    }
}";

        var fixedCode =
            @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.{|#1:SelectExpr|}(x => new { x.FirstName, x.LastName });
    }
}";

        var expected = new DiagnosticResult(DiagnosticDescriptors.SelectToSelectExpr).WithLocation(
            0
        );

        var expectedAfterFix = new DiagnosticResult(
            DiagnosticDescriptors.EnhanceSelectExpr
        ).WithLocation(1);

        var test = new CSharpCodeFixTest<
            SelectToSelectExprAnalyzer,
            SelectToSelectExprCodeFixProvider,
            DefaultVerifier
        >
        {
            TestCode = testCode,
            FixedCode = fixedCode,
            ExpectedDiagnostics = { expected },
            CodeActionEquivalenceKey = "ConvertToAnonymousSelectExpr",
        };
        test.FixedState.ExpectedDiagnostics.Add(expectedAfterFix);
        test.CompilerDiagnostics = CompilerDiagnostics.None;

        await test.RunAsync();
    }

    [Fact]
    public async Task CodeFix_AnonymousSelectToAutoGeneratedSelectExpr()
    {
        var testCode =
            @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.{|#0:Select|}(x => new { x.FirstName, x.LastName });
    }
}";

        var fixedCode =
            @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.SelectExpr<Person, PersonDto>(x => new { x.FirstName, x.LastName });
    }
}";

        var expected = new DiagnosticResult(DiagnosticDescriptors.SelectToSelectExpr).WithLocation(
            0
        );

        var test = new CSharpCodeFixTest<
            SelectToSelectExprAnalyzer,
            SelectToSelectExprCodeFixProvider,
            DefaultVerifier
        >
        {
            TestCode = testCode,
            FixedCode = fixedCode,
            ExpectedDiagnostics = { expected },
            CodeActionEquivalenceKey = "ConvertToAutoGeneratedSelectExpr",
            NumberOfIncrementalIterations = 1,
            NumberOfFixAllIterations = 1,
        };
        test.CompilerDiagnostics = CompilerDiagnostics.None;
        // Accept the LQ002 diagnostic in the fixed state
        test.FixedState.ExpectedDiagnostics.Add(
            new DiagnosticResult(DiagnosticDescriptors.EnhanceSelectExpr).WithSpan(15, 27, 15, 56)
        );

        await test.RunAsync();
    }

    [Fact]
    public async Task CodeFix_PredefinedDtoSelectToAutoGeneratedSelectExpr()
    {
        var testCode =
            @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class PersonDto
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.{|#0:Select|}(x => new PersonDto { FirstName = x.FirstName, LastName = x.LastName });
    }
}";

        var fixedCode =
            @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class PersonDto
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.SelectExpr<Person, PersonDto>(x => new { FirstName = x.FirstName, LastName = x.LastName });
    }
}";

        var expected = new DiagnosticResult(DiagnosticDescriptors.SelectToSelectExpr).WithLocation(
            0
        );

        var test = new CSharpCodeFixTest<
            SelectToSelectExprAnalyzer,
            SelectToSelectExprCodeFixProvider,
            DefaultVerifier
        >
        {
            TestCode = testCode,
            FixedCode = fixedCode,
            ExpectedDiagnostics = { expected },
            CodeActionEquivalenceKey = "ConvertPredefinedToAutoGeneratedSelectExpr",
            NumberOfIncrementalIterations = 1,
            NumberOfFixAllIterations = 1,
        };
        test.CompilerDiagnostics = CompilerDiagnostics.None;
        // Accept the LQ002 diagnostic in the fixed state
        test.FixedState.ExpectedDiagnostics.Add(
            new DiagnosticResult(DiagnosticDescriptors.EnhanceSelectExpr).WithSpan(21, 27, 21, 56)
        );

        await test.RunAsync();
    }

    [Fact]
    public async Task CodeFix_PredefinedDtoSelectToPredefinedSelectExpr()
    {
        var testCode =
            @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class PersonDto
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.{|#0:Select|}(x => new PersonDto { FirstName = x.FirstName, LastName = x.LastName });
    }
}";

        var fixedCode =
            @"
using System.Linq;

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class PersonDto
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

class TestClass
{
    void TestMethod()
    {
        var data = new[] { new Person() };
        var result = data.SelectExpr(x => new PersonDto { FirstName = x.FirstName, LastName = x.LastName });
    }
}";

        var expected = new DiagnosticResult(DiagnosticDescriptors.SelectToSelectExpr).WithLocation(
            0
        );

        var test = new CSharpCodeFixTest<
            SelectToSelectExprAnalyzer,
            SelectToSelectExprCodeFixProvider,
            DefaultVerifier
        >
        {
            TestCode = testCode,
            FixedCode = fixedCode,
            ExpectedDiagnostics = { expected },
            CodeActionEquivalenceKey = "ConvertPredefinedToPredefinedSelectExpr",
            NumberOfIncrementalIterations = 1,
            NumberOfFixAllIterations = 1,
        };
        test.CompilerDiagnostics = CompilerDiagnostics.None;

        await test.RunAsync();
    }
}
