using Microsoft.CodeAnalysis;

namespace Linqraft.QueryExtensions;

/// <summary>
/// Source generator for <c>Linqraft.QueryExtensions</c>.
/// Registers the <c>AsLeftJoin</c> and <c>MappingAs&lt;T&gt;</c> extension stubs and their
/// associated <c>[LinqraftExtension]</c> class declarations into every project that
/// references this package.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class LinqraftQueryExtensionsGenerator : IIncrementalGenerator
{
    // Namespace used for all stubs emitted by this package.
    private const string ExtensionsNamespace = "Linqraft.QueryExtensions";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
        {
            output.AddSource(
                "Linqraft.QueryExtensions.AsLeftJoin.g.cs",
                BuildAsLeftJoinSource()
            );
            output.AddSource(
                "Linqraft.QueryExtensions.MappingAs.g.cs",
                BuildMappingAsSource()
            );
        });
    }

    private static string BuildAsLeftJoinSource() =>
        $$"""
        // <auto-generated>
        // This file is auto-generated by Linqraft.QueryExtensions.
        // see: https://github.com/arika0093/Linqraft
        // </auto-generated>
        #nullable enable
        #pragma warning disable CS1591

        namespace {{ExtensionsNamespace}}
        {
            /// <summary>
            /// Linqraft extension declaration for <c>AsLeftJoin</c>.
            /// The Linqraft source generator uses this class to rewrite
            /// <c>.AsLeftJoin()</c> calls inside <c>SelectExpr</c> projections
            /// so that navigation-property access becomes null-conditional,
            /// which causes EF Core to emit a LEFT JOIN instead of an INNER JOIN.
            /// </summary>
            [global::Linqraft.LinqraftExtension(
                "AsLeftJoin",
                GenerateNamespace = "{{ExtensionsNamespace}}",
                Behavior = global::Linqraft.LinqraftExtensionBehavior.NullConditionalNavigation)]
            internal sealed class LinqraftAsLeftJoinExtension : global::Linqraft.LinqraftExtensionBase { }

            /// <summary>
            /// Provides the <c>AsLeftJoin</c> stub method that can be used inside
            /// <c>SelectExpr</c> projections. The method body is never executed;
            /// it is replaced at compile time by the Linqraft source generator.
            /// </summary>
            [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
            internal static partial class LinqraftAsLeftJoinExtensions
            {
                /// <summary>
                /// Marks a navigation-property access as a LEFT JOIN in the generated EF Core query.
                /// Use this inside a <c>SelectExpr</c> projection:
                /// <code>query.SelectExpr(x =&gt; new { Name = x.Child.AsLeftJoin().Name })</code>
                /// </summary>
                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                public static T AsLeftJoin<T>(this T source) where T : class => source;
            }
        }
        """;

    private static string BuildMappingAsSource() =>
        $$"""
        // <auto-generated>
        // This file is auto-generated by Linqraft.QueryExtensions.
        // see: https://github.com/arika0093/Linqraft
        // </auto-generated>
        #nullable enable
        #pragma warning disable CS1591

        namespace {{ExtensionsNamespace}}
        {
            /// <summary>
            /// Linqraft extension declaration for <c>MappingAs&lt;TResult&gt;</c>.
            /// The Linqraft source generator uses this class to rewrite
            /// <c>.MappingAs&lt;TResult&gt;()</c> calls inside <c>SelectExpr</c> projections
            /// into an explicit cast to <typeparamref name="TResult"/>.
            /// </summary>
            [global::Linqraft.LinqraftExtension(
                "MappingAs",
                GenerateNamespace = "{{ExtensionsNamespace}}",
                Behavior = global::Linqraft.LinqraftExtensionBehavior.CastToFirstTypeArgument)]
            internal sealed class LinqraftMappingAsExtension : global::Linqraft.LinqraftExtensionBase { }

            /// <summary>
            /// Provides the <c>MappingAs&lt;TResult&gt;</c> stub method that can be used inside
            /// <c>SelectExpr</c> projections. The method body is never executed;
            /// it is replaced at compile time by the Linqraft source generator.
            /// </summary>
            [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
            internal static partial class LinqraftMappingAsExtensions
            {
                /// <summary>
                /// Casts the source expression to <typeparamref name="TResult"/> in the generated projection.
                /// Use this inside a <c>SelectExpr</c> projection:
                /// <code>query.SelectExpr(x =&gt; new { Value = x.Foo.MappingAs&lt;IMyInterface&gt;() })</code>
                /// </summary>
                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                public static TResult MappingAs<TResult>(this object source)
                    => throw new global::System.InvalidOperationException(
                        "Linqraft source generator should replace MappingAs invocations before execution.");
            }
        }
        """;
}
