using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EFCore.ExprGenerator;

/// <summary>
/// Base record for SelectExpr information
/// </summary>
internal abstract record SelectExprInfo
{
    public required ITypeSymbol SourceType { get; init; }
    public required SemanticModel SemanticModel { get; init; }
    public required InvocationExpressionSyntax Invocation { get; init; }

    // Generate DTO structure for unique ID generation
    public abstract DtoStructure GenerateDtoStructure();

    // Get DTO class name
    public abstract string GetClassName(DtoStructure structure);

    // Generate SelectExpr method
    protected abstract string GenerateSelectExprMethod(
        string dtoName,
        DtoStructure structure,
        InterceptableLocation location
    );

    // Generate DTO classes
    public abstract string GenerateDtoClasses(
        DtoStructure structure,
        List<string> dtoClasses,
        string namespaceName
    );

    // Generate source code
    public void GenerateCode(SourceProductionContext context)
    {
        try
        {
            var location =
                SemanticModel.GetInterceptableLocation(Invocation)
                ?? throw new InvalidOperationException("Failed to get interceptable location.");

            // Analyze anonymous type structure
            var dtoStructure = GenerateDtoStructure();

            // Skip if properties are empty
            if (dtoStructure.Properties.Count == 0)
                return;

            // Generate unique ID (from hash of property structure and first location)
            var uniqueId = GetUniqueId(location);

            // Get namespace
            var namespaceSymbol = SourceType.ContainingNamespace;
            var namespaceName = namespaceSymbol?.ToDisplayString() ?? "Generated";

            // Generate DTO classes (including nested DTOs)
            var dtoClasses = new List<string>();
            var mainDtoName = GenerateDtoClasses(dtoStructure, dtoClasses, namespaceName);
            var mainDtoFullName = $"global::{namespaceName}.{mainDtoName}";

            // Generate SelectExpr method with interceptor attribute (using only first location)
            var selectExprMethod = GenerateSelectExprMethod(
                mainDtoFullName,
                dtoStructure,
                location
            );

            // Build final source code
            var sourceCode = BuildSourceCode(
                namespaceName,
                mainDtoName,
                dtoClasses,
                selectExprMethod
            );

            // Register with Source Generator
            context.AddSource($"GeneratedExpression_{uniqueId}.g.cs", sourceCode);
        }
        catch (Exception ex)
        {
            // Output error information for debugging
            var errorMessage = $"""
                /*
                 * Source Generator Error: {ex.Message}
                 * Stack Trace: {ex.StackTrace}
                 */
                """;
            var hash = Guid.NewGuid().ToString("N")[..8];
            context.AddSource($"GeneratorError_{hash}.g.cs", errorMessage);
        }
    }

    // Generate unique ID (including location information)
    public string GetUniqueId(InterceptableLocation location)
    {
        var structureId = GenerateDtoStructure().GetUniqueId();
        var locationId = location.Data.GetHashCode().ToString("X8");
        return $"{structureId}_{locationId}";
    }

    protected string BuildSourceCode(
        string namespaceName,
        string mainDtoName,
        List<string> dtoClasses,
        string selectExprMethod
    )
    {
        var accessibility = GetAccessibilityString(SourceType);
        var sb = new StringBuilder();
        sb.Append(
            $$"""
            // <auto-generated />
            #nullable enable
            #pragma warning disable IDE0060
            #pragma warning disable CS8601

            using System;
            using System.Linq;
            using System.Collections.Generic;

            namespace EFCore.ExprGenerator;
            {{accessibility}} static partial class GeneratedExpression_{{mainDtoName}}
            {
            {{selectExprMethod}}
            }
            """
        );
        sb.AppendLine();
        foreach (var dtoClass in dtoClasses)
        {
            sb.AppendLine(dtoClass);
        }
        return sb.ToString();
    }

    protected string GenerateMethodHeaderPart(string dtoName, InterceptableLocation location)
    {
        return $"""
                /// <summary>
                /// generated select expression method {dtoName} <br/>
                /// at {location.GetDisplayLocation()}
                /// </summary>
                {location.GetInterceptsLocationAttributeSyntax()}
            """;
    }

    protected string GeneratePropertyAssignment(DtoProperty property, int indents)
    {
        var expression = property.OriginalExpression;
        // For nested Select (collection) case
        if (property.NestedStructure is not null)
        {
            var converted = ConvertNestedSelect(expression, property.NestedStructure, indents);
            // Debug: Check if conversion was performed correctly
            if (converted == expression && expression.Contains("Select"))
            {
                // If conversion was not performed, leave the original expression as a comment
                return $"{converted} /* CONVERSION FAILED: {property.Name} */";
            }
            return converted;
        }
        // If nullable operator is used, convert to explicit null check
        if (property.IsNullable && expression.Contains("?."))
        {
            var defaultValue = GetDefaultValueForType(property.TypeSymbol);
            return ConvertNullableAccessToExplicitCheck(expression, defaultValue);
        }
        // Regular property access
        return expression;
    }

    protected string ConvertNestedSelect(
        string expression,
        DtoStructure nestedStructure,
        int indents
    )
    {
        var spaces = new string(' ', indents);
        // Example: s.Childs.Select(c => new { ... }) or s.Childs.Select(c => new { ... }).ToList()
        // Extract parameter name (e.g., "c")
        // Consider the possibility of whitespace or generic type parameters after .Select
        var selectIndex = expression.IndexOf(".Select");
        if (selectIndex == -1)
            return expression;
        // Find '(' after Select (start of lambda)
        var lambdaStart = expression.IndexOf("(", selectIndex);
        if (lambdaStart == -1)
            return expression;
        var lambdaArrow = expression.IndexOf("=>", lambdaStart);
        if (lambdaArrow == -1 || lambdaArrow <= lambdaStart + 1)
            return expression;
        var paramName = expression.Substring(lambdaStart + 1, lambdaArrow - lambdaStart - 1).Trim();
        if (string.IsNullOrEmpty(paramName))
            paramName = "x"; // Default parameter name
        var baseExpression = expression[..selectIndex];
        var nestedDtoName = GetClassName(nestedStructure);

        // Find the closing paren for Select(...) to detect any chained methods like .ToList()
        var parenDepth = 0;
        var selectEnd = lambdaStart;
        for (int i = lambdaStart; i < expression.Length; i++)
        {
            if (expression[i] == '(')
                parenDepth++;
            else if (expression[i] == ')')
            {
                parenDepth--;
                if (parenDepth == 0)
                {
                    selectEnd = i + 1;
                    break;
                }
            }
        }
        // Extract any chained method calls after Select(...) (e.g., ".ToList()")
        var chainedMethods = selectEnd < expression.Length ? expression[selectEnd..] : "";

        var propertyAssignments = new List<string>();
        foreach (var prop in nestedStructure.Properties)
        {
            var assignment = GeneratePropertyAssignment(prop, indents + 4);
            propertyAssignments.Add($"{spaces}    {prop.Name} = {assignment},");
        }
        var propertiesCode = string.Join("\n", propertyAssignments);
        var code = $$"""
            {{baseExpression}}.Select({{paramName}} => new {{nestedDtoName}} {
            {{propertiesCode}}
            {{spaces}}}){{chainedMethods}}
            """;
        return code;
    }

    protected string ConvertNullableAccessToExplicitCheck(string expression, string defaultValue)
    {
        // Example: c.Child?.Id → c.Child != null ? c.Child.Id : null
        // Example: s.Child3?.Child?.Id → s.Child3 != null && s.Child3.Child != null ? s.Child3.Child.Id : null
        if (!expression.Contains("?."))
            return expression;
        // Replace ?. with . to create the actual access path
        var accessPath = expression.Replace("?.", ".");
        // Find where ?. occurs and build null checks
        var checks = new List<string>();
        var parts = expression.Split(["?."], StringSplitOptions.None);
        if (parts.Length < 2)
            return expression;
        // All parts except the first require null checks
        var currentPath = parts[0];
        for (int i = 1; i < parts.Length; i++)
        {
            checks.Add($"{currentPath} != null");
            // Get the first token (property name) of the next part
            var nextPart = parts[i];
            var dotIndex = nextPart.IndexOf('.');
            var propertyName = dotIndex > 0 ? nextPart[..dotIndex] : nextPart;
            currentPath = $"{currentPath}.{propertyName}";
        }
        if (checks.Count == 0)
            return expression;
        // Build null checks
        var nullCheckPart = string.Join(" && ", checks);
        return $"{nullCheckPart} ? {accessPath} : {defaultValue}";
    }

    protected string? GetImplicitPropertyName(ExpressionSyntax expression)
    {
        // Get property name from member access (e.g., s.Id)
        if (expression is MemberAccessExpressionSyntax memberAccess)
        {
            return memberAccess.Name.Identifier.Text;
        }
        // Get property name from identifier (e.g., id)
        if (expression is IdentifierNameSyntax identifier)
        {
            return identifier.Identifier.Text;
        }
        // Do not process other complex expressions
        return null;
    }

    protected string GetDefaultValueForType(ITypeSymbol typeSymbol)
    {
        if (
            typeSymbol.IsReferenceType
            || typeSymbol.NullableAnnotation == NullableAnnotation.Annotated
        )
        {
            return "null";
        }
        return typeSymbol.SpecialType switch
        {
            SpecialType.System_Boolean => "false",
            SpecialType.System_Char => "'\\0'",
            SpecialType.System_String => "string.Empty",
            SpecialType.System_SByte
            or SpecialType.System_Byte
            or SpecialType.System_Int16
            or SpecialType.System_UInt16
            or SpecialType.System_Int32
            or SpecialType.System_UInt32
            or SpecialType.System_Int64
            or SpecialType.System_UInt64
            or SpecialType.System_Single
            or SpecialType.System_Double
            or SpecialType.System_Decimal => "0",
            _ => "default",
        };
    }

    protected string GetAccessibilityString(ITypeSymbol typeSymbol)
    {
        return typeSymbol.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal", // Default to internal for safety
        };
    }
}
