name: .NET Build and Test (NativeAOT)

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - release/*
    paths:
      - '**.csproj'
      - '**.cs'
      - '**./Directories.Build.props'
      - '.github/workflows/test-aot.yaml'

env:
  DOTNET_VERSION: '10.0.x'
  DOTNET_MONIKOR: 'net10.0'

jobs:
  native-aot-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish NativeAOT tests
        run: dotnet publish tests\Linqraft.Tests\Linqraft.Tests.csproj -c Release -o publish -f ${{ env.DOTNET_MONIKOR }} -r win-x64 -p:EnableNativeAotTest=true --self-contained true

      - name: Run NativeAOT tests
        run: .\publish\Linqraft.Tests
